### ISSUE TITLE
add support for task lists

### ISSUE THREAD

**Issue by erusev** [careteditor/caret#10]
https://help.github.com/articles/writing-on-github/#task-lists

**Comment by hkdobrev** [comment]
:+1: 

I imagine the only support Caret needs for that is the ability to check items from the preview similar to how GitHub works.

**Comment by erusev** [comment]
we could also have a simple auto-complete that works similarly to lists (ex: create an empty item on line break, remove it on a consecutive line break)

**Comment by hkdobrev** [comment]
@erusev Yes, that would be nice.

**Comment by astoilkov** [comment]
Done. You could start the app and wait for the footer to show up prompting you to restart the app.

**Comment by hkdobrev** [comment]
The task lists feature combined with the live preview is working great! Kudos!
