### ISSUE TITLE
TOC not creating link to heading sections correctly

### ISSUE THREAD

**Issue by jasondavis** [careteditor/caret#101]
I just realized that the HTML for the new TOC tag seems to correctly have an id attribute on the heading item however the links in the TOC menu all link to the current file instead of linking to the heading section:

`<a href="filename">Heading 1</a>`
  
instead of  
  
`<a href="#heading1">Heading 1</a>`

not sure if it is a windows only issue or not but here is a link from the TOC HTML on Windows:  

`<a href="E:\New folder\node_modules\nightmare\">Nightmare</a>`

**Comment by jasondavis** [comment]
One other thing.  I see it currently only supports H1 and H2 headings.  Could H3 and H4 be added possibly?   thanks

**Comment by jasondavis** [comment]
It seems this link issue might be an issue with the link parsing for Markdown...


### Link with http works as normal
`[image](http://www.codedevelopr.com) === <a href="http://www.codedevelopr.com">image</a>`

---

### Link without http results in filepath to markdown file with the link URL at the end:  

`[image](www.codedevelopr.com) ==== <a href="G:\htdocs\projects\www.codedevelopr.com">image</a>`

---

### Link to item in same page results in URL being the folder path to the current markdown file only

`[image](#image) === <a href="G:\htdocs\projects\">image</a>`

---

### Same as above but remove the # results in URL being file path to the markdown file folder with the markdown URL appended at the end  

`[image](image) === <a href="G:\htdocs\projects\image">image</a>`

**Comment by jasondavis** [comment]
Last idea for [[toc]]

Maybe think about adding a quick insert button in the menu like the other HTML element have.  Could maybe have a `[[toc]]` in the menu below the insert link and image menu items?

**Comment by astoilkov** [comment]
Hi @jasondavis,

This issue is now fixed in the latest Caret release(1.5.3). Thanks for reporting.

Regarding your questions:

> One other thing. I see it currently only supports H1 and H2 headings. Could H3 and H4 be added possibly? thanks

We decided to include only H1 and H2 because we believe Table of Contents should only show the most important titles in a document. However, in the future we plan to introduce a syntax which will let you configure this. Something like `[[toc maxLevel=4]]`

> Last idea for [[toc]]

> Maybe think about adding a quick insert button in the menu like the other HTML element have. Could maybe have a [[toc]] in the menu below the insert link and image menu items?

This is interesting idea. We will discuss it internally.

Thanks for the suggestions.

P.S. I will close this issue as a sign of fixing the bug. If you have any other suggestions do not hesitate to open a new issue.

**Comment by jasondavis** [comment]
Sorry I wasn't sure if I should post here or start a new issue as it is related to this issue.  

Just a comment on the `H3` and `H4`.  Here is the particular situation where I needed it most recently.

I have a document with an `H1` heading of **Project Media Items**.  It then has an `H2` heading of **Project Media Types**.  Under **Project Media Types** I have about 10 `H3` heading items which explain in detail info about each **Project Media Type** so in this case the TOC to the list of **Project Media Types** for `H3` headings would come in handy.

I respect your decision for only `H1` and `H2` for now but thought AI would at least pitch a scenario as to why it could be useful for more.  I also like the idea of `[[toc maxLevel=4]]` .

Also another idea.  Not sure how to best implement it but might be worth thinking about someday... The ability to have multiple TOC on a document.  Basically would allow you to have sub menus under different headings.  For example an `H2` heading might have its own TOC which list just the `H3` heading that are under that particular H2 heading.  Sounds complicated but would be a cool feature down the line!

Look forward to the future, keep it going!
