### ISSUE TITLE
TOC heading menu ideas

### ISSUE THREAD

**Issue by jasondavis** [careteditor/caret#103]
Sorry I wasn't sure if I should post here or start a new issue as it is related to this issue #101  [TOC not creating link to heading sections correctly ](https://github.com/careteditor/caret/issues/101)

Just a comment on the idea to add  `H3` and `H4` capability to the **TOC menu**.  Here is the particular situation where I needed it most recently.

I have a document with an `H1` heading of 
### H1 Heading - Project Media Items

 It then has an `H2` heading of 
### H2 Heading - Project Media Types

 Under **Project Media Types** I have about 10 `H3` heading items which explain in detail info about each **Project Media Type** so in this case the TOC to the list of **Project Media Types** for `H3` headings would come in handy.
### H3 Heading - Project Media Type 10

I respect your decision for only `H1` and `H2` for now but thought AI would at least pitch a scenario as to why it could be useful for more.  I also like the idea of `[[toc maxLevel=4]]` .
## Another idea for the TOC Menu

Also another idea.  Not sure how to best implement it but might be worth thinking about someday... The ability to have multiple TOC menus on a document.  Basically would allow you to have sub menus under different headings.  For example an `H2` heading might have its own TOC which list just the `H3` heading that are under that particular H2 heading.  Sounds complicated but would be a cool feature down the line!

Perhaps a parent heading could have some sort of ID which the `[[TOC parent="heading1"]]` tag could mention to make it list only sub-headings under that parent heading on that particular TOC menu.  Or to simplify and not require an ID be added to the parent heading, use the text from the parent heading as the id value in the TOC tag.  Just ideas, as a developer/programmer I have to mention my thoughts on possibble implementations! 

Look forward to the future, keep it going!

**Comment by astoilkov** [comment]
Hi @jasondavis,

In the latest version of Caret 1.13.0 we made the `[[toc]]` print all levels of heading. We hope you like that change.

I am closing this issue.

P.S. Regarding the second idea - We like it but it will probably take us some time to implement it. If you want to track its status please create a new issue with the description included.
