### ISSUE TITLE
List Item Return Without Creating a New List Item

### ISSUE THREAD

**Issue by bluej130** [careteditor/caret#108]
While making a list, you should be able to hold shift and go to the next line without creating a new list item.

**Comment by astoilkov** [comment]
Hi,

We implemented this. The feature will be available in the next Caret official release. I will close this issue when the update becomes official and could be downloaded.

**Comment by astoilkov** [comment]
Shift+Enter now never autocompletes in the latest 1.6.1 Caret release. 

Thanks for the suggestion.
