### ISSUE TITLE
add support for mathematical expressions

### ISSUE THREAD

**Issue by erusev** [careteditor/caret#11]
https://www.mathjax.org/

**Comment by debrouwere** [comment]
Faster: http://khan.github.io/KaTeX/

In Pandoc Markdown, mathematical expressions are delimited with $ for inline and $$ for display math (also in LaTeX), so it'd be nice to not try to parse anything inside those delimiters, e.g. `$a_1 b_2$` should not be rendered as "a _1 b_ 2" or somesuch.

**Comment by erusev** [comment]
Nice, thanks :sparkles:

**Comment by astoilkov** [comment]
Done. You could start the app and wait for the footer to show up prompting you to restart the app.
