### ISSUE TITLE
Shift click doesn't select text from current cursor position

### ISSUE THREAD

**Issue by AzavarSteve** [careteditor/caret#113]
When selecting text from the current cursor position to somewhere I click (using shift click), it appears to only select text from the last clicked cursor position, not the current cursor position as is the case after typing.

To recreate:
Click on a new line. Begin typing a sentence. (the cursor should appear to be at the end of the sentence) Hold shift and click to somewhere in the middle of the sentence.  The selected text should be from the cursor position to the middle (the last half), however, its actually selecting the first half, because its using the last *clicked* cursor position as the start point, instead of the current cursor position.

OS: Windows 10
Caret: Version 1.6.0

Thanks, love the editor so far!

**Comment by astoilkov** [comment]
This is now fixed in the latest 1.6.1 Caret release.

Thanks for reporting.

**Comment by AzavarSteve** [comment]
Awesome, works great now!
