### ISSUE TITLE
Trial version nag screen doesn't have a background, making it very difficult ot read

### ISSUE THREAD

**Issue by tesselode** [careteditor/caret#114]
![image](https://cloud.githubusercontent.com/assets/2637802/18900585/cc4e5242-8510-11e6-96bf-0dea8cbb623d.png)

In prior versions, the nag screen darkened the content behind it. Today I noticed that this is no longer happening. making it virtually impossible to read the message.

**Comment by astoilkov** [comment]
This is now fixed in the latest 1.6.1 Caret release.

Thanks for reporting.
