### ISSUE TITLE
“An error has occurred” while right-clicking selected text

### ISSUE THREAD

**Issue by acusti** [careteditor/caret#115]
Initial steps to reproduce (not particularly consistent):

Select some lines of text, cut it with command-x, undo with command-z, right-click the selection.

Though I didn’t have it reproducing consistently, I could generally get it to happen when using right (control)-click.

The initial generated issue content follows.

---------------

The following error has occurred:
```
{
    "message": "Cannot read property 'top' of undefined",
    "version": "1.6.0",
    "platform": "darwin",
    "os": "15.6.0",
    "path": "web/Editor/Editor.Menu.js",
    "code": "(this._editor.scrollIntoView(),this._editor.view.reflow(),e=this._editor.view.toPoint(i)),t.top=e.top,t.left=e.left,\" \"!=this._editor.text.getChar(i-1)",
    "line": 5,
    "column": 2376,
    "stack": [
        "at List._showing (web/Editor/Editor.Menu.js:5:2376)",
        "at List.trigger (web/Events.js:5:725)",
        "at List.show (web/Editor/Editor.Menu.js:5:1125)",
        "at HTMLElement.<anonymous> (packages/Editor/EditorDesktop.js:5:549)"
    ]
}
```

--------------

Here’s another error I got at another point while right-clicking some text:
```
{
    "message": "Cannot read property 'start' of undefined",
    "version": "1.6.0",
    "platform": "darwin",
    "os": "15.6.0",
    "path": "web/Editor/Editor.js",
    "code": "this[_0xeff5[13]][_0xeff5[59]](_0xb838x2[_0xeff5[51]],_0xb838x2[_0xeff5[53]])},lineRange:function(_0xb838x2)",
    "line": 5,
    "column": 8875,
    "stack": [
        "at Object.getText (web/Editor/Editor.js:5:8875)",
        "at /Applications/Caret.app/Contents/Resources/app.asar/web/Editor/Editor.Spellcheck.js:5:2895",
        "at Array.forEach ((native)",
        "at Object._camelCaseWordDivision (web/Editor/Editor.Spellcheck.js:5:2854)",
        "at Object._menuShowing (web/Editor/Editor.Spellcheck.js:5:4054)",
        "at Object.trigger (web/Events.js:5:725)",
        "at List._showing (web/Editor/Editor.Menu.js:5:2492)",
        "at List.trigger (web/Events.js:5:725)",
        "at List.show (web/Editor/Editor.Menu.js:5:1125)",
        "at HTMLElement.<anonymous> (packages/Editor/EditorDesktop.js:5:549)"
    ]
}
```

**Comment by astoilkov** [comment]
Hi @acusti,

We have fixed the second error. Today we will make a release containing that fix.

However, we couldn't replicate the first error. If you have any more specific steps or tips on when and how you successfully replicate it this would be of great help.

Thanks in advance.

**Comment by astoilkov** [comment]
Hi @acusti,

Can you still replicate any of the errors in Caret 1.6.1?

**Comment by acusti** [comment]
I’ll check today. Thanks for the quick turnaround!

Also, regarding the first error, I haven’t been able to recreate it. It happened a few times, then stopped happening. I’ll update if it comes back.

**Comment by acusti** [comment]
I can’t replicate any of the errors (Caret 1.7.0). Thanks!
