### ISSUE TITLE
Jumping by words (Ctrl+left/right) should behave as in other apps

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#118]
Currently, the jumping in the right direction jumps to the ends of the words like this:

```
The| quick| brown| fox| jumps| over| the| lazy| dog|
```

In the opposite direction (right to left), it jumps to the starts of the words like this:

```
|The |quick |brown |fox |jumps |over |the |lazy |dog
```

It's inconsistent and slightly annoying.

**Comment by astoilkov** [comment]
Hi @borekb,

Thanks for all issues you have reported.

Can you give an example for app that has different behavior compared to Caret? In my experience all apps behave the same way Caret do. For example Atom IDE commands are called "Move To End Of Word" and "Move To Start Of Word" which describes their behavior.

**Comment by borekb** [comment]
@astoilkov Hi, got an email notification with a question about what other apps behave the way I'm proposing and the answer would be almost every one, from MS Word / Office apps to browsers (Chrome, Firefox), text editors like Notepad++ etc. It's true that some apps behave similarly to caret.io (Sublime Text, Atom) but they are a minority. (I personally don't use these two editors so the behavior was really unnatural to me.)

**Comment by astoilkov** [comment]
Yes. I did you ask that question but then realized you are on Windows or Linux machine where the behavior is different. We will alter the behavior on those platforms to match the style of most of the apps.

Thanks for reporting.

**Comment by astoilkov** [comment]
The behavior of Ctrl+Left/Right is now changed in the latest Caret 1.7.0 release. You could check it out and get back to us if everything is ok.

**Comment by borekb** [comment]
Yes, perfect!
