### ISSUE TITLE
In-place preview like on GitHub

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#119]
Currently, caret implements previewing like most other desktop editors: by having two panels side by side. I always found this natural but nowadays, as I spend more on GitHub, I actually like their approach: you focus fully on Markdown and cannot see the preview. Preview is an explicit action that takes over the whole area. So I'm always fully focused on either writing or previewing, never distracted by seeing both.

I think this approach would fit caret's minimal approach, or at least as an option. For example, if right now I'm in the editing mode and the window is just about wide enough to accommodate the text, switching to preview makes both panel unrealistically narrow and hard to read.

What do you think?

**Comment by borekb** [comment]
@astoilkov what do you think about this? It's probably no. 1 on my personal wishlist as I usually have the Caret window about 1000px wide and 500px previews are not much fun.

**Comment by astoilkov** [comment]
I am closing this issue in favor of https://github.com/careteditor/caret/issues/129. They seem to describe the same thing.

We are already working on implementing this in the app.
