### ISSUE TITLE
"etc." incorrect spell checking

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#120]
Minor bug: `etc.` is always detected as a spelling error.

**Comment by astoilkov** [comment]
This is fixed and will be available in the next 1.7.1 release. We have made "etc" to always be correct regardless of having a dot after it or not. However, we will do some spellchecker improvements in the future and we will make it so "etc" is considered wrong when you don't have a dot after it.

**Comment by borekb** [comment]
This is much appreciated, guys. I can imagine that dealing with cross-platform spell checking issues is a major pain in the butt and you'd rather focus on other things but spell checking "unfortunately" is part of the core experience when writing texts. Thanks for putting such effort into this!

**Comment by astoilkov** [comment]
Caret 1.7.1 is now available so I am closing this issue.
