### ISSUE TITLE
Ctrl+Home / Ctrl+End navigation doesn't work

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#121]
`Ctrl+Home` should jump the caret to the beginning of the document, `Ctrl+End` to the end. These shortcuts don't seem to work (at least on Windows).

**Comment by astoilkov** [comment]
Thanks for reporting. We will fix this soon.

**Comment by borekb** [comment]
Also just noticed that <kbd>Ctrl+↓</kbd> and <kbd>Ctrl+↑</kbd> behave like <kbd>Ctrl+Home</kbd> and <kbd>Ctrl+End</kbd> which is incorrect: <kbd>Ctrl+↓</kbd> and <kbd>Ctrl+↑</kbd> should scroll the viewport without moving the caret (at least on Windows).

The problem is that if I accidentally press <kbd>Ctrl+↓</kbd> in a long document, it's hard to get back to previous caret location. (BTW some advanced editors and IDEs have a shortcut to go to last edit location which I often find useful but understand that it might be an overkill for a simple editor like Caret.)

**Comment by astoilkov** [comment]
We have implemented `Ctrl+Home` and `Ctrl+End` under Windows in Caret 1.7.0.

Additionally, I experimented with <kbd>Ctrl+↓</kbd> and <kbd>Ctrl+↑</kbd> but noticed a different behavior in WordPad where these keys move the cursor to next/prev line. In what application these keys scroll the viewport.

Regarding the shortcut to go to last edit location: We are thinking of implementing such feature in the future.

**Comment by borekb** [comment]
1. <kbd>Ctrl+Home/End</kbd> works great, thanks!
2. I thought that scrolling on <kbd>Ctrl + up/down keys</kbd> is a standard behavior on Windows but you're right that it doesn't work everywhere. But I tried a couple of text editors and they commonly implement this (Notepad++, VS Code, ...). However, the most important thing for me is that <kbd>Ctrl+up/down</kbd> **doesn't** jump across the document.
3. Cool!

**Comment by astoilkov** [comment]
We have changed `Ctrl+up/down` to not perform any action for now. We will see if there is any demand for this key combination and then decide what to do. You could expect to see this change in the next 1.7.1 release.

Closing this issue now as it was initially regarding other problem.
