### ISSUE TITLE
Nest list items with 4 spaces, not 2

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#126]
Nested list items indented by just 2 spaces are not considered nested by some Markdown implementations (even some important ones): [Babelmark](http://johnmacfarlane.net/babelmark2/?text=-+First+list+item%0A++-+Nested+item%0A-+Second+list+item). Four spaces are [much safer](http://johnmacfarlane.net/babelmark2/?text=-+First+list+item%0A++++-+Nested+item%0A-+Second+list+item).

**Comment by erusev** [comment]
That's true and it's not just for lists. There are multiple cases where parsers disagree. We try to follow CommonMark (from the creator of Babelmark) as it's perhaps the only thing that comes close to a Markdown standard and according to CommonMark.
