### ISSUE TITLE
Spell checking error even after adding a word to dictionary

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#128]
I've added the word "Mergnout" to a custom dictionary, however, when I write it the second time, it is marked as incorrect:

![image](https://cloud.githubusercontent.com/assets/101152/19023942/769832ee-88fa-11e6-9c3f-30a03290f815.png)

It's weird that Caret doesn't detect the first occurrence as an error but it does for the second one.

**Comment by astoilkov** [comment]
Thanks. We will investigate.

**Comment by astoilkov** [comment]
Just a quick question. What happened after your restarted the app? Do the spell suggestions were marked as incorrect or correct?

**Comment by borekb** [comment]
All is fine now in 1.7.0. Thanks!

**Comment by astoilkov** [comment]
Great.

Closing this.
