### ISSUE TITLE
Toggle Read/Edit mode

### ISSUE THREAD

**Issue by mlinchitstest** [careteditor/caret#129]
It would be nice if there was an easy way to switch between reading and editing. Sometimes I just want to read the file. All you'd have to do is toggle the editor pane on/off. Would be nice if you could just toggle between edit and preview with a keyboard shortcut.

**Comment by borekb** [comment]
+1, I've created a similar issue last week: https://github.com/careteditor/caret/issues/119

**Comment by erusev** [comment]
Makes sense, we're are working on something to address that :)

**Comment by astoilkov** [comment]
We implemented a full screen preview `View -> Preview` which probably meets your requirements.

I will close this issue but if you had something different in mind don't hesitate to write here so we could reopen the thread.
