### ISSUE TITLE
Both 1.6.1 and 1.7.0 installed??

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#136]
A strange thing is happening on my PC:

- When I search for Caret in the Start menu, it has the "C" icon and starts version 1.7.0. (Strangely, in the taskbar, the icon is the dark square one.)
- When I doube-click a `.md` file in Windows Explorer, version 1.6.1 is started.

Not sure what's going on..

**Comment by astoilkov** [comment]
What about if you open Programs and Features where you could uninstall apps?

**Comment by borekb** [comment]
Single one, just "Caret". When I go to properties of the taskbar icon, this is the path that is launched:

`C:\Users\borek\AppData\Local\Caret\Update.exe --processStart Caret.exe`

**Comment by borekb** [comment]
Strange, the double-click was trying to open `C:\Users\borek\AppData\Local\Caret\app-1.6.1 %1`. I deleted that folder entirely, now I can't double-click the MD files but I'm not sure what the "open with" app should be. There is `C:\Users\borek\AppData\Local\Caret\Update.exe` which doesn't sound right, then version-specific EXE file in `app-1.7.0` which, if I set, I will have the same problem after you guys release a new version.

**Comment by astoilkov** [comment]
Why don't you try to just uninstall the app and redownload it from the website.

We test every release and update the version on a Windows PC but we have never experienced such an issue.

**Comment by borekb** [comment]
That surely helps but I guess that after another update, when I have more `app-x.y.z` folders again, the problem will be back again?

I'm not sure what the "Open with" for `.md` files should be. `Update.exe` or `Caret.exe`? `Update.exe` doesn't seem to launch anything, `Caret.exe` is version-specific so my system will be confused after Caret updates itself to a newer version.

**Comment by astoilkov** [comment]
We have made a change in the way app updates its file associations. Could you update to Caret 1.7.1 and see if the problem will be resolved.

**Comment by borekb** [comment]
Yes it is resolved, very cool response guys! 👍

**Comment by astoilkov** [comment]
Great to hear and thanks a lot for reporting these issues and helping us improve the app experience.
