### ISSUE TITLE
Auto-complete for emoji

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#137]
An idea, maybe already on your list: I start typing `:`, press Ctrl+Space and Caret auto-completes all the emoji, possibly even with previews.

I know, the emoji generation :)

**Comment by erusev** [comment]
> An idea, maybe already on your list

Yes, we love this idea and can't wait to implement it

**Comment by borekb** [comment]
To add to this, it would be really cool if I could choose between the `:emoji:` format or a real unicode character. Maybe on an explicit Ctrl+Space, e.g., I have `:clap:` written, press Ctrl+Space, there is an action "convert to unicode character" which inserts 👏 .

The reason is that it's generally easier to work with `:emoji:` if the document is going to be rendered outside of GitHub, real unicode chars need to be used.

**Comment by erusev** [comment]
That's sounds really cool, indeed, and it shouldn't be too difficult to implement.

**Comment by astoilkov** [comment]
We are happy to say we implemented autocompletion for emojis in the latest Caret 1.8.0 release. We also added autocompletion for languages in fenced code block.

Closing this.

**Comment by borekb** [comment]
Autocomplete works nice! How about the "convert to Unicode character" action? Should I create a separate issue to track it?

**Comment by astoilkov** [comment]
Yes. We will do it but if you want to track it you could create a new issue.

**Comment by borekb** [comment]
No that's fine, I'm looking forward to it :)
