### ISSUE TITLE
Paste link over a selected text

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#140]
A cool feature of some editors is that when I have a selection in the editor and a link in my clipboard, <kbd>Ctrl+V</kbd> will simply turn it into `[text](link)`. Would be nice to have in Caret as well.

**Comment by erusev** [comment]
Nice, I think we can do that.

**Comment by astoilkov** [comment]
I am happy to say this is now implemented in the latest Caret release.

Closing this.

**Comment by borekb** [comment]
Excellent!
