### ISSUE TITLE
The menu should reveal on full Alt press, not just key down

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#141]
https://github.com/careteditor/caret/issues/135 introduced Alt support but it's implemented on key down, not key press (down and back up). This means that when I try to type a character like <kbd>Alt+064</kbd> for `@`, or some national characters using <kbd>AltGr+\<number\></kbd>, it's impossible.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.7.2 release. Now the menu is opened only if Alt pressed without any other keys in between.

Sorry for the inconvenience.

**Comment by borekb** [comment]
Thanks!

Another thing I noticed is that Alt pressed for the second time doesn't close the menu.

**Comment by astoilkov** [comment]
Unfortunately, closing the menu when hitting Alt a second time can't be implemented at the moment. The cross platform implementation seems too hard.

**Comment by borekb** [comment]
No problem, it's a minor thing.
