### ISSUE TITLE
Mid-screen scrolling performance and preview window

### ISSUE THREAD

**Issue by ghost** [careteditor/caret#142]
**Mid-screen scrolling:** I would expect the mid-screen scrolling to keep the **working line** always in the middle of the screen. This goes not only for when one has written down to half a page (as it is now) but also from the start: (empty document -> cursor in the middle) and not only for writing but also when moving around (so lines move up and down but the cursor is always in the middle).

**Preview window:** As it is now it works good if one wants to see how the document is going to look like. By separating both, Caret becomes not only a writing app but also a reading one and it is easy to focus one thing at a time.

Both features are to be found in iaWriter (sorry for the comparisons)

Otherwise Caret is looking better and better

**Comment by erusev** [comment]
Thanks a lot for getting in touch.

I agree about the mid-screen scrolling - we implement the new behavior in 1.8 or 1.9.

As to "preview window", do you mean that there should be a way to open preview in another window?

Thanks again.

**Comment by mokudo** [comment]
>As to "preview window", do you mean that there should be a way to open preview in another window?

Yes, that is what I mean. Pressing `Cmd + R` (or another short-cut) changes the view from writing mode to reading mode and back again as needed. It could be an alternative to the actual behaviour (without excluding each other)

**Comment by erusev** [comment]
Would it help if we introduce a shortcut that opens a preview that takes up the whole window (as opposed to the right half)?

**Comment by mokudo** [comment]
Yes, sure! I don't know if it is better to "change modes" instead of opening windows? F.ex. I'm writing in "write mode" then I press a shortcut and the window changes into "read mode". I press the shortcut again and I'm back in write mode

It could also open a new window but that would add "noise" to the screen - anyway it is important that the shortcut takes us back to write mode again.

**Comment by erusev** [comment]
Yes, that's how it would work and btw, we'll also make it possible to edit your text directly in preview.

**Comment by mokudo** [comment]
That sounds great! Looking forward to it!

**Comment by astoilkov** [comment]
Both things described in the first comment are now supported in the Caret 2.0 release.

  - Mid-screen scrolling now always keeps the cursor line in the middle of the screen
  - Full screen preview is now available via `Cmd/Ctrl+Shift+R`

Closing this issue. Thanks for the ideas.
