### ISSUE TITLE
Strange request to save a file when opening another file

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#144]
The steps to reproduce are something like this (not sure exactly as I cannot reproduce this every time):
1. Open Caret with a new document (untitled, unsaved), write some text in it
2. Go to Windows Explorer, double-click some MD file (I've got `*.md` associated with Caret)
3. Second instance of Caret will be opening, asking you whether you want to save the unsaved changes from the first instance
4. I click "no/cancel", the second document opens just fine, both Caret instances are running fine but it was strange that I saw the "do you want to save changes" dialog.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.10.0 release.

This was very interesting problem. Thanks for reporting.

Closing this issue.
