### ISSUE TITLE
Blank window on Linux (Debian Jessie)

### ISSUE THREAD

**Issue by cebe** [careteditor/caret#145]
I just downloaded the `Caret.deb` from the [latest release](https://github.com/careteditor/caret/releases/tag/1.7.2).

Starting Caret only shows a blank window. I tried starting from applications menu and also via console to check whether there  is any debug output.

![bildschirmfoto von 2016-10-13 11 44 34](https://cloud.githubusercontent.com/assets/189796/19344523/ca4e74c8-913a-11e6-8c76-c0ce54bfd04e.png)

OS: Debian 8 (Jessie)
Desktop Env: Gnome3

Is there a way to provide you with more debug info?

**Comment by erusev** [comment]
Hm, that's weird, do other Electron apps work alright on that OS (ex: Atom, WebTorrent, etc.)? Thanks

**Comment by cebe** [comment]
I am not using any of these but I can check it.

**Comment by cebe** [comment]
The electron quickstart app runs fine: https://github.com/electron/electron-quick-start#to-use

**Comment by cebe** [comment]
Is there a way to enable some kind of debug output?

**Comment by axelinternet** [comment]
I have this same issue on ubuntu 14.04 running unity. Other electron apps work fine

**Comment by cebe** [comment]
@erusev is there a way to debug this? Do you have some debug binary that generates some more output about what is happening?

**Comment by erusev** [comment]
@cebe not at this point, but we did manage to reproduce the issue on one of our machines so there's a good chance we fix it, meanwhile, if i think of something that you could do to get more debug info, i'll let you know, thanks

**Comment by erusev** [comment]
@cebe could you try and install 1.7.0 or older and see if it'd work? Thanks

**Comment by cebe** [comment]
I think I already tried an older release, do not remember which one. Will try again.

**Comment by erusev** [comment]
@axelinternet do you think you could do the same - install 1.7 or earlier to see if it'd work? We used a different build process until 1.7 and we want to find out if it makes a difference

**Comment by axelinternet** [comment]
@erusev Works fine in 1.7!

**Comment by cebe** [comment]
this is 1.7.0 for me... does not look right.

![bildschirmfoto von 2016-11-30 17 40 02](https://cloud.githubusercontent.com/assets/189796/20761735/3b19466a-b724-11e6-90ac-6781649ef0fd.png)

**Comment by cebe** [comment]
1.7.2 is the same empty window as initially shown.

**Comment by erusev** [comment]
Does it let you write?

**Comment by cebe** [comment]
yes, similar in 1.6.1:

![bildschirmfoto von 2016-11-30 17 47 59](https://cloud.githubusercontent.com/assets/189796/20762012/31eb7cd8-b725-11e6-9a07-661aa353279c.png)

**Comment by cebe** [comment]
Is that the normal window how it should be? I'd have expected a menu bar and maybe some other elements inside the window :)

**Comment by erusev** [comment]
Well, it is supposed to have a menu bar, we'll have to look into why you don't see one, but there should be no other elements, it's meant to be a clean experience :)

**Comment by erusev** [comment]
We'll update our build process so that next version (1.10) should be able to install fine on your OS

**Comment by cebe** [comment]
great, thanks. looking forward to it :)

**Comment by erusev** [comment]
@cebe if you hit `alt` does the menu appear

**Comment by cebe** [comment]
It does! at least on 1.6.1. Quite sure on the latest release it did not respond to anything.

**Comment by erusev** [comment]
Just released 1.10 using the updated build process - @axelinternet @cebe you should be able to install it

**Comment by cebe** [comment]
Works great, thank you! Purchased a License :)

**Comment by erusev** [comment]
Great, thanks !
