### ISSUE TITLE
Ctrl+right: jump to the end of the block even if there is no dot at the end of line

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#147]
I'm generally happy with the Cltr+right/left behavior implemented in https://github.com/careteditor/caret/issues/118, there is just one annoyance: if the line doesn't end with a non-letter character like a dot, Ctrl+right jumps to the next word which might be quite further down the document if there are e.g. blank lines etc.

These are the jump stops in an example document:

```
|# |Heading

|Paragraph |one|.

|Paragraph |two|.
```

Note that there is no stop at the end of the heading. MS Word, for example, would stop there which is the right behavior I believe. (It's true that Chrome is even worse: it never stops at the end of the line which is annoying.)

**Comment by borekb** [comment]
To add to this, say that I want to select the last word of the heading. I press Ctrl+Shift+right arrow but instead of having just the word selected, I also have a couple of newlines (and possibly other markdown) selected.

**Comment by astoilkov** [comment]
Just to clarify is these the correct stops that you would expect:

```
|# |Heading|

Paragraph |one|.|

Paragraph |two|.|
```

**Comment by borekb** [comment]
Yes (you're missing stops at the beginning of paragraphs but that's probably just an oversight; it should be like this:

```
|# |Heading|

|Paragraph |one|.|

|Paragraph |two|.|
```

)

**Comment by borekb** [comment]
Got me thinking why most editors stop after the final dot in a paragraph but it seems to be the common behavior so I'd stick to it.

**Comment by borekb** [comment]
@astoilkov Any chance this would find its way into Caret anytime soon? I'm encountering this quite often, the improved editing experience would be awesome.

**Comment by astoilkov** [comment]
Indeed. I agree we should fix this. I will take a look at it in the next few days.

**Comment by astoilkov** [comment]
Is the new behavior in the 2.0 release working out for you?

**Comment by borekb** [comment]
Yes, great!

**Comment by astoilkov** [comment]
Closing this issue then.
