### ISSUE TITLE
"PhpStorm" cannot be added to custom dictionary, always marked as spelling mistake

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#148]
![image](https://cloud.githubusercontent.com/assets/101152/19524522/5043f372-961e-11e6-8b34-5ca87fd3d071.png)

There is no way to add the word PhpStorm to a custom dictionary. I guess the spell checker checks the words "Php" and "Storm" separately, I don't get any spelling suggestion on Ctrl+Space.

**Comment by astoilkov** [comment]
For now you could move your cursor in front of the word, hit Ctrl+Space and select add to dictionary so you add both Php word to the dictionary.

**Comment by borekb** [comment]
That fixes "PhpStorm" but introduces another issue because "Php" is not a correct word and I want to see it marked as spelling error when found separately.

**Comment by astoilkov** [comment]
The behaviour is now changed in the latest Caret 1.8.0 release. Words are no longer divided into subwords for spellchecking.

Closing this.
