### ISSUE TITLE
Text/cursor location out of sync

### ISSUE THREAD

**Issue by Jwashton** [careteditor/caret#149]
I have been noticing some odd text-wrapping behavior in newer versions of Caret. The only characters I type in this gif are letters and spaces. This problem goes away if I change the font size, but comes back when I restore the original setting. To an outside observer this would seem to indicate that this is a reproducible failure in some end-of-line calculation. Maybe if the first character of the wrapped line is a space? I'm not sure.

![rtf](https://cloud.githubusercontent.com/assets/3431482/19574724/91ddb01e-96d9-11e6-8255-fcfaf0a38602.gif)

I am running Caret 1.7.2 on Fedora 24 with GNOME 3.20.2 as my shell. If there are any other metrics you need, let me know and I'll be happy to see what I can provide.

**Comment by erusev** [comment]
Thanks, we managed to reproduce to reproduce the issue, we'll investigate.

**Comment by erusev** [comment]
Ok, we fixed it, we'll release a patch version early next week.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.8.0 release.

Closing this.
