### ISSUE TITLE
Error saving a file

### ISSUE THREAD

**Issue by vjdhama** [careteditor/caret#15]
The following error has occurred:
```
{
    "type": "javascript-error",
    "message": "Uncaught Error: EACCES: permission denied, open '/rails_notes.md'",
    "path": "fs.js",
    "line": 549,
    "platform": "darwin",
    "os": "MacIntel"
}
```

**Comment by vjdhama** [comment]
While I think it's obvious that caret couldn't save the file because it didn't have necessary permissions to create a file, it should have taken care of such edge cases.

**Comment by astoilkov** [comment]
We introduced a way to handle files with limited read/write permissions.

You should get an in-app update notification in the next few days.

Thanks for reporting this.
