### ISSUE TITLE
Cursor jumps randomly inside tables

### ISSUE THREAD

**Issue by henrikstroem** [careteditor/caret#150]
After hours of use, sometimes the cursor starts jumping to a seemingly random position after each keystroke when editing tables.

On macOS Sierra 10.12 16A323.

**Comment by borekb** [comment]
Not sure if related but on Windows, after some usage, the caret (like the vertical thing, `|`, not the Caret editor itself :) ) sometimes stops responding to left/right arrows. I need to mouse-click to a certain location to edit there. Not sure when this happens and why but I've seen this at least a dozen times.

**Comment by borekb** [comment]
Found an important detail: the arrows stop working after I write backslash at the end of a line (e.g., to force line break in Markdown).

So pressing this sequence does not move the cursor: <kbd>\\</kbd> <kbd>↑</kbd> (or any other arrow).

**Comment by astoilkov** [comment]
Hi @borekb,

We have successfully replicated your problem. We will investigate it further so we can fix it.

**Comment by astoilkov** [comment]
Hey @henrikstroem,

Do you still experience the same problem in the current release of Caret?

**Comment by henrikstroem** [comment]
I gave up on Caret - I could not live with the quality of the product, so I don't know if the problem is still there.

**Comment by erusev** [comment]
@henrikstroem Could you point to specific issues with the quality that you've experienced so that we could work on them? This would be very helpful! Thanks.

**Comment by henrikstroem** [comment]
The reason I picked Caret in the first place was that I had to do a lot of tables in a report I was writing.

This problem with the jumping cursor and the fact that wide tables would not stay on one line, and they were almost impossible to read and work with when spreading over multiple lines, forced me to go back to TextMate to do the tables, even though it does not handle tables automatically. I later found Typora, which handled these things a lot better, but now more or less given up on Markdown and turned to just using Latex, which gives me more flexibility with tables.

My problem was that I had to insert Latex cross-references and citations, and they easily become very long.

**Comment by erusev** [comment]
@henrikstroem 

Thanks for the quick response. We're working on an option that will disable wrapping for tables and code blocks as well as a feature that we call "edit in preview" that resembles the default writing mode in Typora - if you want, I can write to you when we have these features.

**Comment by astoilkov** [comment]
We have made couple of improvements to the table resizing algorithm in Caret 1.13.0. This issue should be fixed there.

Additionally, we introduced `lineWidth` property available for setup in Preferences which enables easy editing of big tables.

Closing this issue.

**Comment by borekb** [comment]
Not sure if technically possible but tables should be exempt from line wrapping, IMO. The tricky part would be the horizontal scrollbar: it should be visible if the table is wider than the viewport but as I scroll it, the standard paragraphs should not re-flow: they should be wrapped at 72 (or whatever configured) line width.

Setting `lineWidth` to something very wide just for tables isn't something I would personally do.

**Comment by astoilkov** [comment]
Yeah. Absolutely. We have exactly the same idea. However, this is really hard to implement and it will takes us some time to find a suitable solution. This is why we introduced `lineWidth` for now.
