### ISSUE TITLE
Save documents as .txt file

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#152]
Would be nice to be able to save as a .txt file, not just .md, so that other apps can easily recognize and open the text file on Windows.

**Comment by astoilkov** [comment]
Thanks for the suggestions. We have added support for saving .txt files. It will be available in the next release. I will close this issue when the update is available for download.

**Comment by astoilkov** [comment]
This is now available in the latest Caret 1.8.0 release.

Closing this issue.
