### ISSUE TITLE
Enter key does not work properly in code blocks.

### ISSUE THREAD

**Issue by szainmehdi** [careteditor/caret#156]
In version 1.8.0, the enter seems to have buggy behavior when the caret is inside a code block.

See the gif/video here: http://recordit.co/8MIwu9J2WW

It seems like in many places, I'm having to use Shift + Enter to move for a line return.

**Comment by astoilkov** [comment]
We just pushed an update of Caret 1.8.1 which includes a bug fix for this issue.

Thanks for reporting and for the great explanation video.

Closing this.

**Comment by szainmehdi** [comment]
Thank you @astoilkov! 👍
