### ISSUE TITLE
[Request] Add option to automatically strip trailing whitespace.

### ISSUE THREAD

**Issue by szainmehdi** [careteditor/caret#157]
It'd be really helpful if Caret could strip trailing whitespace from a file, like most editors would.

**Comment by erusev** [comment]
Sounds nice, but unfortunately, this would break a lot of documents as in markdown trailing spaces have meaning - 2 trailing spaces = line break

**Comment by szainmehdi** [comment]
Got it. Thank you for taking a look!

**Comment by borekb** [comment]
Related: https://github.com/careteditor/caret/issues/146
