### ISSUE TITLE
Crash when creating new doc (osx)

### ISSUE THREAD

**Issue by Jursdotme** [careteditor/caret#158]
After the most recent update (1.8.0) the app crashes when i try to use the "File>new" shortcut `cmd+N`.

Creating new files through the top menu still works.

System:
macOS Sierra 10.12.1 (16B2555)
MacBook Pro (Retina, Mid 2012)

**Comment by astoilkov** [comment]
Does this happens consistently after a new app launch or it happened just once?

**Comment by Jursdotme** [comment]
I have tested it a little further. It seems that it may not be that tied to the keyboard command.

- A new doc is successfully created at app startup.
- If i create a new doc while one is opening and i get prompted to save. It works.
- If the app is open and no document is open. It crashes.

This seems to be regardless of using the topbar or the shortcut.

**Comment by astoilkov** [comment]
We just release a new version 1.8.1 of Caret. The issue should be fixed there. Could you update and try it?

Thanks in advance.

**Comment by Jursdotme** [comment]
Wow, that was fast and is seems to have fixed it. 

Much obliged.

**Comment by astoilkov** [comment]
Nice. Happy to hear that.
