### ISSUE TITLE
Issue while trying to save note

### ISSUE THREAD

**Issue by wmv** [careteditor/caret#16]
The following error has occurred:
```
{
    "type": "javascript-error",
    "message": "Uncaught Error: EACCES: permission denied, open '/2015-11-28.md'",
    "path": "fs.js",
    "line": 549,
    "platform": "darwin",
    "os": "MacIntel"
}
```

This occurred because the default directory is set as root; Perhaps set it to current user's home folder?

**Comment by erusev** [comment]
This is fixed in the latest version. You should get an update sometime next week. Thanks for reporting.
