### ISSUE TITLE
Add support for Fira Code font

### ISSUE THREAD

**Issue by zapatoche** [careteditor/caret#160]
https://github.com/tonsky/FiraCode

because why not? and ligatures

**Comment by erusev** [comment]
Makes sense, we'll add support for custom fonts where you'll be able to use any font you like.

**Comment by astoilkov** [comment]
Hi @zapatoche,

We introduced Preferences in Caret 1.13.0 where you could set your font to Fira Code. Hope you like it.

Closing this. Have a great day.

**Comment by zapatoche** [comment]
A W E S O M E

**Comment by zapatoche** [comment]
Hi There,

I'd just like to mention that as from 1.14.2 the ligatures stopped working.

Cheers

(i've just upgrade from 1.13.0)

**Comment by astoilkov** [comment]
Yep. Indeed. We made a change that disable font ligatures. We will fix this issue in the next 1.14.3 release.

Thanks for reporting.

**Comment by astoilkov** [comment]
Hi @zapatoche,

1.14.3 release is now available for update. Sorry for the inconvenience.

**Comment by zapatoche** [comment]
already on it :)

Thanks for the update
