### ISSUE TITLE
Double click selects wrong word

### ISSUE THREAD

**Issue by henrikstroem** [careteditor/caret#161]
Double clicking a word doesn't select the word, but the next or next again word.

**Comment by erusev** [comment]
Could you share OS and Caret version, also, can you reproduce this in a different text? Thanks

**Comment by henrikstroem** [comment]
Caret 1.8.2
macOS 10.12.1 (16B2555)

After restarting Caret the problem is gone.

**Comment by erusev** [comment]
Thanks, we'll invetigate

**Comment by astoilkov** [comment]
We think we found the reason for the issue. This should be now resolved in the latest Caret release. It shouldn't happen any more.

Thanks for reporting. Closing this issue.
