### ISSUE TITLE
Start with blank file, instead of reopening the last edited

### ISSUE THREAD

**Issue by johncja** [careteditor/caret#163]
It will be useful if we can launch Caret with just new blank file, instead of auto-opening the last edited.

For example, my typlical workflow for quick notetaking with Word:

1. Click the Word icon on taskbar > 2. Type something into blank new document > 3. Press Ctr+S > 4. Don't type filename, just press Enter to keep the automatically generated filename > 5. Close window.

In Word, it will be saved by default to desktop, with filename automatically generated from the 1st paragraph of document.

**Comment by erusev** [comment]
I understand, I use a similar workflow for note taking, but we want to optimize caret for use cases like writing blog posts, documentation, books, etc. and that's the reason it works like this, I hope this makes sense.

I'll close this, but please, let me know if I'm missing something.
