### ISSUE TITLE
Path and filename are not visible for deeply-located files

### ISSUE THREAD

**Issue by johncja** [careteditor/caret#165]
If I open a file somewhere in a deep hiearchy of folders, like this:

```
C:\Users\John\Desktop\New folder\New folder\New folder\New folder\New folder\New folder\foo.md
```

I would not be able to see neither full path nor filename. Here is a screenshot:

![caret](https://cloud.githubusercontent.com/assets/18004961/20119335/3a31f3e4-a619-11e6-9a93-307d232e8554.PNG)

And here is a another screenshot. I taked Sublime as example, but it's a typical ui-conception for almost all Windows applications:

![sublime](https://cloud.githubusercontent.com/assets/18004961/20119463/ae04e452-a619-11e6-8b43-210ede6d93e2.PNG)

As you can see, at second screenshot the full path and also a filename are both perfectly visible.

**Comment by erusev** [comment]
Thanks, it's a valid issue, we'll see what we can do.

**Comment by astoilkov** [comment]
I am closing this issue in favor of #194

@johncja - you could follow the progress of this issue there
