### ISSUE TITLE
Adding comma(,) with Spelling Check ON

### ISSUE THREAD

**Issue by ardian** [careteditor/caret#166]
Hi there,

I am having an issue when using a comma in any of the words I write, the spell checker thinks it's a mistake.

Caret version: 1.8.2
OS: GNU/Linux (Fedora 24)
![comma-caret](https://cloud.githubusercontent.com/assets/172661/20123568/3887e93e-a620-11e6-9907-95888a409232.png)

**Comment by astoilkov** [comment]
Thanks for reporting. We will investigate this issue.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret release.

Closing this.
