### ISSUE TITLE
Double-click on Word for Spellcheck

### ISSUE THREAD

**Issue by ardian** [careteditor/caret#169]
Hi,

if I have mistyped a word, and then I double click on the word to get a suggestion for fixing, it sometimes selects all the sentence. This problem appeared with the last version of Caret.

I can't really re-produce this, because I am not understanding when this is happening.

OS: GNU/Linux (Fedora 24)
Caret: Caret 1.8.2

![1](https://cloud.githubusercontent.com/assets/172661/20239163/516a93c0-a8fa-11e6-8599-c802fce76198.png)

Thanks!

**Comment by astoilkov** [comment]
Are you sure this doesn't happen when you triple click? We use triple click to select the entire line which is the behaviour of most desktop applications.

Have you tried using Ctrl+Space? This could be really helpful for faster fixing of spelling mistakes.

**Comment by ardian** [comment]
@astoilkov Just tried it again, I have the same issue. To be more specific, if you double click it will select the single word, but the moment I right click on it to get a suggestion it selects the complete sentence.

**Comment by astoilkov** [comment]
With the additional information I was able to replicate the issue and fix it. The fix will be included in the next application release.

Thanks.

**Comment by ardian** [comment]
Awesome! 

Thanks.
