### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by vjdhama** [careteditor/caret#17]
Autosave is a nice feature, since user doesn't have to save the file every time there's a change. It would be nice if caret supported it. Maybe it can be added to roadmap.

**Comment by erusev** [comment]
@vjdhama It is in the roadmap, it's one of the features that we plan for 2.0.

**Comment by astoilkov** [comment]
We are happy to say we have implemented Autosave functionality in the latest Caret 1.7.0 release. You could turn it on by going to Preferences -> Autosave.

Closing this issue.
