### ISSUE TITLE
Right click doesn't update caret position to new mouse position

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#170]
If I move the caret to one area of text, then right click on an other area of text, the drop down will act as if I was right clicking on the area of text the caret was on, not where the mouse was right clicking. 

I think  the behavior of where the drop down is activated should follow the mouse position and not the current caret position, as that is inaccurate and not how most word processors function.

In Word for example, right clicking both moves the caret **and** activates the right click dropdown

**Comment by astoilkov** [comment]
We have caught the problem and we fixed it. The fix will be available in the next Caret release.

Thanks for reporting.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret release.

Closing this.
