### ISSUE TITLE
How to create multiple cursors?

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#174]
Caret 1.9 [introduced](https://caret.io/releases#v1.9) multiple cursors, how to use them?

**Comment by erusev** [comment]
It should be Cmd (or Ctrl) + G - i'll add it to the release notes

**Comment by borekb** [comment]
Does it work without a selection? For instance, in VS Code, I can Alt+click anywhere to create multiple cursors. Ctrl+D only seems to work with selected text which I don't always have.

**Comment by astoilkov** [comment]
We have added `Alt+Click` for creating multiple cursors. It will be available in the next version of Caret.

Closing this issue.
