### ISSUE TITLE
Path completion: use forward slashes even on Windows

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#175]
Path completion is a nice little feature of Caret:

![image](https://cloud.githubusercontent.com/assets/101152/20555716/b38e7406-b163-11e6-857b-13e1d265f156.png)

However, it inserts backslashes on Windows. As the paths are most often URLs, I think those should be forward slashes regardless of the OS.

**Comment by astoilkov** [comment]
Yes. I agree. Will do that.

**Comment by astoilkov** [comment]
This is available in the latest Caret release.

Closing this.
