### ISSUE TITLE
Disappearing text bug

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#180]
See what happens after I press Enter:

![caret-bug](https://cloud.githubusercontent.com/assets/101152/20748997/c8920588-b6f0-11e6-849b-44d4fbadcfba.gif)

Happens with both caret at the start and end of the line.

**Comment by astoilkov** [comment]
Nice catch. Thanks for reporthing.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.10.0 release.

Closing this issue.
