### ISSUE TITLE
Caret mis-positionned

### ISSUE THREAD

**Issue by nio101** [careteditor/caret#182]
On ubuntu 16.04, introduced with the latest 1.10.0, the caret is now mis-positionned one or two characters on the right and the editor is no more usable. :(

**Comment by astoilkov** [comment]
Does this happen for a specific text or it happens on a black app window?

**Comment by nio101** [comment]
The new version opened on a previous text I was editing. Re-selecting the font & font default size fixed the issue... I can't reproduce it now... :s

**Comment by astoilkov** [comment]
Thanks for the information. I hope this doesn't happen again.

I will close this issue for now but if you experience the problem again do not hesitate to write here so we could reopen the the issue and investigate.
