### ISSUE TITLE
Trying to add italics to an indented bullet list causes the line to be deleted

### ISSUE THREAD

**Issue by HoughIO** [careteditor/caret#183]
I ran into this when indenting a list, and adding italicized text.
The line just gets deleted from the editor.

Version number: 1.10.0

Repro steps:

* type some text here
    * _put some indented text, move to the right of the underline and press enter_

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.11.0 release.

Thanks for reporting.

**Comment by HoughIO** [comment]
No problem!
:feelsgood:
