### ISSUE TITLE
Keyboard shortcut for strike

### ISSUE THREAD

**Issue by nblackburn** [careteditor/caret#184]
Please add a keyboard shortcut for strike-though.

**Comment by borekb** [comment]
It could be approached like `<code>`: there is no shortcut for it but if you make a selection and press <code>`</code>, it does the right thing. I can imagine selecting text and pressing <code>~</code> working the same way.

**Comment by macosxguru** [comment]
I didn't know the <code> trick. I would imagine that it would be convenient to use the same technique for strikethrough and quoteblock.

That would make the process of writing convenient.

macosxguru

**Comment by borekb** [comment]
Yeah, it is one of the cute little features that I discovered kind of randomly but make a huge difference in the overall UX. ❤️ Caret!

**Comment by astoilkov** [comment]
We introduced strikethrough assistance in the latest version of Caret.
