### ISSUE TITLE
Fenced Code Block Creation

### ISSUE THREAD

**Issue by cebe** [careteditor/caret#188]
Hi, a small enhancement on Fenced Code Blocks:

If I am at the start of a line and want to create a fenced code block, the automatic completion could be enhanced a bit.

The current behavior is an auto addition of a second backtick after the first has been created. Also, when I add another backtick it will then create another closing backtick so I end up with four backticks in a line and the cursor in the middle of these.

A visualization (in `<>` is what I type afterwards how the line looks like `|` represents the cursor):
``````
<hit `>
`|`
<hit `>
``|``
``````

This is totally fine for inline code so I suggest the following enhancement should only be applied if the backticks are on the start of the line.

In the above situation, in order to get a fenced code block I have to type `<right><right><backspace>`.
Caret could enhance this by adding only one backtick and moving the cursor like this:

``````
<hit `>
`|` // could be that I want to create a normal inline code block here
<hit `>
```|  // pretty sure this is intended to be a fenced block now
``````

Its the little things like these that make an editor awesome, so I would appreciate it if it would be implemented. Thanks! :)

**Comment by astoilkov** [comment]
We have also been thinking in improving the experience of creating a fenced code block. Currently it seems to confusing.

P.S. Have you tried creating a fenced code block by hitting the backtick three times and then hitting Enter?

Thanks for reporting.

**Comment by borekb** [comment]
I use 3x backtick + Enter, it is quite convenient but agree that not very discoverable.

**Comment by cebe** [comment]
> I was wondering if you have tried creating a fenced code block by hitting the backtick three times and then hitting Enter.

I did not think of this, it works. However I usually add a language hint to the fenced code block so I wanted to add that first before writing the code. Otherwise that would work fine.

**Comment by astoilkov** [comment]
Adding a language hint to the fenced code block also works. It also gives you autocompletion for the supported languages.

Hitting backtick three times then starting to write will show you an autocompletion menu. Selecting an item from the autocompletion menu by hitting Enter autocompletes the entire fenced code.

**Comment by cebe** [comment]
Aha! I was too confused by the autocomplete for inline code block that I did not realise this would work as a fenced block too. This is actually better than what I suggested as it also works with fences that are longer than 3. This is more of a documentation issue then, there is nothing to be changed imo.

**Comment by astoilkov** [comment]
In the latest Caret release we changed how ` autocompletes. Now it works just like quotes autocompletion. We hope you like it.
