### ISSUE TITLE
Feature idea: jump to last edit location

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#189]
A great feature from some IDEs and editors that would also be useful in Caret is "jump to last edit location". 

Use case: I edit a paragraph and want to copy something from another part of the document. So I scroll down or up, copy the text and then I just invoke the "jump to last edit location" and am right back where I was. It's much more cumbersome without this feature.

Some editors even implement a stack of last edit locations but that's probably not necessary.

**Comment by astoilkov** [comment]
Do you have a specific shortcut you are familiar or used to?

**Comment by borekb** [comment]
I'm used to <kbd>Ctrl</kbd>+<kbd>Q</kbd> which probably comes from Eclipse, originally. IntelliJ IDEs use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Backspace</kbd> by default (which I find a bit cumbersome to be honest).

**Comment by EnCey** [comment]
+1

In the .NET world (with ReSharper), this is the `Ctrl`+`-` shortcut. 
In addition to edit locations it also remembers locations you jumped to via navigation commands (like `ctrl`+`g` in caret). 

When editing markdown documents, a simple "last edit location" would probably be enough though.

**Comment by borekb** [comment]
Whaat, this has shipped and I have missed it? Awesome!! ❤️

**Comment by astoilkov** [comment]
We actually didn't announce it because we haven't tested it yet. You could try it out and give us your feedback on how it is working for you.

**Comment by borekb** [comment]
When I invoke it from menu > Go > Last Edit Location, it works well. When I press Ctrl+Shift+backspace, it deletes the last word before my current cursor :) (behaves as if I just pressed Ctrl+backspace without Shift).

**Comment by astoilkov** [comment]
We will look at this. Thanks.

**Comment by borekb** [comment]
^^ FYI, still the same keyboard shortcut bug in 1.15.1.

**Comment by astoilkov** [comment]
This is now available in Caret 2.0 release and the shortcut bug should also be resolved. If you have issues with the functionality do not hesitate to open a new issue.

Closing this issue.
