### ISSUE TITLE
Autocompleted Nested List Don't Work

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#191]
I noticed this in the recent 1.11 update where when I create a list and then a nested list, it no longer auto completes the list creation. So for example if I write a list:
- Level 1
    - Level 2a

After Level 2a, when I press ENTER, I expect the next nested list item to be auto created:
- Level 1
    - Level 2a
    -

But instead no list item is created, although it is indented properly, it's just the dash that is missing.

**Comment by astoilkov** [comment]
This is now fixed and the fix will be included in the next Caret release.

Thanks for reporting.

**Comment by astoilkov** [comment]
The new release is now available.

Closing this.
