### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by szepeviktor** [careteditor/caret#195]
Please consider including the changelog in GitHub release notes where :tada: lives.

**Comment by erusev** [comment]
Should it be the same as the one at the website? Thanks

**Comment by szepeviktor** [comment]
Thank you. 

I have no specific wish.
Even a single link to the website is enough. 


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by szepeviktor** [comment]
> Even a single link to the website is enough.

It may not be sufficient as Release notes on the website only show MAJOR.MINOR relases.
PATCH releases are not listed.

**Comment by szepeviktor** [comment]
@erusev A Release checklist always comes handy!

**Comment by sguergachi** [comment]
I think a good solution to this would be to have the about page link to the release notes page on the website
![image](https://cloud.githubusercontent.com/assets/615386/21468568/cf361812-c9e6-11e6-8156-2178e35384b4.png)

So clicking on the version number could be a hyperlink to the page.

**Comment by szepeviktor** [comment]
@erusev Please consider adding some more release notes
https://github.com/careteditor/caret/releases/tag/1.12.0
Thanks.

**Comment by sguergachi** [comment]
There are already nicely formatted release notes here: https://caret.io/releases

**Comment by szepeviktor** [comment]
Thank you.
Please see https://github.com/careteditor/caret/issues/195#issuecomment-267841529



> It may not be sufficient as Release notes on the website only show MAJOR.MINOR relases.
> PATCH releases are not listed.

**Comment by szepeviktor** [comment]
In case of a minor release a simple link to the website would be enogh.

**Comment by szepeviktor** [comment]
Of course you may close this one as `wontfix`

**Comment by szepeviktor** [comment]
Could you please add some notes to GitHub releases for patch releases?

**Comment by astoilkov** [comment]
@szepeviktor We will experiment with adding some release notes to the patch releases. Thanks.

**Comment by szepeviktor** [comment]
Thank you for your effort.

**Comment by borekb** [comment]
I'd suggest using GitHub milestones, it works pretty well for assigning issues to product releases.
