### ISSUE TITLE
Shift + Insert, Ctrl + Insert

### ISSUE THREAD

**Issue by szepeviktor** [careteditor/caret#196]
I do not know Linux and Mac GUI-s, but on Windows it would be nice to support

- <kbd>Shift + Insert</kbd> - Paste
- <kbd>Ctrl + Insert</kbd> - Copy

**Comment by astoilkov** [comment]
asidf

**Comment by astoilkov** [comment]
Hi @szepeviktor,

I just tried using <kbd>Ctrl + Insert</kbd> and <kbd>Ctrl + Delete</kbd> under Windows but I wasn't able to find an app where those shortcuts would perform the action you specified. Am I doing something wrong?

Thanks.

**Comment by szepeviktor** [comment]
1. Open default notepad.exe on Windows
1. Type in a word, e.g. `caret`
1. Select the word
1. Press <kbd>Ctrl + Delete</kbd>
1. Go to a new line
1. Press <kbd>Ctrl + Insert</kbd>
1. Now you have two of the same word

**Comment by szepeviktor** [comment]
One more:
- <kbd>Shift + Delete</kbd> - Cut

**Comment by szepeviktor** [comment]
@astoilkov Could you add this feature?

**Comment by astoilkov** [comment]
This will be available in the next Caret release. I will notify you when this happens.

**Comment by astoilkov** [comment]
This is now implemented in Caret 2.0.6.

Closing this issue. Thanks for the suggestion.
