### ISSUE TITLE
Ordered list

### ISSUE THREAD

**Issue by szepeviktor** [careteditor/caret#198]
Please consider and an option to restore the original ordered list numbering.

```
1.
1.
1.
```

**Comment by erusev** [comment]
Could you share a specific use case for this? Thanks

**Comment by szepeviktor** [comment]
If you make up a list then delete some items you end up with

```
1. First
4. Fourth
```

And I'm used to having only 1-s in an ordered list.

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by astoilkov** [comment]
Hi @szepeviktor,

In Caret deleting items in the middle of a list auto fixes the numbering. Isn't this more convenient?

**Comment by szepeviktor** [comment]
Thank you for your answer.

I was noticing it by using the <kbd>Delete</kbd> key

![ordered-delete](https://cloud.githubusercontent.com/assets/952007/21316954/5a665240-c603-11e6-8ee9-ed850c78013e.png)

After tpying a character the list gets updated.

**Comment by szepeviktor** [comment]
If possible please add an option to use always `1`-s

**Comment by szepeviktor** [comment]
**off** See the recommended editor: https://github.com/szepeviktor/wordpress-speedtest#provider-top-list

**Comment by borekb** [comment]
I've seen some Markdown "style guides" that recommend 1., 1., 1. but I think that:

1. It goes against the core values of Markdown (make text legible for humans yet easily parsable by machines; humans would never write all-ones as ordered list items).
2. The rule in the style guide is only because of dumb editors. Caret is very smart and I think renumbering is a much better approach.

**Comment by szepeviktor** [comment]
> humans would never write all-ones as ordered list items

I know one human who likes to calm waters of 1., 1., 1. @szepeviktor

**Comment by astoilkov** [comment]
We made an improvement in Caret 2.0.6 where lists that contain only 1. will not be auto incremented. If you write 1. on the first line and then change the 2. to 1. on the second line the lists will be autocompleted to 1. I hope people like this solution.

I am closing this issue. If you have any discussions or ideas for improvement don't hesitate to write back so we could reopen the issue.

**Comment by szepeviktor** [comment]
> I hope people like this solution.

Yes *they* so.
