### ISSUE TITLE
Spacing Between Edit and Preview pane is massive

### ISSUE THREAD

**Issue by tutelagesystems** [careteditor/caret#200]
I downloaded the latest release (1.11.3) and now there is a big space between the **editing pane** and the **preview pane**.

The bigger the window, the bigger the space. I have included a screen shot to show the issue (red lines are borders for editing and preview pane).

![image](https://cloud.githubusercontent.com/assets/811123/21294355/7ea305c8-c508-11e6-9dc1-17b0cd8ec31c.png)

**Comment by erusev** [comment]
We'll release an update that fixes that in the next couple of days.

Thanks for reporting!

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.12.0 release.

Closing this. Thanks for reporting.
