### ISSUE TITLE
Inconsistent Dark mode option

### ISSUE THREAD

**Issue by szepeviktor** [careteditor/caret#201]
Please see this state:

![dark-not-dark](https://cloud.githubusercontent.com/assets/952007/21296117/145dd2e0-c564-11e6-8726-3f67b693f12f.png)

I am switching modes by the menu then by the shortcut key.
Sometime it gives the result above.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.13.0 release.

Closing this issue. Thanks for reporting.
