### ISSUE TITLE
GFM does not join consecutive lines

### ISSUE THREAD

**Issue by szepeviktor** [careteditor/caret#202]
Originally

```
some
text
```

outputs `some text`

in GFM

```
some
text
```

What is your opinion?

**Comment by borekb** [comment]
I think Caret implements Markdown as rendered in `*.md` files on GitHub (e.g., READMEs), not in issues and pull requests. Which is a strange mix of Markdown, _some_ GFM enhancements but not all. This is how it is even on GitHub (quite a mess).

With that being said, it would be nice to have switchable MD engines. On the other hand, they are working on a WYSIWYG mode which needs to be two-way (common AST in the middle), which would make swappable MD implementations really hard to do.

**Comment by szepeviktor** [comment]
Thank you.

Appending whitespaces is a strange thing for me. Could be I am used to commenting.

**Comment by szepeviktor** [comment]
> even on GitHub (quite a mess).
> 
> With that being said, it would be nice to have switchable MD engines. On the other hand, they are working

I see you automatically pres <kbd>Enter</kbd> twice.

**Comment by szepeviktor** [comment]
> Which is a strange mix of Markdown, some GFM enhancements but not all.

For example GitLab keeps the consecutive line joining feature in comments which is not something I like.

**Comment by borekb** [comment]
Yeah, the darker corners of Markdown. I can't even find the "specification" of line break behavior on GitHub now; don't see it on [this page about GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) or anywhere else. I'm pretty sure I've seen it somewhere in the past, maybe they're silently deprecating it?

**Comment by erusev** [comment]
Caret tries to comply as of with CommonMark, which is pretty much the only Markdown specification that exists.
