### ISSUE TITLE
Save warning in case of a second window

### ISSUE THREAD

**Issue by szepeviktor** [careteditor/caret#203]
1. Open Caret
1. Enter some Markdown
1. Exit by pressing Alt+F4 (Windows) **OR** File / Exit

No save dialog will pop up.

**Comment by borekb** [comment]
Which is an excellent feature :) It's called hot exit and most good editors have it nowadays.

**Comment by szepeviktor** [comment]
Really.

**Comment by szepeviktor** [comment]
How come that I've seen a Save/Don't save dialog on exit?

**Comment by szepeviktor** [comment]
Got it. A second window!

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.13.0 release.

Closing this issue. Thanks for reporting.
