### ISSUE TITLE
Rendering artifact

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#205]
Sometimes (not always), there is this rendering artifact visible close to the right area of the editor:

![image](https://cloud.githubusercontent.com/assets/101152/21385646/9ed6915c-c76f-11e6-8577-fbbf4d1c8df6.png)

This is with preview hidden.

**Comment by astoilkov** [comment]
We are aware of the issue but still can't pinpoint what is causing it. We are certain that it is a Chrome bug but don't know how to isolate it in order to report them this issue.

I will investigate further when I have the time and write back in this thread.

**Comment by astoilkov** [comment]
I have tried to switch to the previous version of Chrome and this fixes the issue. We will wait for the next release of Chrome and hopefully that resolves the problem. If not we will try to isolate the issue and report it.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.14.0 release.

Closing this issue.
