### ISSUE TITLE
Doubleclick word selection

### ISSUE THREAD

**Issue by szepeviktor** [careteditor/caret#207]
(at least in Windows) doubleclicking a word selects it.

While in Windows dragging the selection selects neighbor words fully, in Caret it switches back to character selection.

Please consider implementing full-word selection on doubleclick+drag.
Thanks.

**Comment by bdnk** [comment]
Same goes for tripleclicking to grab the whole line. Tripleclick+drag should select multiple full lines, instead of switching back to character-by-character selection.

**Comment by pslobo** [comment]
This is probably a Windows/Linux only thing because this behaviour doesn't work on MacOS (in any app I've tried so far.

**Comment by bdnk** [comment]
I use this behaviour pretty consistently across MacOS, in just about any
application that edits text, which is why it was so jarring for it not to
work in this context.

**Comment by pslobo** [comment]
Aha, figured out why I've never come across this in other apps before. I'm one of those crazy tap to click guys so when using the trackpad and tap to click, double tap + hold + drag only starts selection from cursor location, whereas double click + drag select does indeed select the entire word first.

**Comment by astoilkov** [comment]
We have implemented this behavior in the latest Caret version.

Closing this issue.

**Comment by szepeviktor** [comment]
Thank you.
