### ISSUE TITLE
Double scroll bar when in Typerwritter mode

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#208]
In typewriter mode, when in full screen I see 2 scroll bars using latest version.
![image](https://cloud.githubusercontent.com/assets/615386/21468536/2da380f4-c9e4-11e6-8aea-fecc5a152af0.png)

**Comment by astoilkov** [comment]
Do you have your Windows set on 150% scaling?

**Comment by sguergachi** [comment]
No 100%

**Comment by astoilkov** [comment]
This is now resolved in the latest Caret 1.12.1 release.

Closing this issue. Thanks for reporting.
