### ISSUE TITLE
Table with alignment formatting not recognized

### ISSUE THREAD

**Issue by EnCey** [careteditor/caret#210]
First off, the table editor is amazing!

However it doesn't seem to work with alignment rules:

```
| a      | b      | c      |
| :----- | :----: | -----: |
| test 1 | test 2 | test 3 |
| test   | 4      |        | 
```

When I work with this table, it doesn't auto resize columns anymore  and the tab navigation is lost as well 😞

**Comment by astoilkov** [comment]
We implemented support for table alignments. It is available in the latest Caret 1.13.2 release.

Closing this issue.
