### ISSUE TITLE
Links to headings don't work with links to local files

### ISSUE THREAD

**Issue by EnCey** [careteditor/caret#211]
**Update:** see my second comment for the cause of this bug.

-----

For long documents, it would be handy if we could link to a section heading:

```
# Some heading
...

# Other Stuff
See [the other chapter](#some-heading)
```

Anchors could be automatically generated from the name of the heading, or there is a way to explicitly create them like in [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#spe-attr).

What would be _even more awesome_ is if this would work across documents:

```
See [here](other.md#chapter3).
```

**Comment by astoilkov** [comment]
Hi @EnCey,

Linking headings like you showed in the first example is already available. You could write a long document and put `# Heading` in the beginning and `[Heading](#heading)` link in the end and try clicking on the link in the preview. The preview should jump to the `# Heading` line.

**Comment by EnCey** [comment]
Hmm doesn't work in my document, I tried it multiple times now even with a simple `# Heading` (no spaces etc.)

When I click the link in the preview, a Windows Explorer window opens with the directory my note is in.  
I have version 1.12.1 of Caret.

**Comment by EnCey** [comment]
I think I figured it out: when I create a new document I can link to headings and it works in the preview.

However, once I include a link to a different file (example: `link to [index](#index.md)`), the heading link stops working and opens a directory window instead. 
Interestingly, the document remains "broken" even when I remove all links to files.

**Comment by astoilkov** [comment]
We successfully replicated the problem. The fix is available in the latest version of Caret.

Closing this. Thanks for reporting.

**Comment by EnCey** [comment]
Awesome! Just tested it, works like a charm.
