### ISSUE TITLE
Abbreviations ending with a dot spell checked incorrectly

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#212]
For example, `apod.` in the Czech language is a common abbreviation and it even appears in the dictionary Caret uses, however, it still marks this in text as incorrect:

![image](https://cloud.githubusercontent.com/assets/101152/21583351/4a9a416c-d07d-11e6-8c64-c08a0bea7307.png)

**Comment by astoilkov** [comment]
This is now fixed in Caret 4.0 Beta.

Closing this issue.
