### ISSUE TITLE
Largest font too small

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#213]
Sorry to bother you with this again (like for the fifth time I think) but Caret 1.12.1 on my 13'' notebook with 125% DPI renders the largest font too small. It's sort of the same size as 11-12pt in MS Word which is bearable but if I could, I'd make the font larger. Again, to be sure, this is the _largest_ option in Caret.

**Comment by astoilkov** [comment]
We hope the new preferences suits you well for this scenario.

Closing this issue.

**Comment by borekb** [comment]
Not only preferences but Ctrl+= now also scales indefinitely, cool!

BTW, in the preferences, there's also `lineWidth` which I appreciated. Almost wanted to report that 72 is too narrow for me but then I thought, I cannot bother these guys with every detail 🙂 .

**Comment by astoilkov** [comment]
Happy to hear you like it and don't hesitate to bother us - this way we make the product better.
