### ISSUE TITLE
Cursor / Caret is in the wrong place

### ISSUE THREAD

**Issue by EnCey** [careteditor/caret#214]
This is a very annoying bug, as seen in the gif:

![Problem in action](https://cloud.githubusercontent.com/assets/1894528/21589789/b735a0aa-d0f5-11e6-8f3b-41120bfba7c7.gif)

I _think_ this is caused by the link to a local file, at least I managed to reproduce the problem with one of those in my document.

**Steps to reproduce**

1. write some text and a link to a local file
2. save the document
3. close caret & re-open it 
4. when navigating _behind_ the link for the first time, the cursor starts acting weird
5. cursor is also incorrect in the rest of the document afterwards

I'm using Caret v1.12.1 on Windows.

I also reported a different issue related to links to local files: #211  
It's about links to headings/anchors not working when you have a link to a local file in your document.

**Comment by astoilkov** [comment]
This is now resolved in the latest Caret release.

Closing this. Thanks for reporting.
