### ISSUE TITLE
Keyboard shortcuts cheatsheet

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#215]
It would be nice to have a full reference of all the cool shortcuts Caret provides. https://caret.io/features is currently the closest but not comprehensive.

**Comment by macosxguru** [comment]
This might help.  
[A List of Keyboard Commands for Caret - iPadpedia](http://ipadpedia.net/caret_keyboard_commands)

[Adding to the Built-in Keyboard Commands of Caret - iPadpedia](http://ipadpedia.net/adding_to_the_built-in_keyboard_commands_of_caret)

macosxguru

**Comment by macosxguru** [comment]
http://ipadpedia.net/caret_keyboard_commands has been updated for version 1.13.1

**Comment by astoilkov** [comment]
We have implemented Command Palette <kbd>Cmd/Ctrl</kbd> <kbd>Shift</kbd> <kbd>P</kbd> which includes available application commands. We hope you like it.

I think we can close this issue. If someone disagrees we can reopen it.
