### ISSUE TITLE
Ctrl+click on some links doesn't work

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#216]
Example:

```
[test](http://example.com)
http://example.com
```

1. Ctrl+clicking on "`test`" works.
2. Ctrl+clicking on "`http://example.com`" either on the first line or the second line doesn't work, it just brings Windows Explorer to foreground.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.13.0 release.

Closing this issue. Thanks for Borek.
