### ISSUE TITLE
Keyboard shortcuts for ordered & unordered lists

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#217]
The idea comes from OneNote. If I have lines like:

```
line 1
line 2
line 3
```

I can select them (even "lazily", meaning that the selection can start in the middle of line 1 and end anywhere on line 3) and press:

- <kbd>Ctrl</kbd>+<kbd>.</kbd> to get unordered list
- <kbd>Ctrl</kbd>+<kbd>-</kbd> to get ordered list

The result is:

```
- line 1
- line 2
- line 3
```

or

```
1. line 1
2. line 2
3. line 3
```

Pressing the shortcut again converts it back to plain lines.

**Comment by astoilkov** [comment]
This is now possible with Caret 2.0 Keyboard Shortcuts functionality.
