### ISSUE TITLE
Table editing bug

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#220]
![caret-table-editing](https://cloud.githubusercontent.com/assets/101152/22000787/784144a6-dc41-11e6-95e8-4a73d97ceda0.gif)

Can be reproduced on this table:

```
| Col1 | Col2 | Col3 | Col4 |
| ---- | ---- | ---- | ---- |
| text | text | text |      |
| text | text | text | w    |
| text | text | text |      |
| text | text | text |      |
```

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.13.0 release.

Thanks for reporting.
