### ISSUE TITLE
Nested list issues

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#221]
![image](https://cloud.githubusercontent.com/assets/101152/22001262/1613a884-dc44-11e6-9096-0344bd032737.png)

1. Nested table is not syntax highlighted and supported as a table.
2. The nested list is detected as a `<pre>` element.
3. The table is rendered incorrectly.

Test text:

```md
Paragraph before a list.

- List item 1.
- List item 2 with multiple block elements inside the `<li>`. For example, this table:
    
    | Col1    | Col2 |
    | ---------- | ---------- |
    | Hello  | Caret |
    
    - This is a nested `<li>`
    - And another one.

Paragraph after the list.
```

**Comment by astoilkov** [comment]
These issues are now fixed in the [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue.
