### ISSUE TITLE
Drag and drop on Windows still uses backward slashes

### ISSUE THREAD

**Issue by purelygrey** [careteditor/caret#222]
Dropping an image from a folder results in this:

![image](https://cloud.githubusercontent.com/assets/16882824/22018453/f8fb08a6-dcbf-11e6-9a64-cda336d6363c.png)

Slashes need to be replaced manually in order for preview to work.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.13.0 release.

Closing this issue. Thanks for reporting.
