### ISSUE TITLE
Anxious :)

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#223]
Guys, you have to stop announcing releases before they are available, the waiting is killing me :)

![image](https://cloud.githubusercontent.com/assets/101152/22065652/89a65454-dd89-11e6-9504-d5d3b1ad6b33.png)

![image](https://cloud.githubusercontent.com/assets/101152/22065670/9228ac30-dd89-11e6-87fb-b07796559908.png)

![image](https://cloud.githubusercontent.com/assets/101152/22065686/a7f34610-dd89-11e6-9e99-0bc1228ed1b2.png)

❤️

**Comment by astoilkov** [comment]
Ha ha. Sorry Borek. In order for GitHub releases page to detect the newly uploaded files as the latest release there should be at least one commit between the old and the new release.

We have automated process that creates a commit in this repo before we start uploading. This means we can't do much to stop the torturing. 😄 

The good news is that the release is now available.
