### ISSUE TITLE
Ctrl+comma doesn't work on Windows

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#224]
Looks like the keyboard shortcut is registered incorrectly:

![image](https://cloud.githubusercontent.com/assets/101152/22069711/b5900f82-dd99-11e6-9654-205ddd9853b9.png)

**Comment by astoilkov** [comment]
Ooops. Sorry. Will be fixed in the next release.

**Comment by astoilkov** [comment]
This is now fixed in the 1.13.1 release.
