### ISSUE TITLE
[Bug] Youtube embed hijacks keyboard events

### ISSUE THREAD

**Issue by Swader** [careteditor/caret#225]
If your embed a Youtube video in a post, and launch it in preview to look it over by clicking the play button with the mouse, you will be unable to type anything in the editor pane until you click out of the embed in the preview pane, and into the previewed text.

**Comment by astoilkov** [comment]
Hi Bruno,

This bug is now fixed in the latest Caret 1.13.2 version.

Closing this issue. Thanks for reporting.
