### ISSUE TITLE
Typing lag

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#226]
Since 1.13, there is a noticeable lag when typing, I'd guess around 100ms. Bearable but not pleasant and I think this is new in 1.13.

**Comment by borekb** [comment]
Caret actually misses some key-presses which is worse than just a lag. It's like the FPS of the application is too low and it's not able to process all my inputs correctly.

**Comment by astoilkov** [comment]
Does this happen on files under Git or on all files?

**Comment by borekb** [comment]
I'm observing this on a file not under Git. Will try to find out more about this.

**Comment by astoilkov** [comment]
@borekb We have made some improvements to the typing performance. Could you try the new 1.13.3 update and let us know if you see any difference?

**Comment by borekb** [comment]
Seems to be a bit better, will report as I have more experience with 1.13.3.

**Comment by astoilkov** [comment]
Great. Thanks.

P.S. When we measure the typing performance of 1.13.3 compared to 1.12.0 the new version beats the old one.

**Comment by astoilkov** [comment]
@borekb We caught one more issue. We are pretty sure it's the main reason for the lag so expect even bigger improvement with next release.

**Comment by astoilkov** [comment]
Typing lag should be entirely fixed in the latest Caret 1.13.4 release.

**Comment by borekb** [comment]
Yes it looks good, thank you!
