### ISSUE TITLE
version 1.13.2 need to install git ?

### ISSUE THREAD

**Issue by VF128S** [careteditor/caret#227]
why the new version always ask me to install git?

![screen shot 2017-01-22 at 6 25 11 pm](https://cloud.githubusercontent.com/assets/10346089/22181856/5164b5f0-e0d0-11e6-8063-e8c9f0238f13.png)

**Comment by astoilkov** [comment]
This seems to be a bug. We will start investigating immediately.

Sorry for the inconvenience and thanks for reporting.

**Comment by erusev** [comment]
@VF128S Do you have git installed on your machine? Thanks

**Comment by astoilkov** [comment]
@VF128S We have released a new Caret 1.13.3 version where the issue should be fixed. Could verify that?

**Comment by VF128S** [comment]
bug fixed version 1.13.4
thank for your work

**Comment by astoilkov** [comment]
Great to hear! Closing this issue.
