### ISSUE TITLE
Enable accents

### ISSUE THREAD

**Issue by tulu** [careteditor/caret#23]
Hello, when I try to write in Spanish with accents even though I type them the text doesn't show them. This is an example:

Revisión

<img width="372" alt="screen shot 2015-11-30 at 16 04 35" src="https://cloud.githubusercontent.com/assets/377411/11481404/19fa933a-977c-11e5-85f9-015f5f7b5daa.png">

**Comment by erusev** [comment]
Does this affect all fonts? Font settings are accessible from the Preferences menu.

**Comment by tulu** [comment]
It doesn't work with any font. If I copy and paste from Sublime Text for example it works.
Maybe it's the combination of keys to add the accents. I use option + e for ´ and option + n for ˜

**Comment by erusev** [comment]
Thanks, we'll see what we can do.

**Comment by hkdobrev** [comment]
Mac OS also supports holding a letter to trigger an accent popover to choose from. It works only in some apps, it would be great to work in Caret as well.

To be clear on what I'm referring to, have a look at ["Accented characters"](https://support.apple.com/en-us/HT201586).

**Comment by tulu** [comment]
That option works for me in Caret. Not used to it but works for now.

**Comment by hkdobrev** [comment]
@tulu Strange, it doesn't work for me in Caret.

**Comment by tulu** [comment]
@hkdobrev I have version 0.4.4 on a MacBook Pro with El Capitan

<img width="517" alt="screen shot 2015-12-01 at 08 55 19" src="https://cloud.githubusercontent.com/assets/377411/11500041/57a61564-9809-11e5-8e16-dd0cd7a92843.png">

**Comment by hkdobrev** [comment]
@tulu Hmm, it turned I had this disabled. I think this is the official way of writing accents on Mac OS The <kbd>Option</kbd> + <kbd>&lt;key&gt;</kbd> thing allows you type a lot more non-ASCII characters, but it's not just for accents.

For reference you can disable the accents popover with:
```
defaults write -g ApplePressAndHoldEnabled -bool false
```

**Comment by tulu** [comment]
@hkdobrev thanks! Although I write faster with <kbd>Option</kbd> + <kbd>&lt;key&gt;</kbd> :)

**Comment by astoilkov** [comment]
We added support for accents.

You should get an in-app update notification some time next week.

Thanks a lot for reporting this :)

**Comment by erusev** [comment]
@tulu This is a bit off-topic, but I noticed that you've used "Roboto Mono" on the first screenshot and "Menlo" on the second and I was wondering about whether you liked one of the fonts better than the other.

**Comment by tulu** [comment]
@erusev I think I've changed it for the accent testing. I prefer Menlo, really nice :smile:

**Comment by erusev** [comment]
@tulu Thanks, good to know :)
