### ISSUE TITLE
Higher scroll speed in preview window for large documents

### ISSUE THREAD

**Issue by EnCey** [careteditor/caret#230]
When jumping to headings with `Ctrl+G` in larger documents (5000+ lines), it takes a couple of seconds for the preview window to "catch up" as it scrolls to that position, while the editor jumps there instantly.

My understanding is that the scroll animation is intended to give a sense of direction when jumping to a position, however it is not very helpful when it needs to cover such large distances (it's actually kind of  distracting / an unnecessarily delay as you can't start reading right away).

Would it be possible to speed the animation up the further away the target?  
Or instantly jump there instead of scrolling for large distances?

**Comment by astoilkov** [comment]
We introduced both approaches that you proposed. We set the animation speed to always be the same and we made instant jumping for really long scroll animations.

You could try it out and let us know what you think.

**Comment by EnCey** [comment]
Just tried it in my large document, works perfectly! 
Great job guys, I'm amazed with the speed at which you address issues 😃

**Comment by astoilkov** [comment]
Great to hear and thanks for the compliment! We are doing our best to build the best Markdown Editor.

Closing this issue than.
