### ISSUE TITLE
Git indicators incorrect

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#231]
I've got a file with four added lines, this is the correct indication in VS Code:

![image](https://cloud.githubusercontent.com/assets/101152/22407686/aac7ee82-e66b-11e6-9216-975e24ebc7fe.png)

Same in Caret 1.13.4:

![image](https://cloud.githubusercontent.com/assets/101152/22407688/b3bb9534-e66b-11e6-9b49-cafd99de5a14.png)

**Comment by astoilkov** [comment]
@borekb Can you replicate the behavior with every file? I can't seem to successfully replicate it when testing. Is it possible to share the problematic file by email?

Thanks in advance.

**Comment by borekb** [comment]
Did some playing around and I can reproduce it on **every MD file that is _not_ directly in repo root**.

- `<repo-root>/README.md` works fine
- `<repo-root>/subfolder/PROBLEM.md` is problematic

**Comment by astoilkov** [comment]
We caught the problem and fixed it in the latest version of Caret. Could you test it and verify everything is working correctly?

**Comment by borekb** [comment]
👍 Works nicely and the Git indicators are also much nicer.

**Comment by astoilkov** [comment]
Great to hear. Closing the issue.
