### ISSUE TITLE
Word marked as misspelled when it isn't

### ISSUE THREAD

**Issue by Swader** [careteditor/caret#234]
<img width="627" alt="screenshot 2017-01-30 13 13 42" src="https://cloud.githubusercontent.com/assets/1430603/22422751/5cc8cb38-e6ee-11e6-8581-c201b785f1e0.png">

Context: http://grammarist.com/spelling/recognize-vs-recognise/

**Comment by Swader** [comment]
Note that the system language is set to US English, and that checker does NOT mark the word as invalid - so the problem is with Caret and its own implementation of a dictionary perhaps?

**Comment by astoilkov** [comment]
@Swader Is it possible for you to send us the problematic file via email so we can replicate the correct problem on our side?

**Comment by Swader** [comment]
I can no longer reproduce this, it stopped reporting it as invalid. I'll re-open the ticket if it happens again and I can reliable reproduce.
