### ISSUE TITLE
Table rendering issue during page break

### ISSUE THREAD

**Issue by chirsch** [careteditor/caret#235]
When a PDF is generated and a page break happens within a table, the result is a strange double render of the table on the following page. Looks like the headers are re-rendered on top of next row in the table. I can confirm this happens in my modified theme, the Github theme, and the standard Caret theme.

## Preview in Caret *(disregard redacted)*
![caret preview of page break issue](https://cloud.githubusercontent.com/assets/6108606/22667305/3989638e-ec8a-11e6-9913-d7acb1e5f580.png)

## PDF output
![PDF output of page break issue](https://cloud.githubusercontent.com/assets/6108606/22667383/8585f068-ec8a-11e6-8683-5fad21ddb0b0.png)

Let me know if you need any further information or reference.

**Comment by astoilkov** [comment]
Thanks for reporting. This was actually a long lasting bug in Chromium which got resolved in the last few days. We created a release today so you could see the bug fixed in the latest Caret 1.14.0 release.

Closing this issue. Thanks for reporting.
