### ISSUE TITLE
Emoji bug

### ISSUE THREAD

**Issue by ihackalot** [careteditor/caret#238]
When adding an emoji by hitting `⌘ + ⌃ + space`, as soon as you hit any key to add characters or punctuation, the emoji gets deleted. To work around this you can move around with arrow keys before you add new key stroke.

**Comment by astoilkov** [comment]
We resolved the issue. The fix will be included in the next release of Caret. I will write in this thread when an update is officially available.

Thanks for reporting.

**Comment by astoilkov** [comment]
We released Caret 1.14.1 where the fix for this issue is included.

Closing this issue.
