### ISSUE TITLE
Stopped working on fedora 25

### ISSUE THREAD

**Issue by paddycarver** [careteditor/caret#239]
I installed through the RPM file in your downloads, and this is what I see when I open a Markdown file:

![screenshot from 2017-02-09 21-27-25](https://cloud.githubusercontent.com/assets/59249/22815218/d2c2e864-ef0e-11e6-9741-5b254fb2b053.png)

I've tried 1.14.0 and 1.13.4 with the same result.

**Comment by paddyforan** [comment]
(To be clear, that text is highlighted using the mouse--it's unreadable before I do that.)

**Comment by astoilkov** [comment]
Hi @paddyforan 

Did this happen after an update? Can you check what is the last version of Caret that works on your system.

Thanks in advance.

**Comment by astoilkov** [comment]
@paddyforan Did the app starting working for you?

**Comment by astoilkov** [comment]
Closing this issue. Hope everything works correctly. If you have issues please do not hesitate to create a new issue or post in this one.

**Comment by paddycarver** [comment]
Sorry for never updating this and answering your question, everything got busy. :(

Things worked again when I entirely uninstalled Caret and reinstalled it. If I had to guess, there was/is(?) a bug in the upgrade-in-place code somewhere, or something. But I have a workaround, so this hasn't been a huge deal.

Sorry again for the late response! Feel free to leave this closed, as I have a workaround.
