### ISSUE TITLE
Cursor offset in bold text with custom font

### ISSUE THREAD

**Issue by hkdobrev** [careteditor/caret#246]
I've made use of the custom font functionality in the preferences and started using the Source Sans Pro font. However, shortly after I've observed some problems with the cursor.

1. Configure Caret to use "Source Sans Pro" font.
2. Type out a title like:

  ```md
  ## The quick brown fox jumped over the lazy dog
  ```

  (the longer the sentence, the more visible the defect)

3. When the cursor is along the end of the line you'll see it has a quite visible visual offset from where you are actually typing. Typing is normal, but the cursor is over the previous letters.

This is not reproducible with the default font.

Screenshot:

![screen shot 2017-02-23 at 00 41 02](https://cloud.githubusercontent.com/assets/506129/23236165/cb1e329c-f960-11e6-8d1b-85f2ad05aeea.png)

The current caret position here is after the last letter, but the cursor is over the letter before the last.

**Comment by erusev** [comment]
This is something we've been working on this issue for a while now - we should release an update that fixes it in March.

Thanks for reporting.

**Comment by arda-** [comment]
I've noticed that this error happens with any font that isn't monospace.

**Comment by erusev** [comment]
This is fixed in the latest release.
