### ISSUE TITLE
macOS Sierra: fullscreen mode window closer error

### ISSUE THREAD

**Issue by arda-** [careteditor/caret#247]
Closing a window from fullscreen mode will create an 'empty'/ black space. They cannot be closed without quitting the app.

macOS Sierra, 10.12.3

![screen shot 2017-02-26 at 9 11 44 pm](https://cloud.githubusercontent.com/assets/9686548/23349521/dcca8454-fc68-11e6-990e-08200f53ff86.png)

**Comment by astoilkov** [comment]
This is now fixed in the latest version of Caret 1.14.3.

Closing this issue. Thanks for reporting.
