### ISSUE TITLE
enhancement: make bold text bold, for supported fonts

### ISSUE THREAD

**Issue by arda-** [careteditor/caret#248]
Currently, unclosing text in ** for bold only results in a color change. 

I understand if this was an opinionated UI choice, but I'd appreciate an option to make the text render bold.

![screen shot 2017-02-26 at 9 17 51 pm](https://cloud.githubusercontent.com/assets/9686548/23349557/1dacd3e6-fc69-11e6-8e4e-f32ad1a1f4b0.png)

**Comment by erusev** [comment]
Sure, makes sense.

**Comment by astoilkov** [comment]
The bold Markdown in Caret is now bold. We have made that change a long time ago but just noticed that this issue was still open.

I am closing this issue. Thanks for reporting this.
