### ISSUE TITLE
Cannot Open Non-Markdown File Extensions

### ISSUE THREAD

**Issue by theideasmith** [careteditor/caret#25]
I tried opening a non-markdown file, that is markdown format but not given correct extension (it had a blank extension). 

The following error has occurred:
```
{
    "message": "Uncaught TypeError: Cannot read property '0' of null",
    "line": 5,
    "column": 2571,
    "version": "0.4.4",
    "platform": "darwin",
    "os": "15.0.0",
    "path": "/Applications/Caret.app/Contents/Resources/app.asar/packages/FileManager/FolderView.js",
    "stack": [
        "at View.caret.inherit._select (/Applications/Caret.app/Contents/Resources/app.asar/packages/FileManager/FolderView.js:5:2571)",
        "at loopEvents (/Applications/Caret.app/Contents/Resources/app.asar/web/Events.js:5:229)",
        "at Object.Events.trigger (/Applications/Caret.app/Contents/Resources/app.asar/web/Events.js:5:527)",
        "at Object.List._selectItem (/Applications/Caret.app/Contents/Resources/app.asar/web/List.js:5:1952)",
        "at Object.List._handleKeydown (/Applications/Caret.app/Contents/Resources/app.asar/web/List.js:5:2754)"
    ]
}
```

**Comment by astoilkov** [comment]
Fixed.

You should get an in-app update notification some time next week.

Thanks a lot for reporting this :)

**Comment by theideasmith** [comment]
BTW do you guys intend for the code for this to be open source? Because one can just extract the app.asar and unobfuscate all the code.

**Comment by erusev** [comment]
We might open-source parts of the code in future, but we have no specific plans for it. 

One could, indeed, extract the asar files, but it would be illegal for one to copy and / or modify and / or distribute these files or their contents.
