### ISSUE TITLE
Incorrect preview of quote inside a list item

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#250]
Repro:

```md
1. First item
    > Nested quote
2. Second item
3. This is broken
```

Renders as:

![image](https://cloud.githubusercontent.com/assets/101152/23412614/609219e6-fdd6-11e6-95a5-51d67c791d6c.png)

Should render as:

![image](https://cloud.githubusercontent.com/assets/101152/23412744/de25e892-fdd6-11e6-875d-19847d24bef1.png)

**Comment by borekb** [comment]
It's also not syntax-highlighted correctly.

**Comment by astoilkov** [comment]
This is now fixed.

Closing this issue.
