### ISSUE TITLE
'Delete Line' command / shortcut

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#254]
I use this frequently in advanced code editors and IDEs, and somewhat miss it in Caret. The advantage is that one does not need to carefully select the line, the cursor can be anywhere on it and `Ctrl+D` (my preferred shortcut) removes it. It usually also works with "lazy selection" over multiple lines: whichever lines are affected by the selection, even partially, are removed on `Ctrl+D`.

**Comment by astoilkov** [comment]
Caret now has Delete Line command. Closing this issue.
