### ISSUE TITLE
Convert [[toc]] to full Markdown

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#255]
`[[toc]]` is a useful feature of Caret but does not render e.g. on GitHub. It would be good to have a context action (Ctrl+spacebar) to convert `[[toc]]` into a full Markdown. For example,

```md
[[toc]]
```

would turn into

```md
- [First section](#first-section)
- [Second section](#second-section)
```

**Comment by astoilkov** [comment]
This is now implemented in the latest Caret release.

Closing this issue. Thanks for the great idea.

**Comment by borekb** [comment]
Funny, I had to google this issue to find out how to insert full Table of Contents into Caret :) Maybe this menu item could be nested, like Headings, and contain two options, _Insert [[toc]]_ and _Insert full Table of Contents_.

![image](https://user-images.githubusercontent.com/101152/39320029-31f1fa30-4983-11e8-9427-f48a4449212b.png)
