### ISSUE TITLE
Emoji autocomplete does not work before a space character

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#256]
Emoji autocomplete (https://github.com/careteditor/caret/issues/137) was not working for in some cases, I've narrowed it down to a space character. Compare trying to enter emoji between `Some` and `words`:

![image](https://cloud.githubusercontent.com/assets/101152/23606854/d3d1f90e-0262-11e7-88e2-425d74ff8897.png)

![image](https://cloud.githubusercontent.com/assets/101152/23606863/dc8c549a-0262-11e7-8ab9-5086549d6183.png)

![image](https://cloud.githubusercontent.com/assets/101152/23606910/1e702af8-0263-11e7-8064-e7f3410b578e.png)

**Comment by astoilkov** [comment]
This is now fixed in the latest version of Caret.

Closing this issue.
