### ISSUE TITLE
Missing " in the exported HTML

### ISSUE THREAD

**Issue by jamesec** [careteditor/caret#257]
Every exported html,
The 2nd " in `<meta charset="UTF-8">` is missing.

You just try _Export to HTML..._ and can reproduce this bug.

Caret Version 1.15.1 on masOS 10.12.3

**Comment by astoilkov** [comment]
Indeed. We know about the issue. It is fixed internally. The next release will include the fix.

Thanks for reporting. I will write again in this thread when the fix gets included in an official release.

**Comment by astoilkov** [comment]
This issue is now fixed in the new 2.0 Caret release.

Closing this issue. Thanks for reporting.
