### ISSUE TITLE
Cursor position is ambiguous

### ISSUE THREAD

**Issue by Makkori** [careteditor/caret#261]
In the following image, the cursor position is in front of the period, but is displayed behind.
![cursor](https://cloud.githubusercontent.com/assets/16304495/24292071/ed8644d6-108b-11e7-85f0-df4a6a123733.png)

**Comment by astoilkov** [comment]
Thanks for reporting this issue. Can you tell me what font you are using and what is the contents of the line where this issue happens?

Thanks in advance.

**Comment by Makkori** [comment]
No settings were changed except the `lineWidth` in order to match line breaks in existing files.
```
font: Roboto
fontSize: 16
lineHeight: 1.9
lineWidth: 80
```
The line in question is
> this analyis is used to select which files to use when generating the new reference file.

(Yes, there is a typo...)

**Comment by EnCey** [comment]
I also have this issue in the newest version, it appears to be the same as #214 that was fixed a while ago.
Also using the default Roboto font.

**Comment by astoilkov** [comment]
We have fixed it. Expect a new release in the next hour.

**Comment by astoilkov** [comment]
Caret 2.0.1 is now available with fix for this issue.

Closing this issue.

**Comment by Makkori** [comment]
Still some issues it seems. The cursor is after the period in this case.
![cursor2](https://cloud.githubusercontent.com/assets/16304495/24297268/734026e4-10a2-11e7-9eb2-965b069a0211.png)

**Comment by astoilkov** [comment]
@Makkori - you could follow the progress of this issue [here](https://github.com/careteditor/caret/issues/264#issuecomment-289048909)
