### ISSUE TITLE
Strange cursor positioning

### ISSUE THREAD

**Issue by ritashugisha** [careteditor/caret#264]
Unsure if this is a sub-issue of #261 but I'm experiencing strange cursor positioning in v2.0.1.
I also notice that a cursor continues to be shown after "For example" in the gif.

![Imgur](http://i.imgur.com/ebGvEcc.gif)

Using default settings on Ubuntu 16.10.

**Comment by Bhendrickx** [comment]
I have the same issue. The cursor seems to diverge more from alignment as it nears the end of a line.

Caret version 2.0.1
Ubuntu 16.10

**Comment by astoilkov** [comment]
Hi,

We will need some time to investigate this problem as it is a strange one. It seems it can be replicated only under Ubuntu 16.*. It appears that letters are smaller there.

**Comment by EnCey** [comment]
I'm also still experiencing this problem in version 2.0.1 on a Windows 10 system:
![image](https://cloud.githubusercontent.com/assets/1894528/24302083/be683a30-10b1-11e7-9948-729147b95e71.png)

**Comment by erusev** [comment]
@EnCey What font is that? Thanks

**Comment by astoilkov** [comment]
@EnCey Does the problem gets fixed if you restart the app?

**Comment by astoilkov** [comment]
We think we fixed all issues related to cursor position. @ritashugisha @Bhendrickx @EnCey Can you check if everything is ok in the 2.0.2 release?

**Comment by EnCey** [comment]
Oh snap, I did change the font in the editor too, not just in the preview...
Sorry for reporting that incorrectly; the font I'm using is [Source Code Pro](https://www.fontsquirrel.com/fonts/source-code-pro).

Solved for me in 2.0.2, cursor is positioned correctly now.
It's amazing how fast you guys are at fixing stuff, excellent job!

**Comment by ritashugisha** [comment]
Also fixed for me as of v2.0.2

**Comment by astoilkov** [comment]
Great to hear. Closing this issue then.

**Comment by Bhendrickx** [comment]
Update to v2.0.3 fixed it for me as well. Thank you.
