### ISSUE TITLE
Custom keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#267]
I wanted to remap Ctrl+D form _Selection › Select Next_ to _Edit › Delete Lines_ so my config now looks like this:

![image](https://cloud.githubusercontent.com/assets/101152/24381471/cb595c8c-1350-11e7-9431-ca037f566852.png)

However, pressing `Ctrl+D` still expands selection. I was able to successfully remap some other keyboard shortcuts so maybe it's something about this one specifically.

**Comment by astoilkov** [comment]
This is now fixed in Caret 2.0.5. You could test it.

**Comment by borekb** [comment]
Works! Thanks.
