### ISSUE TITLE
Settings to insert emoji as Unicode characters by default

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#269]
Something like

```
insertEmojiAsUnicode: true
```

in `Preferences.md`.

**Comment by borekb** [comment]
Would be nice, I happen to convert all `:emoji:` to Unicode characters manually.

**Comment by erusev** [comment]
This should probably be the default behavior - what do you think?

**Comment by borekb** [comment]
Good idea. 👍

**Comment by borekb** [comment]
Just remembered about this issue, I'm converting emoji to Unicode all the time :)

**Comment by astoilkov** [comment]
@borekb This is on our roadmap so expect it soon.

**Comment by astoilkov** [comment]
This is now the default behavior in Caret 4.0 Beta.

Closing this issue. Thanks Borek!
