### ISSUE TITLE
Nested List Support

### ISSUE THREAD

**Issue by jalaziz** [careteditor/caret#27]
It appears that nested lists aren't well supported.

Auto-completion, highlighting, and preview all seem broken when writing nested lists.

**Example**:

```
Some list:
  1. A
  2. B
    - a
    - b
  3. C
```

**Github Rendered**:

Some list:
1. A
2. B
   - a
   - b
3. C

**Comment by erusev** [comment]
Thanks, we'll see what we can do.

**Comment by erusev** [comment]
It took some time, but this is now resolved 🎉
