### ISSUE TITLE
Config option to set number of Tab spaces

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#273]
When I press `Tab`, Caret inserts 2 spaces. I'd like to configure this to be four.

**Comment by pslobo** [comment]
I want put in another request for this. It's not always that easy to see exactly what is indented and what isn't.

**Comment by kevindoveton** [comment]
When creating sub lists, the rendering engine requires that it be indented by 4 spaces from the main list before being converted to a sublist. This can cause confusion as to why lists are not rendering correctly.

**Comment by scott-mead** [comment]
I'm using python flask-flatpages to render .md to html on our site.  python markdown needs 4 spaces (same with pandoc and bitbuckest) to show indentation levels in lists.

**Comment by astoilkov** [comment]
We have introduced a preference called `tabSize` in the new Caret 4.0 Beta available [here](https://caret.io/4beta/).

Closing this issue. Thanks for all the feedback.
