### ISSUE TITLE
Separate setting for code font

### ISSUE THREAD

**Issue by chriskrycho** [careteditor/caret#275]
Love the new settings approach—a block of YAML is genius for this—and I'd love for the next supported setting to be the code font used for inline and block code.

Love the app! 👍

**Comment by astoilkov** [comment]
We are happy to say this is now implemented in Caret.

In order to change the font used in code blocks you could go to Preferences and alter the `font` property value.

![image](https://user-images.githubusercontent.com/884810/28314523-940647a6-6bc3-11e7-8767-8453c723f1d1.png)


Closing this issue.
