### ISSUE TITLE
Menus don't follow OS X conventions

### ISSUE THREAD

**Issue by wezm** [careteditor/caret#28]
Overall the app is pretty great. Here's some nitpicky stuff that made it feel a little off for me:

Caret's menu deviate from OS X conventions::
- By putting preferences in the menu bar
- Not having an About option in the application menu
- Including options like Minimize and Fullscreen in the application menu, which are typically in a Window menu
- The Preview item does not change state when Preview is active. Typically a checkmark is added like: ![screen shot 2015-12-08 at 4 34 03 pm](https://cloud.githubusercontent.com/assets/21787/11648528/996ed2c2-9dc9-11e5-89a7-be4ed4a29974.png)
- Typically the ⌘P shortcut is used/reserved for Print
- Menu items that will present a dialog or confirmation don't have ... after them. E.g. Save As

When saving a new document the save dialog defaults to the root of the hard disk, whereas this would normally be one of the directories in the user's home directory such as Documents.

**Comment by erusev** [comment]
Hi @wezm,

Thanks for your feedback and for the kind words.

I'll try to address your points:

> By putting preferences in the menu bar

Where would you prefer preferences to be?

> Not having an About option in the application menu

What would you expect to see in an in-app About page?

> Including options like Minimize and Fullscreen in the application menu, which are typically in a Window menu

Well, usually, Minimize is in "Windows" and "Fullscreen" is in "View", but we felt like it doesn't make much sense to introduce 2 more menus just for these items.

> The Preview item does not change state when Preview is active. Typically a checkmark is added like: screen shot 2015-12-08 at 4 34 03 pm

This makes sense, we'll see what we can do.

> Typically the ⌘P shortcut is used/reserved for Print

This is true, but it's also well associated with print preview (ex: try hitting ⌘P as you read this in your browser).

> Menu items that will present a dialog or confirmation don't have ... after them. E.g. Save As

This also makes a lot of sense.

**Comment by hkdobrev** [comment]
I'd like to reiterate on some of @wezm points:

> Where would you prefer preferences to be?
> What would you expect to see in an in-app About page?

- [ ] *Preferences* should be in the *Caret* menu.
- [ ] *About* should be the first item in the *Caret* menu. It should have the version, website, authors, license info. Basically most of the items in the *Help* menu.
- [ ] Having consistency with *Full Screen*, *Minimize* and *Zoom* is a big plus for me. I'd prefer *Enter Full Screen* in *View* and also *Minimize* and *Zoom* in *Window*. I have global Mac OS shortcut for the Zoom feature and not having it in the menus prevents me from using my shortcut.
- [ ] Most of the items in *Preferences* could be moved in a *View* and the least used ones in a dialog box if any.

**Comment by erusev** [comment]
@hkdobrev 

Thanks for the input.

> Preferences should be in the Caret menu.

I agree that the place for an item called "Preferences" would be in the "Caret" menu, but we don't have such an item.

> About should be the first item in the Caret menu. It should have the version, website, authors, license info. Basically most of the items in the Help menu.

This makes sense.

> Having consistency with Full Screen, Minimize and Zoom is a big plus for me. I'd prefer Enter Full Screen in View and also Minimize and Zoom in Window. I have global Mac OS shortcut for the Zoom feature and not having it in the menus prevents me from using my shortcut.

Would it help if we add a "Zoom" item to the "Caret" menu and associate it w/ the standard shortcut?

> Most of the items in Preferences could be moved in a View and the least used ones in a dialog box if any.

I'm not sure I understand this.

**Comment by hkdobrev** [comment]
> Would it help if we add a "Zoom" item to the "Caret" menu and associate it w/ the standard shortcut?

There's no standard shortcut for Zoom, but the fact it's in the menu somewhere on every app, allows me to have a shortcut for it using the App Shortcuts feature in Mac OS. I'd prefer the consistency of the Window menu, but my shortcut and looking through the menus by typing in the Help box would work no matter where it is.  


> > Most of the items in Preferences could be moved in a View and the least used ones in a dialog box if any.

> I'm not sure I understand.

Most apps have a *View* menu which would be ideal for the most of the items you have in *Preferences*.

**Comment by erusev** [comment]
Thanks, @hkdobrev.

**Comment by onury** [comment]
Here is my input:  

  - Preferences / Font (block) should move to **Format** menu.
  - Preferences / Font Size (block) should move to **Format** menu.
  - Preferences / Check Spelling should move to **Edit** menu.
  - Preferences / Autosave should move to **File** menu.
  - Preferences / Mid-Screen Scrolling  should move to **Window** menu.

### A new menu: "View" should be added.

  - Preferences / Block Focus should move to **View** menu.
  - Preferences / Dark Mode should move to **View** menu.
  - Preview / Show should move/rename to **View / Preview**
  - Preview / Default should move/rename to **View / MD Flavour: Default**
  - Preview / GitHub should move/rename to **View / MD Flavour: GitHub**
  - Preview / Add Theme.. should move to **View** menu.

No items left for Preferences menu, so it should be removed.

**Comment by erusev** [comment]
@onury Makes sense, in fact, we've been thinking about something very similar to what you propose.

**Comment by astoilkov** [comment]
We are happy to say we made a lot of improvements to the application menu in the latest Caret 1.10.0 release.

We followed a lot of the suggestions and feedback in this thread. Thank you for all your comments. We hope you like the changes.

I am closing this issue. However, if anyone have additional suggestions and feedback do not hesitate to write here and we will reopen it.
