### ISSUE TITLE
Maximized window takes up more space than it should

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#285]
At the bottom part, Caret's maximized window slightly overlaps Windows taskbar:

![image](https://cloud.githubusercontent.com/assets/101152/24578550/6c3aceda-16e2-11e7-8076-d7b851ade6b6.png)

Never seen this before, started happening with Caret 2.0.6.

**Comment by astoilkov** [comment]
I have just tested this on our Windows 10 machine and I can't seem to replicate the problem. I did go through every change between 2.0.5 and 2.0.6 and I wasn't able to identify anything that could have changed window behavior. Can you download 2.0.5 and see if the problem appears there?

**Comment by borekb** [comment]
It is quite hard to see because the app window is usually "below" taskbar (I think it's some Windows bug when it lets app windows on top of the taskbar but it occasionally happens). But it's still visible.

OK state (window not full screen, dragged to align well with the taskbar):

![image](https://cloud.githubusercontent.com/assets/101152/24606766/0a6b7266-186f-11e7-8dc5-aa7702939a60.png)

The problematic state with the window maximixed:

![image](https://cloud.githubusercontent.com/assets/101152/24606796/2958a824-186f-11e7-993b-2119acfab36e.png)

You should be able to see a couple of pixels of white-ish window through the semi-transparent taskbar.

**Comment by astoilkov** [comment]
I think I found the [problem](https://github.com/electron/electron/pull/9167). Electron have fixed it so we can update and see if it will fix the problem for us as well.

**Comment by astoilkov** [comment]
Is this fixed in the latest version for you?

**Comment by borekb** [comment]
Yes it is. Thanks!
