### ISSUE TITLE
Shortcut to go to end/beginning doesn't work

### ISSUE THREAD

**Issue by hgezim** [careteditor/caret#286]
Command+Arrow key should move you to beginning or end of current line. It doesn't do that in Caret.

**Comment by astoilkov** [comment]
Hi @hgezim,

This is very strange. We can't replicate this problem. Can you please try to restart the app or your computer and see if the problem persists.

Does the Command+Arrow shortcut work in other applications? Do you have Visual Studio Code or Atom on your computer to see if the behavior is the same there?

Thanks for your collaboration in advance.

**Comment by hgezim** [comment]
Thanks for prompt reply. I tried it in other apps and it works (sublime)
but don't think I tried it on an Electron app. Will let you know.

**Comment by hgezim** [comment]
Works now 🤷‍♂️. Sorry for the trouble.
