### ISSUE TITLE
Auto-formatting of headings interfers with 'Move line'

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#287]
Before:

![image](https://cloud.githubusercontent.com/assets/101152/24728089/d5d1e3be-1a58-11e7-80a3-ac2f1b3535bc.png)

I just want to move the `---` line a couple of lines down but after the first one, it is recognized as a heading marker and changed:

![image](https://cloud.githubusercontent.com/assets/101152/24728100/e045902a-1a58-11e7-953a-bd3fde042c68.png)

It's not the desired behavior in my case (I don't use settext-style headers).

**Comment by astoilkov** [comment]
Fixed in 2.0.9
