### ISSUE TITLE
Recent files: keep MD file from a Git branch

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#291]
I'm a heavy user of Ctrl+E (navigate to recent files) but if I'm editing a Markdown file that is in a Git branch and I'm switching between branches often, this file gets removed from the recent list.

Caret probably checks whether the files in the recent list exist on disk and if not, it removes them from the internal data structure permanently. A better implementation for me would be to only filter on the UI level. When the file comes back (I switch back to a Git branch where my file exists), it shows up again in Caret.

**Comment by astoilkov** [comment]
Definitely. I will do this immediately. Thanks for the suggestion.

**Comment by astoilkov** [comment]
Included in 2.0.10.
