### ISSUE TITLE
Word wrapping bug

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#292]
Before moving "Test" one line up:

![image](https://cloud.githubusercontent.com/assets/101152/24995816/87c0e98a-2030-11e7-93a7-a9fcc2d90326.png)

After ( 🐛 ):

![image](https://cloud.githubusercontent.com/assets/101152/24995819/8e374fe8-2030-11e7-94f2-a05419d67017.png)

After I pres Ctrl+End and Enter, it is fixed:

![image](https://cloud.githubusercontent.com/assets/101152/24995870/b76bbb92-2030-11e7-92db-47362adc90cd.png)

**Comment by astoilkov** [comment]
This is now fixed in the [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue.
