### ISSUE TITLE
Ctrl+click on link in editor mode works strangely

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#293]
After I press <kbd>Ctrl</kbd> the pointer changes to hand cursor but clicking on the link does nothing. I need to release the <kbd>Ctrl</kbd> and click on it plainly (the pointer remains the hand one, strangely).

Update: the behavior is not completely predictable. Sometimes, Ctrl+click works the first time, sometimes it doesn't.

**Comment by astoilkov** [comment]
Can you test the behavior in the latest release? We think we fixed it.

**Comment by borekb** [comment]
Seems fixed, thanks!

**Comment by borekb** [comment]
Just happened to me again in 2.0.11. Example Markdown was:

```md
- Issue about XYZ (https://github.com/versionpress/versionpress/issues/406)
```

**Comment by astoilkov** [comment]
I tried everything to replicate the problem but without success. If you have any idea on what could be the steps for reproducing this would be great.

**Comment by borekb** [comment]
Oh it's a focus issue. If I'm inside Caret all works fine. If I have two windows side by side, the focus being in the other window, then Ctrl+clicking the link in Caret without giving it focus explicitly leads to this "issue". But it's just a tiny quirk only, not worth any more energy :) Thanks.
