### ISSUE TITLE
Feature request: create new file within selected directory

### ISSUE THREAD

**Issue by vanniewelt** [careteditor/caret#294]
When I'm working on some file in particular directory, it would be very useful if I could create new file by entering its name or path relative to current directory and save it immediately (similar to `Go > To File`) Currently I must `File > New`, `File > Save As...` and select the location I worked within, which is quite annoying (save dialog remembers only the location I recently saved to).

**Comment by astoilkov** [comment]
We actually have a mechanism for creating files. Open `Go > To File`, write the name of your new file and hit `Cmd/Ctrl+Enter` - this will create the file in the current directory.

We are aware that we don't promote and educate our users about this feature. We plan to change that by creating some videos that show hidden features like this.

**Comment by astoilkov** [comment]
I am closing this issue. Do not hesitate to write us if you have additional questions or suggestions.
