### ISSUE TITLE
When using multiple cursors, only one line is indented when pressing tab

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#296]
I know I already mentioned this on twitter, but I think it makes more sense to move those bugs/feature requests over to here, so...

When using multiple cursors and pressing tab, only the original line is indented and not every line, as I'd expect.

![screen-recording-2017-04-17-13-57-26](https://cloud.githubusercontent.com/assets/1452095/25089521/ed8286dc-2375-11e7-8df2-22b2e36d8784.gif)

**Comment by astoilkov** [comment]
We fixed this issue in the latest Caret 2.0.11 release.

Closing this issue. Thank you for reporting.
