### ISSUE TITLE
Autocomplete path doesn't work when using ~/

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#297]
When using the Unix standard for the home folder, autocomplete doesn't work as expected.

On a side note, I'd love to see support for autocomplete and relative paths too. So, typing `![](../img/image1.png)` would get autocompleted too.

**Comment by astoilkov** [comment]
We have fixed the issue in the 2.0.11 Caret release.

Regarding the relative paths - I can't seem to replicate this issue. Can you test them in a saved document - they don't work when working in untitled document?

**Comment by pslobo** [comment]
Yeah, that was it. I was currently working on an unsaved document when I tested that. Sorry about the confusion. Relative paths are working just fine in autocomplete when used with a saved document... Oops 😊

**Comment by astoilkov** [comment]
Great to hear that. Closing this issue then. Thank you very much for all the reports.
