### ISSUE TITLE
More contrast for modal dialogs / context menus

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#299]
Things like context menu, about dialog etc. all blend into the document and sometimes it's hard to make out.

Here's a quick example: 

![screen-shot-2017-04-13-21-14-06](https://cloud.githubusercontent.com/assets/1452095/25090803/57de5fcc-237d-11e7-97c0-44cf56f12ddd.png)

**Comment by borekb** [comment]
Agree, same for navigation features, search etc.

**Comment by pslobo** [comment]
This is now much better for context menus, thanks!

**Comment by astoilkov** [comment]
Great to hear that. Closing this issue then.
