### ISSUE TITLE
Customizable CSS Theme Support

### ISSUE THREAD

**Issue by seven-jinxin** [careteditor/caret#30]
Can let user customize theme by css?

**Comment by erusev** [comment]
Not at this point, but we are working on it.

**Comment by erusev** [comment]
Do you have specific things in mind that you'd like to change in the current theme?

**Comment by seven-jinxin** [comment]
I have ever used another MarkDown editor, It could export to PDF from File menu, and allow user to use a css file as theme. 

What's the next?

I could use the markdown editor to write down business plan, comments, then export to PDF with Business Styled. It's so great for me. It's a pity that software haven't got update for a long time.

**Comment by erusev** [comment]
Could you tell us the name of that editor? Thanks!

**Comment by seven-jinxin** [comment]
it called mou.
http://25.io/mou/

I'm also be the paied user for that app, but there isn't any update more than half a year, and the author haven't reply my mail.

**Comment by erusev** [comment]
Thanks, we'll see what we can do.

**Comment by instanceofme** [comment]
+1 very handy

I currently use [Marked](http://marked2app.com) for HTML & PDF export with custom CSS, it makes the workflow less straightforward.

**Comment by ardian** [comment]
Hey @erusev also check penflip.com dark mode theme, it's really clear and good looking, but yes having the option to customize via CSS can open the way for the community to make themes for the editor.

**Comment by astoilkov** [comment]
We are really excited to say we introduced Custom CSS Theme support in the latest version of Caret. It is under the new Preview application menu. You could update and try it out.

**Comment by astoilkov** [comment]
Hi @ardian,

Yes. We have plans for introducing themes for the editor. In the moment we are focused on other key features but we will definitely add this feature some time in the future.
