### ISSUE TITLE
alt+cmd+ double click to select multiple words.

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#300]
Currently, when pressing alt+cmd+click (and drag) we can select multiple words. I'd like to see this extended to support alt+cmd+doube click to select multiple words. As it stands, the current behaviour selects the entire word but eliminates all previous selections.

![kapture 2017-04-17 at 15 19 14](https://cloud.githubusercontent.com/assets/1452095/25091495/500b74a2-2381-11e7-8725-887e741b0555.gif)

**Comment by pslobo** [comment]
Yay! Thanks!!

**Comment by astoilkov** [comment]
We fixed both double and triple click selection. Hope you like it.

Closing this issue.
