### ISSUE TITLE
Images not displaying properly in preview window.

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#302]
Images that have a space in their name are not displayed correctly in preview, nor are images that are referenced using `~/`.

I'd expect that images with a space in the filename work using either `""` or by escaping the space. So, `![]("Image Bug.png")` or `![](Image\ Bug.png)` should both work in my opinion.

![2017-04-18 15_27_38](https://cloud.githubusercontent.com/assets/1452095/25135937/95544eba-244b-11e7-8f0e-bf501bff7864.gif)

**Comment by pslobo** [comment]
Partially fixed. 

As you can see from the image, when referencing a local image with a space in the name, escaping or enclosing in " does nothing.

When using the full path, there is no need to escape, but the image doesn't show inline as in other cases. When using full path and " again, not working. When using full path and escaping the space, it shows in preview but not inline.

![screen shot 2017-05-11 at 14 13 45](https://cloud.githubusercontent.com/assets/1452095/25950934/13109cd6-3654-11e7-90e0-34a46ad4bbdc.png)

**Comment by astoilkov** [comment]
We now fixed all the things you have described - expect an update soon.

**Comment by pslobo** [comment]
Confirmed and damn fast too! WOW 👍
