### ISSUE TITLE
Spell checking doesn't kick in

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#304]
Sometimes, spell checker isn't checking my document. It happens relatively rarely but I found a small repro that I can share. OK state:

![image](https://cloud.githubusercontent.com/assets/101152/25171686/f2860bb6-24ee-11e7-99be-f8fb9af4633d.png)

Error state:

![image](https://cloud.githubusercontent.com/assets/101152/25171756/220b2452-24ef-11e7-8799-dd965a3522f3.png)

Text in verbatim:

```md
asdf 

- Doesn't happen often but it does happen.

```

**Comment by borekb** [comment]
Even smaller example:

Doesn't spell check 🚫 

```md
asdf 

Doesn't happen often but it does happen.
```

Does spell check ✔️ 

```md
asdf 

Doesn't happen often.
```

**Comment by astoilkov** [comment]
We think we found the problem causing this. We will notify you when we release the next version of Caret so you could test this.

**Comment by borekb** [comment]
That was fast, looking forward to it.

Another spell checking issue that I don't have a good repro at hand is that sometimes, it seems to think that the word ends at the start of the next word. For example, it would autocorrect this:

```
tesst|

Next paragraph.
```

to

```
test|Next paragraph.
```

But as I said, I don't have a good repro and this bug seems to be there only momentarily. If I see it again, I'll try to capture it and create a new issue.

**Comment by astoilkov** [comment]
Is this fixed for you in the latest release?

**Comment by borekb** [comment]
Yep, all is fine, thanks!
