### ISSUE TITLE
Where is the menu in Ubuntu MATE?

### ISSUE THREAD

**Issue by orschiro** [careteditor/caret#309]
Dear all, 

Very interesting editor!

Question:

How do I basically use this editor?

On Ubuntu MATE, I do not know how to proceed from this blank screen without any menu. 

![image](https://cloud.githubusercontent.com/assets/170947/25196388/cabe9ec0-2540-11e7-9bb1-82c9c342cb75.png)

**Comment by borekb** [comment]
Just write.

**Comment by astoilkov** [comment]
Hi @orschiro,

You could press the Alt key and the application menu will show up. Let me know if that helps.

**Comment by astoilkov** [comment]
You could also open Command Pallete `Ctrl+Shift+P` which shows all available application commands.

**Comment by orschiro** [comment]
@astoilkov, it does help, thank you so much! :-)

May I ask one last question quickly?

Does Caret support a handy auto-save on close?

**Comment by astoilkov** [comment]
Great to hear @orschiro 

Regarding the auto-save on close - what do you mean by that? We have a `File -> Autosave` feature but maybe what you are referring to is different?

**Comment by orschiro** [comment]
Dear @astoilkov,

This is it. Amazing, thank you! :-)
