### ISSUE TITLE
Export. Export to PDF and HTML

### ISSUE THREAD

**Issue by seven-jinxin** [careteditor/caret#31]

**Comment by erusev** [comment]
Something like "export to HTML" already exists - just select all and hit Edit » Copy as HTML.

As to "export to PDF", we plan to implemented, but it's a bit complicated so it'd take some time.

**Comment by hkdobrev** [comment]
You can export to PDF with your Mac OS print dialog if you have a print dialog available in Caret.

**Comment by erusev** [comment]
Thanks @hkdobrev we'll investigate this approach.

**Comment by nblackburn** [comment]
+1

**Comment by erusev** [comment]
"Export to PDF" will ship with 1.1 later this week

**Comment by astoilkov** [comment]
Done. You could start the app and wait for the footer to show up prompting you to restart the app.
