### ISSUE TITLE
Ctrl+click on internal link navigation

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#311]
It would be nice if Ctrl+click on internal links (inside the same document) worked. Note: they do in the preview mode, this is about the editor mode.

![image](https://cloud.githubusercontent.com/assets/101152/25230176/58270134-25d3-11e7-8fcb-c47457b48922.png)

**Comment by pslobo** [comment]
I can't get this to work, either in preview or inside the actual document.

this code doesn't work for me

```markdown
1. [Title 1](#title1)
...
...
...
## Title 1 <a name="title1"></a>
...
```

Context menu shows `visit title1` but selecting that does nothing. Preview shows clickable link, but clicking it does nothing.

Testing on macOS Sierra.

**Comment by astoilkov** [comment]
This is not how the link between titles is made. The name of the title is automatically generated by making the text lowercase and adding `-` between spaces. In your example the link should be `[title 1](#title-1]` in order to work.

**Comment by pslobo** [comment]
Ah crap, there I go again defaulting to MultiMarkdown spec 😁 

Tested that way and it is indeed working. Sorry about the mixup.

**Comment by astoilkov** [comment]
Closing this issue.

@pslobo If you think your scenario is also worth implementing you could open a seperate issue.

**Comment by pslobo** [comment]
Not needed, I'm fine adjusting to this new format, especially since you're not using the MMD spec but rather GFM spec, best to stick to it.

**Comment by borekb** [comment]
Caret 2.1.2 navigates correctly but I still get this popup dialog:

![image](https://cloud.githubusercontent.com/assets/101152/25998170/fba1271a-371f-11e7-95f2-72b0834021b5.png)

**Comment by astoilkov** [comment]
@borekb - We missed that sorry. Already fixed it so the next release won't have that problem. Thanks.

**Comment by borekb** [comment]
One more thing: I sometimes have internal links like this:

```md
Toc:

- [Section](#section)

<div id="section"></div>

## Some complicated section name
```

In essence, I create an invisible DIV with a simple and stable `id` but Caret doesn't seem to understand that. If I change the link to `[Section](#some-complicated-section-name)` it works.

**Comment by pslobo** [comment]
That's similar to the MultiMarkdown spec I was referring to that essentially allows you to add a link like [A Title](#atitle) that later points to <a name="atitle"></a>

**Comment by pslobo** [comment]
That's similar to the MultiMarkdown spec I was referring to that essentially allows you to add a link like `[A Title](#atitle)` that later points to an html tag like `<a name="atitle"></a>`

**Comment by astoilkov** [comment]
@borekb - we need additional implementation to support this scenario
