### ISSUE TITLE
Main Context Menu appears on Second Monitor

### ISSUE THREAD

**Issue by BrynnMountain** [careteditor/caret#314]
When clicking on the main menu drop down at the top left of Caret, the context menu appears on my left monitor, instead of on the primary monitor where the Caret window is open.

![caret-2-0-bug](https://cloud.githubusercontent.com/assets/9312117/25244574/21c32e00-25b6-11e7-9217-e5a3cb94eeba.png)

**Comment by astoilkov** [comment]
Hi @BrynnMountain,

Does this happen every time? Should the window be maximized?

Thanks for reporting.

**Comment by te1** [comment]
This happens for me every time when the window is maximized or otherwise aligned on the left edge of the right screen on Windows 8.1.

**Comment by BrynnMountain** [comment]
@astoilkov This happens every time my window is maximized on Windows 10 - v.1607. Unlike @te1 though, I don't have this issue when the Caret window is left-aligned.

**Comment by astoilkov** [comment]
@te1 and @BrynnMountain Is this issue now fixed for you? We included a fix related to this issue in Caret 2.1.0. We aren't experiencing the issue on our Windows 10 test machine.

**Comment by te1** [comment]
It now works as expected for me. Thanks :)

**Comment by BrynnMountain** [comment]
@astoilkov Can confirm this is fixed as of 2.1.3! Thanks!

**Comment by astoilkov** [comment]
Great. Closing this issue then.
