### ISSUE TITLE
Fixed Menu/Word count Font size

### ISSUE THREAD

**Issue by flegfleg** [careteditor/caret#318]
When increasing the font size to a comfortable size on the Retina Macbook, the title bar text gets comically large. 

![bildschirmfoto 2017-04-22 um 15 45 31](https://cloud.githubusercontent.com/assets/4009931/25304970/bb75ebe2-2772-11e7-9b44-8161babf063c.png)

**Comment by erusev** [comment]
Looks like a valid issue, we'll see what we can do, thanks!

**Comment by astoilkov** [comment]
We changed the behavior of the UI in Caret and now increasing the font size increases only the text size in the editor.

Closing this issue. Thanks a lot for reporting.
