### ISSUE TITLE
Spell checking "wraps" to the next line

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#319]
I've finally managed to reproduce a spell checking bug initially reported in https://github.com/careteditor/caret/issues/304#issuecomment-295230545:

![image](https://cloud.githubusercontent.com/assets/101152/25318157/45e809d8-2889-11e7-9745-9b724f67fe97.png)

After pressing `Delete`:

![image](https://cloud.githubusercontent.com/assets/101152/25318159/5aecefa6-2889-11e7-95aa-053c4e62b255.png)

Suggestions are weird (don't include 'test'):

![image](https://cloud.githubusercontent.com/assets/101152/25318166/6b075ebc-2889-11e7-8524-de4e7e7bf0fe.png)

After I select "tests" correction:

![image](https://cloud.githubusercontent.com/assets/101152/25318172/7a63803e-2889-11e7-85ea-9ac945d7b6e8.png)

**Comment by borekb** [comment]
Something is wrong with spell checking when **deleting text**. I think that the original bug report is just one special case of it. I can get error even in the middle of the line, like this:

![image](https://cloud.githubusercontent.com/assets/101152/25339899/5cb94c1e-2904-11e7-807e-478a04ccc52c.png)

**Comment by borekb** [comment]
Another possibly related observation: sometimes, Caret thinks that a punctuation after the word is part of it. I had a text "bla bla config, bla bla" (note the comma), I've added the word "config" into dictionary but actually, "config," was added:

![image](https://cloud.githubusercontent.com/assets/101152/25472910/93a0817c-2b2d-11e7-9838-b0d44bf4216e.png)

Now, the "config" word is still unknown and marked as incorrect.

**Comment by astoilkov** [comment]
Thanks a lot for all the detailed information and observations. We will investigate everything.

**Comment by borekb** [comment]
Punctuation bug: https://github.com/careteditor/caret/issues/351

**Comment by astoilkov** [comment]
This is now fixed in Caret 4.0 Beta.

Closing this issue.
