### ISSUE TITLE
Critical - Typing accented characters (like in "cómo", "línea") deletes the previous lettter

### ISSUE THREAD

**Issue by jjarava** [careteditor/caret#32]
Hi!

Just getting started with Caret (looks great), but I've run into a "I can't work with it" bug in the first 10 minutes.

Caret has an issue on the way it handles the accented characters (which in Spanish, for instance, are quite common). When typing words like `cómo´ and `línea`, when typing the accent, the previous letter is deleted.

I've done a GIF capture to show what I mean; hope that it's properly visible 
![caret-accented-characters-issue](https://cloud.githubusercontent.com/assets/2682444/11902438/23a2ebaa-a5b2-11e5-9b35-fce0fb895132.gif)

Please fix ASAP as it's quite unusable for me at it is.

Thanks!

**Comment by astoilkov** [comment]
Hi,

Can you provide a little more information on the scenario. What version of Caret are you using (Opening the OS Caret menu shows the version)?

I have tried to reproduce the problem by adding a Spanish Input Source but without success. I am trying to do the following:
  - Write any letter for example `C`
  - Click `Option+;` (which puts ~ and then I can enter accent)
  - Click `o` to enter accent

Any suggestions on why I can't reproduce it?

**Comment by jjarava** [comment]
Hi, 

I'm using what I guess is the last version of Caret - v1.0.1

As how to type the accented character, I don't know why you can't repro the issue other than typing the accent that way is not how it's normally done... 

I'm using a standard Spanish keyboard layout and typing an accented character is a 2-key process:

1. Press the accent key (middle keyboard row at the right; see screenshot)
2. Press the corresponding vowel.

![caret-accented-characters-issue-typing-accents-2015-12-18_18-41-47](https://cloud.githubusercontent.com/assets/2682444/11903189/ad099786-a5b7-11e5-8c58-bde36c0610d4.jpg)

(in my case the layout is Spanish-ISO, but any Spanish keyboard I've used works the same: Accent and then the letter)...

In the screencap I sent, you can see that when I type `cómo`, the "*invisible*" keypress when I type the accent makes an underline appear under the c letter - the letter that is then deleted.

Don't hesitate to ask for more information if neeed

**Comment by astoilkov** [comment]
Ok. I have successfully replicated the issue. We will fix it as soon as possible and create a new release. We will get you notified.

Thanks for reporting this issue!

**Comment by astoilkov** [comment]
We have fixed the problem and will create a new release soon. You could expect a new update popup in a few days.

Thanks again.

**Comment by astoilkov** [comment]
We have just pushed a new update 1.0.2. It takes some time for the CDN to deploy the file in the entire world so it can take a while until you see a popup message for the update.

**Comment by jjarava** [comment]
Thanks!! The update arrived and I can confirm the issue is solved
