### ISSUE TITLE
Select more/less not working properly with list block

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#322]
Using alt + up/down arrows to select more/less isn't working as expected with list blocks. Whereas using that feature in a paragraph, it'll select work, sentence paragraph and then finally the parent (up to header and then next header) with a list it goes, word, line full block up to header  and doesn't select the list block.

![kapture 2017-04-25 at 21 56 48](https://cloud.githubusercontent.com/assets/1452095/25407524/811ad2d6-2a02-11e7-88e5-828b066e70b8.gif)

**Comment by astoilkov** [comment]
Hi @pslobo,

This is now implemented in the latest version of Caret 4.0 beta.

Closing this issue. Thanks for reporting! Hope you like the new beta.
