### ISSUE TITLE
Typing accented characters in tables is broken.

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#323]
This one is easier to show than to explain :)

![kapture 2017-04-25 at 22 32 35](https://cloud.githubusercontent.com/assets/1452095/25408810/33ed09e8-2a07-11e7-9156-9b79e6db05da.gif)

**Comment by astoilkov** [comment]
This is now fixed in the [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue.

Would be awesome to hear what you think about the Caret 4.0 Beta. Have a great day.
