### ISSUE TITLE
Spell checking shouldn't be active inside [link](url)

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#324]
Spell checking should be active in the URL:

![image](https://cloud.githubusercontent.com/assets/101152/25427430/d142505c-2a72-11e7-822d-359be481273a.png)

**Comment by astoilkov** [comment]
Do you mean only inside of the URL or in the title as well?

**Comment by borekb** [comment]
URL. `[This should be spell checked](...and this shouldn't)`.

**Comment by astoilkov** [comment]
Great. This is ready then. Expect it in the next release.

**Comment by astoilkov** [comment]
Closing this issue as it landed in the latest 2.1 release.
