### ISSUE TITLE
Format Menu not working properly when formatting headings

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#329]
When using either the menu or keyboard shortcuts to set some text as a heading, choosing another heading level will set it as normal text. You have to select again in order to apply correct formatting.

![kapture 2017-04-26 at 22 30 35](https://cloud.githubusercontent.com/assets/1452095/25458033/3eebd382-2ad0-11e7-8821-3a889902049e.gif)

**Comment by pslobo** [comment]
Working great, thanks. also, love the new headings :D

**Comment by astoilkov** [comment]
Awesome. We really like them too. Caret 2.1 is one of the updates we are really proud of.

Closing this issue.
