### ISSUE TITLE
Use HTTPS for connections to caret.io

### ISSUE THREAD

**Issue by jacobbednarz** [careteditor/caret#33]
During the startup little snitch prompts to connect to `caret.io` however it's only using HTTP instead of HTTPS. Depending on what this is used for, this should really be using HTTPS.

**Comment by erusev** [comment]
It does this to check for updates so no sensitive information is communicated, but I guess it wouldn't hurt to make the connections more secure.

**Comment by jacobbednarz** [comment]
Even just for updates it is important to be able to verify that the host you are communicating with is the intended host and the communication stream hasn't been tampered with during transport. If the update service is under HTTPS you can avoid man in the middle attacks (via DNS poisoning, etc) and ensure users don't end up with a malicious version installed.

**Comment by erusev** [comment]
Thanks, this makes a lot of sense.

**Comment by huwd** [comment]
:+1:

**Comment by huwd** [comment]
You come across [surge.sh](https://surge.sh/)? Can get SSL + custom domain for static sites for free. Various other features for their first price tier.

Just in case you didn't want to roll your own.

**Comment by erusev** [comment]
Thanks @huwd I'll check it out.

**Comment by erusev** [comment]
This is now resolved 🎉  - thanks for the patience.
