### ISSUE TITLE
Double ENTER should clear code block (?)

### ISSUE THREAD

**Issue by archfrog** [careteditor/caret#331]
Hi,

I love Caret.  But I have one gripe with v2.x.  Whenever I want to finish up a code block, I hit ENTER twice to clear/end the code block.  However, this does not work with Caret so I end up having to type BACKSPACE precisely four times to clear the code block.  This is rather irritating :-)

To recreate do this:

1. Start at the beginning of a new line.
2. Enter four spaces.
3. Enter some code such as: sudo apt install nginx.
4. Hit ENTER twice.
5. Notice that you're still editing code and that you have to delete the last line and precisely four spaces to get out of code editing again.

Thanks,
Archfrog

**Comment by pslobo** [comment]
Well, obviously @erusev and @astoilkov need to weigh in on this, but I'd consider that normal and expect behaviour, how else would you write code that indeed has some empty lines (for readability or any other reason)? A very lame example:

``` python
import whois

data = raw_input("Enter a domain: ")
w = whois.whois(data)

print w
```

vs.

```python
import whois
data = raw_input("Enter a domain: ")
w = whois.whois(data)
print w
```

Instead of creating code blocks using indents, I'd advise you to use triple backticks. It's cleaner and easier.
```
   ```shell
```

Hope this helps.

**Comment by archfrog** [comment]
Okay, I'll give it a try.  Thanks for the tip.  The only problem is that it is a pain to write backticks on Danish keyboards :-)  Perhaps I should use Markdown Extra fenced code blocks instead.  That way, I can also specify the format (if only I could locate a list of supported formats) of the code block.

**Comment by archfrog** [comment]
FYI, I found this from GitHub:

- [Creatinga and highlighting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

That seems reasonable enough.  I will consider this issue closed, but leave it for the authors to decide.

**Comment by pslobo** [comment]
Caret uses the GFM speck. You can check out the supported specs here. https://github.github.com/gfm/#fenced-code-blocks

**Comment by pslobo** [comment]
Yeah, the triple backticks are fenced code blocks. That's what I was suggesting. You can however use titldes too if that's better on Danish keyboards.

![screen shot 2017-05-01 at 16 10 47](https://cloud.githubusercontent.com/assets/1452095/25583212/c12a6348-2e88-11e7-9499-336fadeb054a.png)

**Comment by archfrog** [comment]
Pretty much the same.  Both involves dead keys: You hit a key, hit something else (such as space), and then the backtick or tilde appears.  I'll have to manage.  Now I got the color coding to work.  Thanks again!

**Comment by archfrog** [comment]
A final note for those stumbling upon this thread: Caret works beautifully if you use fenced code (three tildes or three backticks before and after the code).  No problem getting out of code mode there.  Caret actually inserts the closing code fence itself, so it is just a matter of moving the cursor a bit.

I only wish I could find a definitive, clear list of the names of all of the supported formats.  I tend to write documents that include multiple formats (Shell/Bash, .INI files, code snippets, and so on).

**Comment by pslobo** [comment]
@archfrog if you use fenced code blocks a lot, you can simply create a keyboard shortcut to add that, simply edit the keyboard-shortcuts.md file (how to do it depends on what OS you're using)
