### ISSUE TITLE
Feature: Send files to Trash when deleting in File Navigator

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#335]
I imagine the file navigator is manipulating the files via command line. I'd request/advise you implement some form of trash when deleting files. I'm not yet entirely sure how I pulled it off (need to test with some garbage data) but I managed to delete a few critical files and folders, and it's not the first time either when messing around with the navigator (not to worry though, I've got backups. Heck, I got backups of my backups 😀) Next user this happens to may not be as understanding though 😉

**Comment by astoilkov** [comment]
In the latest version Caret we moves files to the trash instead of permanently deleting them.

Closing this issue. Thanks for idea!
