### ISSUE TITLE
Undo bug

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#336]
As a repro, I have a new file with a single 🤞 emoji:

![image](https://cloud.githubusercontent.com/assets/101152/25597175/9e86e43e-2ecd-11e7-96cd-51081deb956f.png)

When I delete it and press Ctrl+Z (undo), I get back this:

![image](https://cloud.githubusercontent.com/assets/101152/25597178/a78bcdd8-2ecd-11e7-9245-0c398d7a5825.png)

Even weirder, as I kept pressing Ctrl+Z, I got a text from a _previous file_ (the file I was originally editing before encountering the undo bug and creating a new blank file to test it out):

![image](https://cloud.githubusercontent.com/assets/101152/25597230/e6f716e4-2ecd-11e7-8a84-d1b550e4ecfb.png)

**Comment by borekb** [comment]
Copy & pasting unicode is perfectly fine, there's just something wrong with the undo functionality.

**Comment by astoilkov** [comment]
We fixed the issue and it is now available in Caret official release. Thanks for reporting @borekb.

Closing this issue.
