### ISSUE TITLE
Option to hard wrap

### ISSUE THREAD

**Issue by jacobbednarz** [careteditor/caret#34]
I'm a big fan of 80 character line wraps and it would be great to have this option available within caret.

**Comment by erusev** [comment]
That's interesting, why exactly 80?

**Comment by jacobbednarz** [comment]
I'm an old school type of bloke and wrap at 72/80 characters for most things as I do it via CLI (including markdown). It would be nice to have this option so that I don't end up reformatting everything I open in CLI to avoid crazy scrolling and long lines.

**Comment by erusev** [comment]
Thanks, we'll see what we can do.

**Comment by erusev** [comment]
We're introducing this feature with the next release later this week.

I'll reopen this and close it when the release is out.

@jacobbednarz 

We were wondering why you closed the issue - is it because you no longer need the feature? 

Thanks

**Comment by jacobbednarz** [comment]
Heya! 

It was a combination of me cleaning up stagnating issues I opened and no longer using the product. 

Happy for you folks to keep this open if it's of use to you!

**Comment by astoilkov** [comment]
An option to change the line width is now included in the latest version of Caret so closing this issue now.
