### ISSUE TITLE
Middle click both scrolls and pastes

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#340]
I'm not sure this is consistent only on Linux, where the middle-click will usually paste the content at cursor, but on this platform a middle-click (or keep pressing the middle button) causes Caret to _scroll the editor view_ until it's stopped, by middle-clicking again or by depressing the button: **then it will paste** the content either at the _initial cursor position_ (where initially the middle button was clicked or pressed) or (sometimes) by _replacing the selection_ that in the meantime got created while scrolling.

Canceling the action can be done by <kbd>ESC</kbd>, this also helps in actually working around it.

Hope i was able to explain the thing o_O

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 2.1.2 release.

Closing this issue. Thanks for reporting.
