### ISSUE TITLE
Selecting word by double-click remains partially unselected if the selection is then resized

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#343]
On the Linux platform, performing a double-click for selecting the starting word and then dragging the mouse to expand/move the selection will cause Caret to partially unselect the starting word, making it difficult to perform selections this way.

You can see this clearly in the video: please ignore the triple-click selection on the `odio` word of the paragraph, this was unintended :)

![selection-double-click](https://cloud.githubusercontent.com/assets/819314/25672254/11db905e-3033-11e7-9eb6-ad17403cde7a.gif)

**Comment by pslobo** [comment]
This is related to https://github.com/careteditor/caret/issues/207 and as I've said there, it would as though this is a Linux/Windows only feature since I cancer replicate said behaviour on any text editor on MacOS (at least not with the trackpad. I'll need to try with a mouse when I can).

**Comment by manuelbua** [comment]
This also has been fixed, thanks!
