### ISSUE TITLE
Feature Request: Open any file from command line

### ISSUE THREAD

**Issue by aerze** [careteditor/caret#345]
Similar to opening any file for vscode or sublime
I'd like to be able to open the editor from the command line
```sh
caret ./readme.md
```

Currently I can alias the application, but not pass it any files
```sh
open -a Caret
```

**Comment by manuelbua** [comment]
I agree, this would be much practical :+1:

**Comment by aerze** [comment]
OHHH SNAP you _can_ do this
so I was trying to pass args like this
```sh
open -a Caret --args notes.md
```

but you have to skip the args
so like this 
```sh
open -a Caret notes.md
```

**Comment by aerze** [comment]
Assuming you're on mac and Caret is just in your Applications directory
you can add `alias caret="open -a Caret"` to your profile and just use `caret notes.md`

**Comment by manuelbua** [comment]
It never worked for me: it does reopen the last one opened file, but calling from command line doesn't really work , i'm on Linux btw..

**Comment by aerze** [comment]
¯\_(ツ)_/¯ reopen the issue?

**Comment by manuelbua** [comment]
But does it really works on a Mac? Sometimes it just reopens the last file, else just a blank one: yes would be cool to reopen thanks!

**Comment by pslobo** [comment]
I know this has been closed, but just to set the record straight, the best way to alias this isn't to `open -a caret` but rather `alias caret='/Applications/Caret.app/Contents/MacOS/Electron'`

This works consistently across all my testing.
