### ISSUE TITLE
Bug: Multiline selection

### ISSUE THREAD

**Issue by onury** [careteditor/caret#346]
Hold <kbd>ALT</kbd> and drag cursor a few lines down or up. Selection goes crazy ⚡️

**Comment by manuelbua** [comment]
What do you mean by _crazy?_ For me it activates multirow selection mode and it's pretty handy :smiley:

**Comment by onury** [comment]
It doesn't follow the lines I select. e.g. I aim to select 2 lines, it selects like 50 lines towards the bottom.

I'm on a Mac. Maybe a bug in Mac version.

**Comment by manuelbua** [comment]
Oh that could be it.

**Comment by astoilkov** [comment]
Hi,

We are aware of this bug and have fixed it internally. Expect a release soon.

Thanks for taking the time to report. We really appreciate it.

**Comment by pslobo** [comment]
Working fine for me, thanks!

**Comment by astoilkov** [comment]
Great. Closing this issue then.

**Comment by onury** [comment]
@astoilkov  It's not working properly within tables. Try dragging down on a table.

<img width="655" alt="drag" src="https://cloud.githubusercontent.com/assets/3665990/25961687/d055ecd6-3683-11e7-9044-c838b89ec28f.png">

**Comment by pslobo** [comment]
@astoilkov @onury It's working just fine for me. What is happening there is a visual glitch due to you having code there, but if you look at this example, the selection is adhering to the correct position (not visually though)

![screen shot 2017-05-11 at 18 01 35](https://cloud.githubusercontent.com/assets/1452095/25961943/e48685e0-3673-11e7-9aa8-de4b3aae9732.png)

**Comment by onury** [comment]
Below is the **correct** behaviour:  

![correct](https://cloud.githubusercontent.com/assets/3665990/25963657/bd420416-368a-11e7-9d29-64a3c4547c30.gif)

But when there is a code block, the selection on that line jumps and not in sync with the other lines:  

![incorrect](https://cloud.githubusercontent.com/assets/3665990/25963661/c2b10aa0-368a-11e7-82e9-5714f3737a79.gif)
