### ISSUE TITLE
Opening a file as an argument from the linux command line doesn't always open the specified file

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#347]
Whenever i'm at the console, trying to open Caret with a file as an argument doesn't always open it: sometimes it works, sometimes it open the last recently closed file, sometimes just a blank document is presented.

I can't test this on a Mac or a Windows machine, but it looks like this works fine on Mac via the `open -a Caret notes.md` syntax, taken from issue #345 (now closed); the syntax i use on my Linux console is the classic one ie. `Caret README.md`.

**Comment by pslobo** [comment]
Can you see to what caret is aliased? On my Mac I have it aliased to `alias caret='/Applications/Caret.app/Contents/MacOS/Electron'` and I can consistently open a filed passed to it via the command line.

**Comment by manuelbua** [comment]
Oh i just found out what the problem is, will close this issue since it's related to Arch packaging: they include a `/usr/bin/Caret` that invoke the installed binary at `/opt/caret/Caret` but without passing any parameters.

Sorry for the fuss, it's an ArchLinux packaging-related thing.

**Comment by manuelbua** [comment]
For any other ArchLinux user out there, just for your reference, i opened an issue at the AUR [here](https://aur.archlinux.org/packages/caret-bin/#comment-595016).
