### ISSUE TITLE
Detect changed files on focus/Option to "reload" file

### ISSUE THREAD

**Issue by jjarava** [careteditor/caret#35]
HI!

I'm starting to use Caret, and I've run into the issue a couple of times... I have all my notes in a /Notes folder and I use nvALT to edit/view/search them... 

The problem appears when I change something in a "note" that I have been working on Caret, and then go back Caret and want to keep working there's no prompt or option to "reload" the content... If I want to reload the doc I have to either close and open, or open a different document and open the one I want (using ⌘-T to go to the Folder view and selecting the *same* file I have open doesn't reload).

And if I forget to do it, and save, then I overwrite the changes I had done in the file - not good either... 

I think that "change detection" and "autosave" (I've seen it's been reported as issue #17), are two important features to really make Caret shine.

**Comment by astoilkov** [comment]
We have already planned both of these. If everything according goes according to plan you will see "change detection" some time next week and "autosave" in the 2.0 release.

Thanks for your feedback.

**Comment by astoilkov** [comment]
We have implemented file monitoring and automatic reloading of files. You could expect an app update soon.
