### ISSUE TITLE
Punctuation interferes with spell checking

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#351]
Originally reported in https://github.com/careteditor/caret/issues/319#issuecomment-297636967 but this probably deserves an issue on its own. There are two issues I can report:

## Incorrect spell checking

Sometimes, Caret thinks that a punctuation after the word is part of it. I had a text "bla bla config, bla bla" (note the comma), I've added the word "config" into dictionary but actually, "config," was added:

![image](https://cloud.githubusercontent.com/assets/101152/25472910/93a0817c-2b2d-11e7-9838-b0d44bf4216e.png)

Now, the "config" word is still unknown and marked as incorrect.

## Incorrect correction

Before:

![image](https://cloud.githubusercontent.com/assets/101152/25820321/2444261e-3431-11e7-8c61-faf1b5c47139.png)

Accepting correction:

![image](https://cloud.githubusercontent.com/assets/101152/25820341/3ba0963a-3431-11e7-827b-0e126fcf0baf.png)

After:

![image](https://cloud.githubusercontent.com/assets/101152/25820354/4527c052-3431-11e7-95b3-4ce70374f7d3.png)

(the comma is gone).

**Comment by astoilkov** [comment]
This is now fixed in the new [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue. Thanks again Borek!

**Comment by borekb** [comment]
You're on a roll :)
