### ISSUE TITLE
Windows: Problem with code in list item

### ISSUE THREAD

**Issue by archfrog** [careteditor/caret#353]
This simple line in a list makes Caret go bonanza and display characters that you cannot remove again, even if you quit the app and restart it.  I'm not sure it is enough to copy and paste the example, you probably have to type it in manually.
``´
...
10. _What is the purpose of `myfunkyfield`?_ s
`´`
I cannot move past the last character of `myfunkyfield` so I cannot remove the 's'.  The solution for now is to write the line as follows:

1. Enter "_What is the purpose of ?_".
2. Move the cursor to the question mark.
3. Enter the string "`myfunkyfield`".

The problem seems to be that Caret gets confused when there are code quotes in a list item.

**Comment by astoilkov** [comment]
Hi @archfrog,

I can't seem to be able to replicate the problem. I am doing exactly what you have described as steps to replicate. Does the issue happen every time? Is it possible for you to send us a video or recorded gif of the behavior?

Thanks in advance.

**Comment by archfrog** [comment]
I'm not sure if the problem can only be recreated on Windows.  I did this to recreate it:

1. Open a new file with Caret v2.0.11 (using `File -> New`).
2. TYPE `1. `.
3. TYPE an underscore.
4. TYPE this text: `What is the purpose of `.
5. TYPE a back tick.
6. TYPE `code code`.
7. TYPE a back tick and notice that the cursor places itself before the back tick you just typed (things are beginning to go wrong).
8. TYPE `? word word` (the cursor is now positioned before the last d in the last word).
9. Move the cursor to `?` and use `Del` to TRY to delete it.

In my end, the `Del` key the first w of the first word and the question mark stays unchanged.  After this, the line editing gets more and more confused.

I hope this helps.  I don't know how to record video and/or GIFs just yet :-)

**Comment by pslobo** [comment]
Ah, you hadn't mentioned the underscore before I think. This is probably related to https://github.com/careteditor/caret/issues/306 and should be fixed in the next version if I'm not mistaken.

**Comment by archfrog** [comment]
My mistake :-)  Great, feel free to close this issue, if that's what you do with duplicates.

**Comment by astoilkov** [comment]
Indeed, this is a duplicate. I will close this issue later today when we release Caret 2.1

**Comment by astoilkov** [comment]
This is now fixed. Closing this issue.

Thanks for reporting.
