### ISSUE TITLE
Inverted colours/contrast for dialogs

### ISSUE THREAD

**Issue by pslobo** [careteditor/caret#356]
Seems that the changes introduced to create better contrast for modal dialogs is also affecting certain other areas. When using the command palette of navigator, the "matched" text is dimmed whereas the rest is highlighted. It should be the other way around.

![screen shot 2017-05-11 at 13 41 06](https://cloud.githubusercontent.com/assets/1452095/25949537/ca6a384c-364f-11e7-9dae-882754d55428.png)
_app should be highlighted_
or

![screen shot 2017-05-11 at 13 43 38](https://cloud.githubusercontent.com/assets/1452095/25949561/db3d57e4-364f-11e7-83f4-2955a453e70f.png)
_ne should be highlighted_

**Comment by erusev** [comment]
Ah, that's bad, will fix it later today or tomorrow

**Comment by pslobo** [comment]
That was a fast fix indeed. Working fine now 👍
