### ISSUE TITLE
Copying selection by right click breaks selection and will copy one portion

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#359]
<kbd>Right-clicking</kbd> when a selection is in place will break that selection on <kbd>right-click-down</kbd> and choosing "copy" will both:
- copy part of the original selection, or the new selection done at <kbd>right-click</kbd> losing the original one if <kbd>right-clicked</kbd> **outside** the selection)
- will act as the <kbd>left-click</kbd> button was being kept pressed, starting to select from the <kbd>right-click</kbd> position, following the cursor until <kbd>left-click</kbd> is pressed: pressing <kbd>ESC</kbd> will appear to work, as keyboard input will deselect any area and accept input as normal, but moving the mouse cursor will make the odd behavior to kick-in again.

Currently, only by <kbd>left-clicking</kbd> will let you quit that behavior and make the editor usable again.

![test](https://cloud.githubusercontent.com/assets/819314/25973691/73e3b20e-36a5-11e7-9f9a-848098433992.gif)

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 2.1.2 release.

Closing this issue. Thanks for reporting.
