### ISSUE TITLE
OSX - Issues with spellcheck? Support for non-english language docs?

### ISSUE THREAD

**Issue by jjarava** [careteditor/caret#36]
I'm using Caret on OSX, and when opening my test documents (in Spanish), I get lots of "underlines" and I get prompted to correct the word and the options than I'm presented are English words.

When opening the same doc in other apps (nvALT and TextWrangler, for example), I don't have any issue with Spellchecking - I get suggestions (in Spanish) when I miss-type a word, and that's it... and whe the document is in English, the system figures it out and acts accordingly.

I haven't configured/changed anything in the system for the other apps, but I was wondering if there's some config to be done in Caret to recognise Spanish (or non-English) text

Thanks

**Comment by erusev** [comment]
Thanks for reporting this, we'll see what we can do.

**Comment by astoilkov** [comment]
We have implemented automatic language detection and fixed the observed problem. You could expect an app update soon.

Thanks you for the reported issues.
