### ISSUE TITLE
Option for more subtle spell checking style

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#362]
Caret 2.1 came with a new spell checking style:

![image](https://cloud.githubusercontent.com/assets/101152/26003126/188907be-3732-11e7-8b81-a614fdabf36b.png)

It is quite aggressive to my taste, especially if I have more words that are not in a dictionary. This is a good candidate for configuration option, IMO: some people, when writing English prose for example, will want clearly visible spelling mistakes, in more technical documents, the red background is too distracting.

**Comment by astoilkov** [comment]
We totally agree. We will see what we can do.

**Comment by astoilkov** [comment]
Closing this issue as we changed the styling of misspelled words.
