### ISSUE TITLE
Window scroll position wrong in typewriter mode after embedded image

### ISSUE THREAD

**Issue by netmasteroc3** [careteditor/caret#364]
I'm seeing a problem where Caret improperly calculates the scroll position when using typewriter mode after embedding an image in the document.

What I expect to see is the line with the caret positioned in the vertical center of the window.

What I am seeing is the line with the caret being positioned at the bottom or below the bottom of the window. 

Steps to reproduce:
1. Create a document
2. Turn on typewriter mode
3. Add an image to the document.
4. Position the caret below the image to continue typing.

I'm running Caret 2.1.2, the behavior exists in both the Windows version (tested Win 10) and the Mac version (tested on 10.12.4).

Version 2.1 added inline image rendering in the editor mode (as opposed to preview mode), and it appears that the calculations being done to center the active line in the viewport are not taking into account the height of the inline images when calculating where to set the scroll position. As a result, typewriter mode scrolls to a position higher in the document than it should.

**Comment by astoilkov** [comment]
Hi @netmasteroc3,

Thanks for reporting. We are starting work on this issue. Expect a fix soon.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 2.1.3 release.

Closing this issue. Thank you for reporting.
