### ISSUE TITLE
Styling of subsequent paragraphs of multi-paragraph footnotes and list items in editor incorrect

### ISSUE THREAD

**Issue by netmasteroc3** [careteditor/caret#368]
Markdown/Caret supports multiple paragraphs in elements such as footnotes or list items by indenting the subsequent paragraphs by 4 spaces. Caret's markdown engine definitely supports this convention as it properly renders the output of a multi-paragraph footnote or list item. However, the styling of the text in the editor doesn't appear to be special cased to support styling this properly.

![styling](https://cloud.githubusercontent.com/assets/28659714/26028905/4bc69716-37f7-11e7-8a2c-894850c18bf8.png)

There are two lines that are improperly styled/displayed in the above image. 

The line "Code in pp 3" should be styled as a code block as it's preceded by 8 spaces of indention; 4 to make it a paragraph in the list and 4 to make it a code block. 

The line "Second paragraph of foot note." should be styled the same as a footnote as it's preceded by 4 spaces which should be treated as a paragraph continuation of the footnote declaration ahead of it.

To potentially complicate things further, with nested lists, the indention for subsequent paragraphs remains at 4 spaces, not 4 spaces lined up with the list level.

Caret: 2.1.2
OS: Windows 10, Mac OS 10.12.4

Cheer's guys, keep up the good work.

**Comment by erusev** [comment]
Thanks for reporting this, we'll see what we can do.

**Comment by erusev** [comment]
This is fixed now, we'll release an update later next week.

**Comment by astoilkov** [comment]
This is now fixed in the new Caret 4.0 Beta update available [here](https://caret.io/4beta/).

Closing this issue. Thanks for reporting.
