### ISSUE TITLE
Caret's vs. native context menu

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#369]
Interesting, didn't find out this earlier but there are actually two context menus, one when I right-click:

![image](https://cloud.githubusercontent.com/assets/101152/26032549/79985270-3896-11e7-8961-033e0a7021be.png)

And one when I Ctrl+Space:

![image](https://cloud.githubusercontent.com/assets/101152/26032551/8ba4add8-3896-11e7-9194-715da0556d91.png)

I can even trick it to display native-like items:

![image](https://cloud.githubusercontent.com/assets/101152/26032554/a73a0714-3896-11e7-95c3-526e30788c4a.png)

Not sure how I've done that though, it was just a few random key presses and right-clicks.

This is not really an issue, just posting it as I found it interesting. Is this the intended behavior?

**Comment by astoilkov** [comment]
@borekb - Yes. This is intended. Initially it was the custom context menu all the time. However, we discovered that it feels unnatural for most users and also makes it feel like it isn't a native app.
