### ISSUE TITLE
The operation of the Undo and Redo seems incorrect.

### ISSUE THREAD

**Issue by muukii** [careteditor/caret#37]
The operation of the Undo and Redo seems incorrect.
Or sentence is increased to or destroyed.

I am very expect to Caret.
Thank you.

**Comment by erusev** [comment]
Can we give us the steps that we could follow to reproduce the issue?

Thanks.

**Comment by astoilkov** [comment]
What version of Caret are you using? You could try updating to 1.0.2 and see if the issue still persists.

**Comment by astoilkov** [comment]
Hi,

We fixed the issue. You could expect an app update in the upcoming weeks.

Thanks for reporting.

**Comment by muukii** [comment]
Thank you!
