### ISSUE TITLE
Selection and cursor in headings is difficult due to being offsetted 

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#370]
As in the subject, i tried this on Linux ~~and OSX and the result is the same~~: the cursor and the selection are being offsetted by some pixels, the more you write on the line the more the offset will be, until you can move the caret halfway the characters.

See the attached gif for some tries, while using the following text:

```markdown
# Translated URLs containing non-ASCII characters won't be set active in the menu when visited
```

Put that in a file and you should notice the behavior.

![output](https://cloud.githubusercontent.com/assets/819314/26059182/17e8a55c-3981-11e7-8ae0-c440781f6055.gif)

Note how, toward the end of the video, i try to select the uppercase `i` of the word `non-ASCII` and although it looks like it's highlighted, it will not be overwritten by entering new characters.

**Comment by astoilkov** [comment]
Hi @manuelbua,

I tried replicating the problem but without success. You can see the behavior on my side using Caret 2.1.3:
![](http://g.recordit.co/w9iqrRzNot.gif)

**Comment by manuelbua** [comment]
Mmm i tried on a Mac as well with another document and i get the same behavior with `2.1.3` as well (i forgot to mention that, i was using the latest as well).

This also happens while writing, let me try another time and will take a video as well.

**Comment by astoilkov** [comment]
Does this happen every time or just sometimes?

**Comment by manuelbua** [comment]
Yes, this happens every time, even while writing:

![output](https://cloud.githubusercontent.com/assets/819314/26062470/2af7a7f6-398b-11e7-8294-d5145e6e8c15.gif)

Note that the flickering or the fast-moving cursor, for some reason, is related to the screencast tool working bad.

**Comment by manuelbua** [comment]
Sorry, the tries i did on the Mac weren't actually performed on a Mac, i asked a friend to try but he didn't do it in the end.. ;(

**Comment by astoilkov** [comment]
I also tried it on in Ubuntu 14 and everything works fine. Does this started happening when you updated or it was always been a problem? Maybe you could try to uninstall and install the app.

**Comment by manuelbua** [comment]
I think i noticed this when the new editor theme come out: so i initially noticed this on `2.1.1`, this started happening on all my ArchLinux machines.

I waited to report this because i think noticed there was an issue describing the same problem.

This evening i can try with the `Kali` distribution i'm also using, that is a debian-based distro featuring Gnome3 as well.

**Comment by pslobo** [comment]
I just tried this on a mac and I can't replicate it. Running in Fedora I can replicate this. Thinking it may be related to font. What font are you using @manuelbua? On Fedora I'm using Roboto, whereas on the Mac I'm using another, other that the default.

**Comment by manuelbua** [comment]
I'm currently using the Roboto fonts packaged by Arch in the `community` repo: it's called `ttf-roboto` version `2.136-1`.

This is the [zip file](https://github.com/google/roboto/releases/download/v2.136/roboto-hinted.zip) that get installed.

I could try to reinstall them and report back as well.

**Comment by manuelbua** [comment]
I reinstalled them, but the problem persist.

**Comment by manuelbua** [comment]
FYI i also tried on the **kali** distribution as well and the problem is the same.

**Comment by astoilkov** [comment]
@manuelbua Have you tried latest version of Caret to see if this issue is fixed there?

**Comment by manuelbua** [comment]
Hi @astoilkov, it looks like it's working fine on my Arch installation! Need to try it out on Kali but i'm confident this is now working fine, great work!

**Comment by astoilkov** [comment]
What about https://github.com/careteditor/caret/issues/373?

**Comment by manuelbua** [comment]
I can confirm this also works fine in Kali.
