### ISSUE TITLE
Spaced bold font offsets the visual selection

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#373]
In some cases, having a paragraph containing some spaced, bold words, will cause selections performed on the characters following the bold ones to be visually offsetted, and not reflecting the actual selection.

This doesn't always is the case: for instance, the following text will cause the problem:

```md
**Do Dododod** abc def ghi jkl mno
```
This one will not cause any problems:

```md
**This** is another test. This is another test. This is another test. This is another test.
```

But adding a single space and more bold characters, appending to the `**This**` string, will cause the odd behavior again:
```md
**This isisisis** is another test. This is another test. This is another test. This is another test.
```

![test](https://cloud.githubusercontent.com/assets/819314/26118161/2996f022-3a69-11e7-9b48-115cf0dfbb8c.gif)

This Markdown code, instead, will cause to interefere with the selection from mid-phrase on; note in the video how double-clicking a single word is offsetted when performed on the right, while it's fine if at the left:

```md
This is another test. This is **This isisisis** test. This is another test. This is another test.
```
![test2](https://cloud.githubusercontent.com/assets/819314/26118355/e01785be-3a69-11e7-9ced-cb828084b2b9.gif)

Note that the `---` separators in the video aren't needed to replicate the problem, they were part of my original test case and only forgot to remove them.

**Comment by astoilkov** [comment]
@manuelbua - does this happen if you change the font in the preferences?

**Comment by manuelbua** [comment]
I did a couple of tries: this never happens with `Roboto` and it will work fine even reverting to `Roboto Condensed`, but i have to NOT close the window and move away from the preferences pressing <kbd>CTRL+,</kbd> again.

As soon as i close and reopen the editor, `Roboto Condensed` will cause the bug, but this never happens with `Roboto` or `Liberation Sans`.

**Comment by astoilkov** [comment]
This seems the same as https://github.com/careteditor/caret/issues/370. There is a problem with the font Roboto Condensed under some Linux based systems. We will investigate further and let you know.

**Comment by manuelbua** [comment]
@astoilkov you are probably spot on: i suspected the same since also adding bold to the heading amplifies the offset as well.

Also, i tried both the `hinted` and `unhinted` versions of the Roboto font family, but the result is the same.

**Comment by BsNoSi** [comment]
I can´t reproduce this on Windows 10 / Caret 2.1.3. Neither with `Roboto`, nor with `Roboto Condenced` or `Liberation Sans`.

> Maybe the used fonts are the reason, that Caret can not heal. Sometimes they are corrupted or incomplete, leading to the described effects.

**Comment by manuelbua** [comment]
It seems this stopped happening on my ArchLinux machines, i didn't switch Roboto fonts or changed settings somewhere, maybe i'm speaking too early but it seems its working fine :)

On Kali Linux, instead, i've to do some more testing since it has some incosistent behavior that i would like to explore more.

**Comment by manuelbua** [comment]
I can confirm that the initial test case is now working fine on my ArchLinux machines, too bad i can't pinpoint what really changed on the OS part since i can't think of something i installed/uninstalled.

I know that Ubuntu had different font rendering from other distros (is this still the case?), but Kali is now Debian-based and i'm not sure what's the difference there: i'm going to test on that platform a bit more and hopefully i can find what's the culprit there.

**Comment by astoilkov** [comment]
Is it possible the 3.0 update fixed it? Can you download a [2.1.3](https://github.com/careteditor/caret/releases/tag/2.1.3) for example and see if the problem exists there?

Thanks in advance.

**Comment by manuelbua** [comment]
Uhmm.. i reinstalled `2.1.3` and it started to exhibit the same problem as expected, so i reinstalled each `3.0.x` version up to `3.0.2`, but the problem is back again and won't go away :(

I also tried deleting the `.cache` but to no avail, the old bug is back nonetheless.

I've found a way to workaround it, it's not great but it works: if i **decrease and increase** the font size, then there will be no problems **as long as the editor is open**, whenever i close it or open another file i need to resize the font again to have it working fine.

**Comment by astoilkov** [comment]
Wow. Sorry for bringing the bug back again. We will keep investigating in order to fix it.

**Comment by manuelbua** [comment]
Nahh now i've found a temporary fix and it's consistent: strange thing that running the old version would cause this, probably Electron is just crazy on its own..

**Comment by manuelbua** [comment]
Unfortunately the workaround does NOT work on Kali Linux, while it works very well on Arch. I had the hope it was going to finally be an usable workaround, but it looks like it's something else 😢

**Comment by astoilkov** [comment]
If you don't have a workaround I suppose you have changed your font in Preferences? You like Roboto and want to write with it?

**Comment by manuelbua** [comment]
I tried switching to Roboto and this also works on ArchLinux, but not on Kali 😱

**Comment by manuelbua** [comment]
I now tried to uninstall Caret from the Kali machine, manually deleted every trace from `.config` and copied my settings back, i'm always using "Roboto Condensed".

Now the Arch workaround is working fine here too, as well as using the Roboto font as a temporary alternative.

While testing the font size workaround, i noticed an interesting thing happening, this may or may not help you to pinpoint the problem, but it's curious: before using the workaround the editor text is wrapping **early** on the right side, while after the workaround it "correctly" wraps the text.

You can notice the different wrapping starting at line 2:

Before workaround:
![before-resize](https://user-images.githubusercontent.com/819314/27649356-d460f5f4-5c31-11e7-80bb-34684ab6a1ac.png)

After workaround:
![after-resize](https://user-images.githubusercontent.com/819314/27649380-e1f29eb6-5c31-11e7-8981-d089a2cf6bf6.png)

**Comment by manuelbua** [comment]
The latest version `3.3.1` looks like this is solved as well: i'm testing on ArchLinux and will test on my Kali installation but this looks very promising, thanks so much!

**Comment by astoilkov** [comment]
Great to hear. I am closing both issues. If you have any problems on Kali do not hesitate to write here so we could reopen them.

**Comment by manuelbua** [comment]
Confirming this works fine on both Arch and Kali Linux.
