### ISSUE TITLE
Maximized window dimensions not state saved in MS Windows when exiting

### ISSUE THREAD

**Issue by netmasteroc3** [careteditor/caret#374]
When closing Caret in on Windows with the Caret window maximized, Caret saves the window's maximized dimensions as opposed to the window's state (maximized) and normal dimensions. When Caret is relaunched its window is given the larger "maximized" dimensions, as opposed to the maximized state.

Steps to reproduce:
1. On a MS Windows machine, launch Caret.
2. Maximize the Caret window.
3. Close Caret.
4. Relaunch Caret

The Caret window will be the full size of the visible screen (actually slightly bigger) but not in the maximized state (maximize button will show a single box not the double restore box). If you maximize Caret's window, it will resize to properly fill the whole desktop (nothing will extend past the screen's boundary). If you restore the Caret window, it will return to the screen filling dimensions.

The expected behavior is that Caret should launch as a maximized window if it was maximized when closed, and clicking restore should return Caret's window to the size of the last non-maximized Caret window.

Windows: 10 version 1607
Caret: 2.1.3

**Comment by te1** [comment]
I have the same problem on Windows 8.1 with Caret 2.1.3

**Comment by archfrog** [comment]
I have a related problem, I think.  I'm using Caret v2.1.3 on Windows 8.1 x64.

I have a monitor that can rotate/pivot.  I use this feature all the time when I write documentation.  I turn my screen 45 degrees and then use the freeware program [iRotate](http://www.entechtaiwan.com/util/irotate.shtm) to rotate my screen using Ctrl-Alt-Left to get Windows to use 1920 as the screen height and 1080 as the screen width.  When I open Caret, it fills out only the top half of the screen.  And there's no Maximize menu item in the Windows menu as Caret believes it is already maximized.  Caret is the only program that I have experienced problems with using iRotate.

I found a great little tool to export Markdown from Word [Writage](http://www.writage.com).  So now I can write my documents in Word, which has superior spell and grammar checking compared to most tools out there, and afterwards export it to a Markdown file that I can preview and finish up in Caret.

**Comment by archfrog** [comment]
I didn't realize that the "Zoom" item in the "Windows" menu meant Maximize.  Maximize works as expected, it is only on the initial startup that Caret doesn't maximize properly.  And I suppose that has been fixed given the `resolved` label on this issue.  Sorry!

**Comment by astoilkov** [comment]
Great to hear that. We indeed have fixed the problem. The fix will be available in the next Caret release.

**Comment by astoilkov** [comment]
The fix is now available in the official Caret release.

Closing this issue. Thanks to all for reporting and helping fix this issue.
