### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by tulu** [careteditor/caret#38]
The following error has occurred:
```
{
    "message": "Uncaught TypeError: Cannot read property 'start' of undefined",
    "line": 5,
    "column": 3010,
    "version": "1.0.1",
    "platform": "darwin",
    "os": "15.0.0",
    "path": "/web/Editor.Spellcheck.js",
    "code": ".start>=s&&(n.start=Math.max(n.start+i,0),n.end=Math.min(n.end+i,r),n.end<0&&(h.splice(a,1),a-=1)),(n.start>=e.start&&n.end<=e.end||e.start>=n.start&&e.end<=n.end)&&(h.splice(a,1),a-=1)},_selectionChange:function(t)",
    "stack": [
        "at Object.EditorSpellcheck._updateRanges (/web/Editor.Spellcheck.js:5:3010)",
        "at Object.<anonymous> (/web/Editor.Spellcheck.js:5:1599)",
        "at Array.forEach (",
        "at Object.EditorSpellcheck._update (/web/Editor.Spellcheck.js:5:1557)",
        "at loopEvents (/web/Events.js:5:229)",
        "at Object.Events.trigger (/web/Events.js:5:527)",
        "at Object.Editor.(/web/Editor.js:5:13781)",
        "at Object.Editor.(/web/Editor.js:5:13293)"
    ]
}
```

**Comment by astoilkov** [comment]
Can you share in what language you were writing when the error occurred?

**Comment by tulu** [comment]
Where I can see that? When I write in Spanish the autocorrect highlights almost everything because it's in English

**Comment by astoilkov** [comment]
Hi @tulu,

We have fixed the spellchecking problem with languages different from English you could expect an app update soon.

Regarding the error being thrown: I have tried to replicate it but without success. Any additional information regarding when it happened and can you replicate it again in 1.0.2 will be highly helpful.

Thanks.

**Comment by tulu** [comment]
Great, thanks!
I don't really know how to replicate it. It happened a couple of times when I double click on a file and there's already a file opened but maybe this is not the problem. I tried right now and worked well...

**Comment by astoilkov** [comment]
Hi @tulu,

We made some changes and improvements to this part of the code. No one have reported the same problem and we didn't receive another crash report for this. I will close this issue and if you experience the same problem do not hesitate to reopen it.

Have a great day.

**Comment by tulu** [comment]
Great, thanks!
