### ISSUE TITLE
Add country preference for spelling check

### ISSUE THREAD

**Issue by lexieheinle** [careteditor/caret#381]
Hello,

I was wondering if you could add a country preference for the "Check Spelling" option. There's several American-British spelling differences that would incorrectly mark a word as misspelled, such as "standardize."

**Comment by erusev** [comment]
Sure, we'll see what we can do.

**Comment by astoilkov** [comment]
We improved our automatic detection of languages and now we detect British english more precisely and autocorrect it.

You could try it and if you still experience a problem we will investigate more.

**Comment by thomas-sittler** [comment]
Still getting problems with British spellings. 
```
formalisation
favour
civilisations
minimising
relativised
```

**Comment by astoilkov** [comment]
@thomas-sittler On what operating system are you using Caret?

**Comment by thomas-sittler** [comment]
Windows 10.

**Comment by astoilkov** [comment]
@thomas-sittler The next version of Caret will include more improvements to the British spelling. I will let you know when we release the next version so you could check if the issue will still persist.

**Comment by jelias** [comment]
Is there not a setting that we could choose our language? Or perhaps Caret could check the System Language and use that as default?

Teaching 'color' and 'realize' to Caret is getting old :/

**Comment by astoilkov** [comment]
We just released a new Caret Beta update which improves the language auto-detection. You can download it from [here](https://caret.io/4beta/).

You could try it out and let me know if you still need a manual setting for the language.
