### ISSUE TITLE
view preferences are not saved

### ISSUE THREAD

**Issue by innaj** [careteditor/caret#383]
when I open the editor and switch to "live preview" with ctrl+R this preference is not saved. When I re-open the editor I get the only editor mode again. 
windows 10.

**Comment by astoilkov** [comment]
We fixed the problem. The fix will be included in the next version of Caret.

Thanks for reporting @innaj

**Comment by astoilkov** [comment]
Closing this issue as it was fixed a long time ago.

Thanks for reporting.
