### ISSUE TITLE
Dictionary lookup doesn't work on MacOS

### ISSUE THREAD

**Issue by ebeloded** [careteditor/caret#388]
Hey guys,

I use [Mac OS built-in dictionary](https://support.apple.com/kb/PH25145?locale=en_US) a lot - to find the right word or a better synonym. Unfortunately, this great functionality is not working in Caret: there is no response to force touch or three finger tap.

Hope you can fix it!

**Comment by erusev** [comment]
We'll see what we can do, thanks.

**Comment by astoilkov** [comment]
Hi @ebeloded,

This is now fixed in the latest Caret 3.3.1 release. Sorry for the delay.

Closing this issue. Thank you for reporting it.
