### ISSUE TITLE
add `Check for Updates` button/option

### ISSUE THREAD

**Issue by jjarava** [careteditor/caret#39]
Hi!

I know that Caret *should* auto-detect when there's a new update pending and prompt to update.

I've created a couple of suggestions/bugs (#36 and #35) that have been marked as fixed and where I'm told that I should expect an update soon... but it's been a couple of days and I haven't got the update notification (I'm still at `Version 1.0.2`).

So I think being able to "force" an update check (as most if not all non-Mac App Store apps in OSX implement) would make a lot of sense

Thanks!

**Comment by astoilkov** [comment]
We agree. We have already planned "Check for Updates" feature.

P.S.: The new update will be uploaded in the beginning of January. This is also why you haven't got that update notification.

**Comment by jjarava** [comment]
Hi!

good to know that the idea was already in the works. 

Also thanks for the info on the update timing; it'll save me from relaunching Caret every few hours "just in case"

Regards and Happy New Year!

**Comment by jjarava** [comment]
Hi!
Any news on the update being posted? Just to stop wondering if I have an issue that prevents my copy from being updated...

Thanks!

**Comment by astoilkov** [comment]
Hi,

We haven't released a new update. The reason is that we are making some big features and improvements and we also want to include release notes in the new update so people can see what are these changes. Sorry for the delay but I hope it will be worth it :). We have also implemented the `Check for Updates` menu item.

I promise to write in this issue and close it when we actually push the new update.

**Comment by jjarava** [comment]
Perfect thanks! Good to have a place to check for changes then!

Looking forward to updates to this thread!

**Comment by jjarava** [comment]
Hi!

Any news of the update?
Thanks!

**Comment by astoilkov** [comment]
Hi,

  - [x] we have implemented all important and hard features
  - [x] we have done some important changes to the UI and design of the application
  - [x] we have moved to GitHub releases for providing updates and distributable files
  - [ ] we need to make final touches and adjustments to the UI
  - [ ] we need to do final testing of all changes

This means that we would probably be able to release the update in the next 7 days if the testing process goes according to plan.

**Comment by astoilkov** [comment]
The 1.1.0 update is now available. You could start the app and wait for the footer to show up. If you have any feedback we are more than happy to hear from you.

Closing this.
