### ISSUE TITLE
CaretSetup.exe (windows trial) blocked by Symantec Endpoint

### ISSUE THREAD

**Issue by estrenuo** [careteditor/caret#392]
When trying to install the Windows trial version, Symantec Endpoint is blocking the install with the following warning:

![error](https://user-images.githubusercontent.com/6818793/27376055-4d74e3a4-5671-11e7-9ef7-c23004f81b2e.png)

**Comment by astoilkov** [comment]
Have you seen this warning for other apps? For example have you ever installed Atom or VS Code?
We changed the certificate we use recently because the previous expired and it will take some time for antivirus applications to flag it as safe.

**Comment by estrenuo** [comment]
No I haven’t seen it for other apps nor did I try to install Atom or VS Code. I will just wait then to see if works later.

**Comment by astoilkov** [comment]
If you want to install Caret you could download an older version containing the older certificate. You could download the 2.0.11 version [here](https://github.com/careteditor/caret/releases/tag/2.0.11).

**Comment by estrenuo** [comment]
That works and it also managed to update to the newer version in place. Thanks.
