### ISSUE TITLE
inline image not showing

### ISSUE THREAD

**Issue by kevindoveton** [careteditor/caret#395]
**problem:** an image is not showing inline when the link is not visible as shown - all other images are working fine - broken image is at bottom of the page 
![screen shot 2017-06-26 at 9 03 48 pm](https://user-images.githubusercontent.com/11331381/27537447-15716c52-5ab3-11e7-8e1a-5d05b1a41521.png)

**expected** (this is shown when scrolled right  to the bottom of the page)
![screen shot 2017-06-26 at 9 03 55 pm](https://user-images.githubusercontent.com/11331381/27537453-1a3bf59a-5ab3-11e7-8a36-0b0ff5d067a8.png)

**Comment by kevindoveton** [comment]
just did a bit more checking, problem is independent of whether the live preview is enabled or not, it was also still present after a close and reopen

**Comment by astoilkov** [comment]
Thanks for reporting this issue. Is it possible you share the file and the image so we could replicate the problem? Have you changed the line width in Preferences?

Thanks in advance.

**Comment by kevindoveton** [comment]
not sure if these are default
```
font: Roboto
fontSize: 15
lineHeight: 1.9
lineWidth: 72
```

https://github.com/kevindoveton/flinders-se1-cheatsheet - file is cheatsheet.md

**Comment by astoilkov** [comment]
We issue is now fixed in the latest version of Caret.

Closing this issue. Thanks for reporting!
