### ISSUE TITLE
Titlebar is now empty, no indication on which file i'm currently editing

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#396]
As in the subject, in Caret 3. since the titlebar is now empty, there is no way to know which file i'm editing and in which path, that was pretty handy:

![no-title](https://user-images.githubusercontent.com/819314/27539474-ff597580-5a7c-11e7-8c07-3d203156234f.jpg)

**Comment by astoilkov** [comment]
You have downloaded a testing version of Caret 3.0 from the releases. We have fixed the issue and uploaded the 3.0 version again. You could try downloading it again and reinstalling to fix the problem.

**Comment by manuelbua** [comment]
Oh man that was **fast**! But i can't find the updated `.deb` package  :)

**Comment by astoilkov** [comment]
Sorry. It wasn't uploaded yet. Can you try now?

**Comment by manuelbua** [comment]
New version fixed it, thanks!
