### ISSUE TITLE
Default sidebar shortcut CTRL+\ not working on Linux

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#397]
The default shortcut `CTRL+\` is not working on Linux, switching it to something else such as <kbd>CTRL+ALT+S</kbd> will make it work.

An odd thing happened while trying to change shortcut: the editor started saying "Error processing the settings, not saved" or something on these lines, but i'm unable to reproduce; i closed Caret and modified the `keyboard-shortcuts.md` file manually.

**Comment by astoilkov** [comment]
You could download 3.0 version again where we fixed the problem. Thanks for reporting.

**Comment by manuelbua** [comment]
This fixed it, thanks!

**Comment by borekb** [comment]
Doesn't work on Windows (using the auto-updated version so hopefully the right one).

**Comment by astoilkov** [comment]
@manuelbua Great to hear.

@borekb It works on our test machine. Are you sure you haven't broken the keyboard-shortcuts.md while reporting the previous bug?

**Comment by borekb** [comment]
I can see 

```
View › Sidebar: Ctrl \
```

in my keyboard-shortcuts.md file. I'm attaching it as a whole.

[keyboard-shortcuts.md](https://github.com/careteditor/caret/files/1105396/keyboard-shortcuts.txt)

**Comment by astoilkov** [comment]
@borekb I used your `keyboard-shortcuts.md` file but still can't replicate the problem. Maybe you could try restarting the app or your computer?

**Comment by borekb** [comment]
I've added a second shortcut:

![image](https://user-images.githubusercontent.com/101152/27591268-711d21c4-5b51-11e7-9ee7-fac30f4179df.png)

Ctrl+H now works but Ctrl+\ still doesn't. Strange.

**Comment by borekb** [comment]
Oh, found it, I've got two backslashes on my keyboard! The one next to Enter works, the one close to bottom left corner (between left Shift and Z) doesn't.

**Comment by astoilkov** [comment]
Can you execute the following code `document.addEventListener('keydown', function (e) { console.log(e.keyCode) });` in your browser and then press the problematic `\` and see what will be logged in the console?

**Comment by borekb** [comment]
The problematic is 226, the one that works is 220.

**Comment by astoilkov** [comment]
Thanks a lot. We fixed the issue. The fix will be included in 3.0.1.
