### ISSUE TITLE
Menu checkbox at View->Sidebar not synced when sidebar closed by clicking outside it

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#398]
Whenever the sidebar is opened, it will close when clicking outside it: this is fine, but when looking at the menubar for the View->Sidebar menu item, the checkbox symbol is not removed and still there, indicating the sidebar is still opened.

**Comment by astoilkov** [comment]
You could download 3.0 version again where we fixed the problem. Thanks for reporting.
