### ISSUE TITLE
Can't invoke Caret more than once, the last instance will wait for the other one to finish

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#399]
I was wanting to open a bunch of files directly from Nautilus and double-clicked a file to open it.

Once it opened i did the same for another one, but the new Caret process just looked like it was hung, but after one minute the old file got closed, while the new one opened instead.

The same thing can be achieved, instead of waiting, by closing the first editor instance: then the new one will open instantly.

As a workaround i can create a new window and drag-and-drop the file from Nautilus.

**Comment by astoilkov** [comment]
This seems to be an Electron issue. I have [logged the problem](https://github.com/electron/electron/issues/9880) and waiting for response on their side.

**Comment by betahat** [comment]
I'm having the same problem on Arch linux (installed from AUR) but I'm unable to create a second window at all.

**Comment by astoilkov** [comment]
@mthomas7 - Isn't it possible through the application menu `Window -> New` (which if not visible could be shown by pressing Alt)?

**Comment by betahat** [comment]
@astoilkov When I have a document open, if I select `Window -> New` I get a blank document, but it's in the same window as the old document, and the old document is no longer visible.

**Comment by astoilkov** [comment]
These issues should be now fixed in the Caret 4.0 Beta release which can be downloaded from [here](https://caret.io/4beta/).

Can you try it and let me know?

Thanks in advance.

**Comment by betahat** [comment]
Works! Though with a weird caveat. The first two times I try to make a new window, it pops up then disappears. The third time, it stays and works perfectly. I tried a few times, and it's consistently the third time that it works. (I love the beta btw - the left hand side with the tabs is really nice!)

**Comment by astoilkov** [comment]
@mthomas7 Can you check what version of Caret Beta are you running `Help -> About Caret`? This looks like an issue we had in `Caret 4.0.0-beta0` which we fixed in `Caret 4.0.0-beta1`.

**Comment by betahat** [comment]
@astoilkov I'm running the beta1 version.

**Comment by astoilkov** [comment]
@mthomas7 There is new `caret-4.0.0-beta2` update that should fix that issues with the new windows.

**Comment by betahat** [comment]
@astoilkov That did it - thank you!

**Comment by astoilkov** [comment]
@manuelbua Did your problem get resolved in the new Beta release?

**Comment by manuelbua** [comment]
@astoilkov Congrats on the new release!

It looks like the originally reported problem is fixed, but i'm not sure the issue i've now is related to this: with Caret closed, double-clicking an `.md` file from Nautilus will open Caret on that file, doing the same with another document will spawn a new Caret window opening the _Welcome.md_ file instead of my document.

Also, doing that from the command line won't help either.

**Comment by astoilkov** [comment]
@manuelbua Do you expect the new file to be opened in a new tab in the same window?

**Comment by manuelbua** [comment]
Eheh was going to ask what the behavior should have been: since tab support is there then i probably would expect to see it opening in a new tab, at least this is what i can see from most editors with tab support such as Geany, SublimeText, phpStorm, etc..

I'm not sure other editors allow to choose that as an option, but i personally don't see the need for having an option for that either: if i really need another separate window then i think i would be opening a new one and dropping a file there.

**Comment by astoilkov** [comment]
We release a new Beta release where the new behavior is opening a new tab inside of the same window.

Closing this issue.
