### ISSUE TITLE
Keyboard Shortcut for Copy as HTML

### ISSUE THREAD

**Issue by benembery** [careteditor/caret#40]
Adding a Keyboard Shortcut for _Edit > Copy as HTML_ would help, as I caret a lot for generating simple HTML documents.

**Comment by erusev** [comment]
Makes sense. We could, perhaps, use <kbd>Cmd</kbd><kbd>Shift</kbd><kbd>C</kbd> for this instead of `Copy as Rich Text`. @astoilkov What do you think?

p.s. I loved that you have used "caret" as a verb.

**Comment by benembery** [comment]
Verb usage was unintentional, but funny in retrospect.

I would be happy with any short cut along those lines.

**Comment by erusev** [comment]
@astoilkov what do u think about this

**Comment by astoilkov** [comment]
I think `Copy as Rich Text` is also important so I suggest making <kbd>Cmd</kbd> + <kbd>Ctrl</kbd> + <kbd>C</kbd> perform `Copy as HTML`.

**Comment by erusev** [comment]
users could use preview to copy rich text using the regular cmd+c so even if we agree that this command is equally important, having a shortcut for it might be less important

also, introducing <kbd>Ctrl</kbd> in shortcuts would be a precedent

**Comment by hkdobrev** [comment]
Regarding the keyboard shortcut, if you are just using shortcuts like <kbd>Cmd</kbd> + <kbd>C</kbd> and <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>, the default mapping to Windows and Linux would be <kbd>Ctrl</kbd> + <kbd>C</kbd> and <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>. However if you include shortcuts such as like <kbd>Cmd</kbd> + <kbd>Ctrl</kbd> + ..., then mapping to Windows and Linux is not so straightforward as you would need to possibly use the super key.

**Comment by erusev** [comment]
@hkdobrev thanks, that's a good point

**Comment by benembery** [comment]
Whilst I agree there is need for commonality between OS users, there are also users migrating from other competitors like MacDown and Mou to consider, both of those apps use <kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd>.

**Comment by erusev** [comment]
@benembery that's a good point as well

**Comment by astoilkov** [comment]
In Caret 2.0 we introduced custom keyboard shortcuts. This will help you set the desired shortcuts.

Closing this issue. Thanks for the ideas and don't hesitate to give us feedback on the new feature.
