### ISSUE TITLE
Links in the preview pane will not open externally but into Caret instead

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#400]
Links such as absolute hyperlinks or filesystem paths will now open **into** Caret, whether they are `.html`, `.txt` or text files in general: images still correctly open in the browser.

**Comment by manuelbua** [comment]
Also, noticed TOC links are working fine too.

**Comment by astoilkov** [comment]
This is again fixed in an updated version of 3.0. You could reinstall it.

Thanks for reporting.

**Comment by manuelbua** [comment]
Hi @astoilkov, it looks like version `3.4.3` has a regression on this and definitely linked `.txt` files will open in Caret all the time instead of an external editor.

Not sure if i should open a new issue on this or just comment here?

**Comment by astoilkov** [comment]
@manuelbua This has actually always worked like that. We open all text and Markdown files inside of Caret and all other file extensions in an external editor.
