### ISSUE TITLE
keyboard-shortcuts.md goes crazy on Ctrl+Z

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#402]
Congrats on the 3.0 release! I'm going to report a couple of issues.

The first is:

1. Open keyboard shortcuts
2. Press Ctrl+Z

I get this:

![image](https://user-images.githubusercontent.com/101152/27589341-6175db22-5b4b-11e7-998e-22dc9e89d699.png)

**Comment by astoilkov** [comment]
This is now fixed in the 3.0.1 release.

Closing this issue. Thanks for reporting.
