### ISSUE TITLE
Revert File > Publish?

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#403]
I tried clicking File > Publish and something very cool happened :) This was on a public document, fortunately, however, what would happen if it was private? Is there a way to delete the published document from your servers? Maybe some sort of warning before the actual publish happens would be useful.

**Comment by borekb** [comment]
But I like where this is heading :)

**Comment by sdvb** [comment]
Additionally, it seems that I can publish the same file twice and it will receive a new unique ID every time. Perhaps if the file is already published the link would be available from the in-app publish menu? 

I'd appreciate a more detailed explanation of how this feature works.

**Comment by astoilkov** [comment]
You could think of `File - Publish` the same way you think of `File - Export to PDF`. Both commands will publish/export the file without taking into account whether the file was already published/exported. The idea behind `File - Publish` is to have a quick and easy way to share a file with a friend/colleague or just save it on a public URL.

**Comment by sdvb** [comment]
@astoilkov Thanks, that helps with understanding.

**Comment by gandalfsaxe** [comment]
How long until the published document expires?

How can considered making a manual delete feature of the published document?

**Comment by astoilkov** [comment]
The published documents never expire and there is no manual delete feature.

The `File -> Publish` feature was actually experimental and will be removed in Caret 4.0.

**Comment by gandalfsaxe** [comment]
Ah ok. What's the reason for removal?

I thought it was convenient. Although I must admit it'd be much more convenient in a form where it would auto update to reflect changes to the document. Luckily there's many other ways to share, including shared cloud folder, GitHub etc. Still curious to why it's being removed?

**Comment by erusev** [comment]
We have a better approach to publishing in mind so we see this one as obsolete and we want to reduce the time we spend to support it.

**Comment by gandalfsaxe** [comment]
Understandable.

Sorry for going off-topic for a second, but what is in store for the near future?

**Comment by erusev** [comment]
Will release 4.0 beta real soon - hopefully, before the end of the month. We've been working on it since August so it's a big release. Will send a newsletter when it's out.

**Comment by astoilkov** [comment]
We have now removed the feature in [Caret 4.0 Beta](https://caret.io/4beta/). We made this decision because we have a better idea for a solution to the problem. Additionally, this feature was not complete and the discussion here showed there is a lot more work on it which will be for nothing after we implement the new idea.

Hope you understand.

Closing this issue.
