### ISSUE TITLE
Go to Heading incorrectly parses document (regression in 3.0)

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#405]
For the attached document, Caret shows only some headings:

![image](https://user-images.githubusercontent.com/101152/27592625-3987e894-5b55-11e7-8cfa-b555323cabbc.png)

[example.md](https://github.com/careteditor/caret/files/1105616/example.txt)

**Comment by astoilkov** [comment]
This is intentional. If you start searching for a particular heading it will show up. However, we have some ideas how we can improve this so I added `enchancement` label to this issue.

**Comment by Tuxii** [comment]
Hi,

It maybe is intentional, but it's annoying nonetheless. I don't see the reasons behind this choice. 
Could you please share your ideas to improve this behavior ? 

Maybe you could make use of the newly introduced (and welcomed !) sidebar to display the headings ?

**Comment by astoilkov** [comment]
Our current idea is to remove the headings popup and replace it with floating(by default) sidebar on the right side which shows the entire document structure. You would be able to optionally pin the sidebar in order to see all your file headings all the time.

**Comment by borekb** [comment]
Less sidebars please, stay focused on the text :) I think the 2.x approach to headings (even 3.0 although the UI is slightly more confusing) was fine, it is similar to "navigate to file symbol" experience in IDEs, very natural for me once you learn the shortcut.

**Comment by EnCey** [comment]
Not an improvement for people with large documents that relied on the "Go to headings" popup to quickly locate something or get an overview of their documents :/ 

Is the new sidebar coming in the near future or is it only just an idea at this point? 
If the latter, then maybe the "Go to headings" popup can be enhanced in the interim to show all headings again? Since the search is working you seem to have them all available anyway

**Comment by erusev** [comment]
This is fixed now (3.1) - Go to Heading now lists all headings.

In addition, we've introduced a Headings sidebar that should be more convenient to use is some situations.

Feedback on both is very welcome.

**Comment by borekb** [comment]
Both are great!

One thing I noticed (which I think is new) is that the heading text is now selected by default after navigation. I preferred the old behavior.

**Comment by astoilkov** [comment]
@borekb Do you mean that after hitting `Enter` the selection wraps the entire heading text? If this is what you mean this is the same behavior from 2.0 release. Do you remember a different behavior?

![image](https://user-images.githubusercontent.com/884810/27771530-c2d7fb8c-5f58-11e7-9dda-93292588a13e.png)

**Comment by borekb** [comment]
Yeah, I meant Ctrl+G and press Enter. I didn't realize it always used to wrap the text :)

**Comment by astoilkov** [comment]
We changed this behavior maybe 4 months ago so it is:
 - easier to see where the selected heading is
 - easily navigate to the start or end of the heading using left or right arrows

I am closing this issue as it is now resolved.
