### ISSUE TITLE
Long block-level math expressions $$$ ... $$$ do not scale

### ISSUE THREAD

**Issue by thomas-sittler** [careteditor/caret#406]
For example:

```
$$$
F=\frac{\frac{RSS_r - RSS_u}{k_u - k_r}}{\frac{RSS_u}{n-k_u}} \land H_0 \rightarrow F \sim F(k_u - k_r, n - k_u)
$$$
```

results in 
![image](https://user-images.githubusercontent.com/14138935/27594648-4445e54a-5b52-11e7-86b4-1cdd6bdd35a9.png)

**Comment by astoilkov** [comment]
Do you want expressions that have scroll to actually scale down and become smaller in the preview so they can fit the available space?

**Comment by thomas-sittler** [comment]
it should be smaller in general. in normal latex, block-level math is only slightly bigger than inline math.

e.g.:

![image](https://user-images.githubusercontent.com/14138935/27597069-35e15a64-5b59-11e7-8287-06e898b5a16b.png)

```
inline math: $F=\frac{\frac{RSS_r - RSS_u}{k_u - k_r}}{\frac{RSS_u}{n-k_u}} \land H_0 \rightarrow F \sim F(k_u - k_r, n - k_u)$

block level math:
$$F=\frac{\frac{RSS_r - RSS_u}{k_u - k_r}}{\frac{RSS_u}{n-k_u}} \land H_0 \rightarrow F \sim F(k_u - k_r, n - k_u)$$


inline math: $\sum_{i}^t F_i $

block level math:
$$\sum_{i}^t F_i $$
```

**Comment by erusev** [comment]
@thomas-sittler 

Based on your feedback, we reduced the size of math blocks.

We'll release the update sometime next week.
