### ISSUE TITLE
Titlebar doesn't indicate the saving state of a file with the asterisk sign anymore

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#407]
Before 3.x the titlebar was showing an <kbd>*</kbd> asterisk sign whenever a file had **not** been saved, that was pretty handy and it would be cool to have it back :grin:

**Comment by borekb** [comment]
It does show an asterisk for me (v3.0.0).

**Comment by astoilkov** [comment]
@manuelbua We fixed this in 3.0.2. Thanks for reporting.

@borekb This issue was only under Linux. This is why you weren't able to reproduce it.
