### ISSUE TITLE
Incorrect in Korean

### ISSUE THREAD

**Issue by ChangJoo-Park** [careteditor/caret#412]
https://vimeo.com/223384597

see above video. 

안녕하세요 is "Hello" in English.

version : 3.0.1 

before I update 3.0.1 It didn't happened.

**Comment by astoilkov** [comment]
Hi @ChangJoo-Park,

We have made a fix related to the Korean typing. Can you update Caret to 3.0.2 and see if the issue will be fixed for you?

**Comment by ChangJoo-Park** [comment]
@astoilkov It works well 👍 
Thank you :)
