### ISSUE TITLE
Sidebar not useable Shortcut in german layout

### ISSUE THREAD

**Issue by slamprecht** [careteditor/caret#413]
The UI says that Shortcut to invoke Sidebar ist CMD+\ , so Command and Backslash. Thats not useable on a mac with german keyboard. To produce this you have to hit:

cmd+shift+option (alt)+7

**Comment by astoilkov** [comment]
Hi @slamprecht,

You could change the shortcut to a different one that is easier to press from the Keyboard Shortcuts. Additionally, in the next version we will also make `Cmd+1` to open the Sidebar.

Do you have other software that have this shortcut assigned to something? Have you seen a solution to this inconvenience in other programs?

Thanks for the feedback.

**Comment by BsNoSi** [comment]
My `keyboard-shortcuts.md` show `CTRL \` as shortcut, in menu `CTRL ^` is displayed, and it works that way on my (Windows) keyboard.

After update, `CTRL \` was displayed as shortcut but did not work. After some modifications in the shortcuts-file, without changing the sidebar settings there (still `CTRL \`) it was displayed as described.

I can not reproduce this.

**Comment by slamprecht** [comment]
The new shortcut cmd+1 works. tnx

**Comment by astoilkov** [comment]
Great to hear. Closing this issue then.
