### ISSUE TITLE
Wrong Cursor Position After Soft Hyphen

### ISSUE THREAD

**Issue by BsNoSi** [careteditor/caret#414]
Adding a soft hyphen ("&shy­;", #­173) leads to wrong cursor position afterwards. It seems as if the space is added, "shy" would require, if it is displayed.  This is new in version 3.02, in previous I could not see this effect.

This is a very strong error, because it is impossible, to position the cursor as desired.

```
Copy this line, it con­tains some (sense­less) soft hy­pen to re­pro­duce the ef­fect.
```

**Comment by astoilkov** [comment]
We fixed this problem in the latest Caret 3.1 release.

Thanks for reporting. Closing this issue.
