### ISSUE TITLE
Scrollbar rendering incorrectly (doubled) Win10/Caret 3.0.2

### ISSUE THREAD

**Issue by netmasteroc3** [careteditor/caret#416]
After either maximizing or full screening (f11) caret, and restoring it to a windowed state, Caret draws 2 scroll bars along the right side of the window as in the attached image below.

System: Windows 10 v. 1703 build 15063.447 (64-bit)
Caret: 3.0.2

![caret-scroll](https://user-images.githubusercontent.com/28659714/27751075-9cc2f98a-5da8-11e7-9b48-40d996607cd9.png)

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 3.1 release.

Thank you for reporting. Closing this issue.
