### ISSUE TITLE
Bug: cmd-t shows all files but not right directories

### ISSUE THREAD

**Issue by slamprecht** [careteditor/caret#418]
Sorry to say. But I was to enthusiastic about it. 

I do: 

1. Open a md file in directory 1: Cmd-t shows me the files in it. Not only some, with arrows keys i can see all of them.
2. Open another document in directory 2. Let document 1 open in caret. cmd-t shows me list of files but not from the directory in which document 2 is saved, but the folder of document 1

So Caret didn't follow my folder change. IMHO a bug and another argument to make a rollback to old functionality. That worked reliable. 

Regards
Stephan

**Comment by slamprecht** [comment]
To make it more clear:

1. Screenhot  Look at path. I open this file in caret.
2. Screenshot: Its open and i hit cmd-t. Look at path. Thats the files from a different directory
![caret01](https://user-images.githubusercontent.com/1213017/27769504-87855660-5f2b-11e7-9655-eb1bfafa46f4.jpg)
![caret02](https://user-images.githubusercontent.com/1213017/27769506-8cfccd8a-5f2b-11e7-9392-01418a8a97d9.jpg)

**Comment by erusev** [comment]
We'll fix this in the next release sometime next week.

Thanks for reporting it.

**Comment by astoilkov** [comment]
This behavior has now been changed in Caret 3.2.

Closing this issue. Thanks for reporting.
