### ISSUE TITLE
x86 and x86_64 assembly support for syntax highlighting would be awesome

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#419]
I know i'm a niche, but i would love to see syntax highlighting support for x86 and x86_64: currently i'm using **Sublime Text** to open external `.asm` snippets with [this bundle](https://github.com/13xforever/x86-assembly-textmate-bundle) and it works great, but having that in Caret would be great:

![asm_sublime](https://user-images.githubusercontent.com/819314/27771483-76d3acd0-5f4f-11e7-8254-8bffce41cdb8.png)

**Comment by astoilkov** [comment]
@manuelbua Is this the same as https://github.com/careteditor/caret/issues/109? Probably not that niche after all.

**Comment by manuelbua** [comment]
Yes, looks like it: sorry for duping the issue, i searched for `x86` and `x64` and couldn't find anything.

**Comment by astoilkov** [comment]
No problem. I am closing this issue in favor of the first one.
