### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by instanceofme** [careteditor/caret#42]
I'd like to open several documents at the same time

(The shortcut for this could be the widespread cmd-shift-N).

**Comment by erusev** [comment]
We are considering adding the feature.

Could you share with us the use cases that you have for the feature and why using cmd+e or ctrl+tab to navigate recent / open documents doesn't work for these cases.

**Comment by instanceofme** [comment]
Sure!

Multiple copy-paste from a Markdown document to another, editing multiple long documents, dispatching info from a same source into several destination (e.g. I review some design spec and write both user doc and admin doc, or different pages of user doc), comparing two versions of a same doc (with preview in both)… Basically anytime I need to have both documents in front of me; switching only takes me so far, but I give up after two or three switches.

Open recent will lose my scroll position, and rightly so: in the general case of Open Recent, I would **not** want it to remember my scroll position. Plus I can't make multiple comparisons at different places easily, and copy/pasting different parts is a pain too, I ended opening the other doc in TextEdit but that felt wrong.

**Comment by erusev** [comment]
Thanks, that's a great response, I appreciate it.

**Comment by anandrajaram** [comment]
I'd like this too (along with the `Command+ backtick ` to switch between windows

**Comment by erusev** [comment]
We are working on it.

**Comment by astoilkov** [comment]
We are very happy to say we have included multiple windows support in the new 1.2.0 version of Caret.

**Comment by instanceofme** [comment]
Nice, thanks

**Comment by slawek-survicate** [comment]
@astoilkov Is it still available in 4 beta? How can i use it?

**Comment by astoilkov** [comment]
Hi Slawek,

No. We removed multiple windows support in version 4. However, we have ways to achieve a similar behavior using our Files and Folders popup. You can quickly jump to the last file or project you have been in.

**Comment by slawek-survicate** [comment]
Thats deal-breaker for me :/ Most productivity apps support multi window managment. Any chance this will be re-implemented in future releases?

**Comment by erusev** [comment]
Hi @slawek-survicate, could you share your use cases for multiple windows? What are the kinds of things that do that require multiple windows? Thanks so much!

**Comment by slawek-survicate** [comment]
I just like my windows managment. I use Contexts app to switch between multiple website / documents / projects I have opened concurrencly. I it also useful for copy / paste, comparing things, side-by-side etc.

**Comment by erusev** [comment]
Thanks for the quick response! There is a chance to bring back the feature in future releases, but since this would add some complexity to the code we want to make sure that the essential features of the app work well before we do this. I hope this makes sense. Thanks again!

**Comment by slawek-survicate** [comment]
Just to convince you it is important expierience for mac users - there are several one-window  applications have multiple windows support implemented:
- Evernote
- Things (new in 3 version)
- 1Password

1Password and Things have deticated button to separate current document from main window: 
<img width="48" alt="obraz" src="https://user-images.githubusercontent.com/39489552/52716897-1380ed00-2fa0-11e9-8aff-ca0b889f9ee5.png">

Evernote has it hidden more but it is still available. Not to mention all native applications. If you want that native feeling you have to support it. Otherwise it is still webpage-packed-to-app expirience.

**Comment by erusev** [comment]
@slawek-survicate Thanks for mentioning that! It helps a lot. We'll see what we can do.

**Comment by slawek-survicate** [comment]
@erusev btw implementing this please consider put filename into window title so when i switch windows I can see which file i am switching to:

<img width="697" alt="_" src="https://user-images.githubusercontent.com/39489552/52914040-03308100-32c4-11e9-8daa-6725c398ed89.png">

Already bought pro version you guys have done a really good job! Cant wait for multi window support but no pressure there. Just keep being awesome 😎

**Comment by erusev** [comment]
@slawek-survicate That's a great suggestion, thanks!
