### ISSUE TITLE
Table not aligned with bold or italic text

### ISSUE THREAD

**Issue by narnaud** [careteditor/caret#422]
When chaning the style of text in the tables (normal, bold and italic), the tables pipes are not aligned anymore.
See screenshot:
![2017-07-04 21_42_41-the qt company qt marketplace 2017-05-14-estimate md _ c_ nicola](https://user-images.githubusercontent.com/469305/27841456-c70aed90-6101-11e7-8318-e01f48f2a255.png)

Tested on Windows 10 64bits, caret 3.1, default font.

**Comment by erusev** [comment]
This is fixed now, we'll include the fix in the next version that's planned for early next week.

**Comment by astoilkov** [comment]
The fix was included in the Caret 3.2 release. 

Closing this issue. Thanks for reporting.
