### ISSUE TITLE
File navigator (CTRL + T) cuts first two characters

### ISSUE THREAD

**Issue by sdvb** [careteditor/caret#427]
Hi there. It seems that since 3.0 the file navigator cuts the first two letters of the file name (see screenshot).

![image](https://user-images.githubusercontent.com/12238015/27883912-2f48d7f2-6187-11e7-88ad-58f09e9acb84.png)

The first two words should be Sales, and the last Test. 

I'm using Windows 10. Anyone else has this issue?

Edit: better screenshot.

**Comment by astoilkov** [comment]
Hi @sdvb,

We were unable to replicate the issue. Does this happen in every folder?

**Comment by sdvb** [comment]
@astoilkov Yes it's in every folder. At first I thought there might be some sort of character limit for document titles, but it's not the case since I tried with short titles too.

**Comment by astoilkov** [comment]
Can you make a screenshot of your title bar as well so I can see what is your current project folder. Thanks in advance.

**Comment by sdvb** [comment]
Here it is, I had to pixelate some sensitive names.

![image 2017-07-06 at 11 31 26 am](https://user-images.githubusercontent.com/12238015/27926967-1049bcaa-623f-11e7-8724-1d0118103086.png)

Same thing happens if I just create a new folder on the desktop and create some test files in it.

**Comment by EnCey** [comment]
I can confirm this behavior. Ctrl+T also fails to show any files at all in many folders, so I stopped using it in favor of Ctrl+1.
When it does show files, the first 2 characters are missing. When it shows nested files, the letters will be missing in the folder name (the file name will then be complete).
![image](https://user-images.githubusercontent.com/1894528/27949338-a0daee42-62fd-11e7-99d3-c81a6e94d001.png)
Folder name here is "stories"

**Comment by astoilkov** [comment]
Thanks guys. We caught the problem and fixed it. Expect a release early next week.

@EnCey Can you give an example of a file that Ctrl+T have missed? This would help a lot in improving the experience.

**Comment by EnCey** [comment]
@astoilkov I created a new issue #430 via the "submit to GitHub" feature of Caret.

**Comment by astoilkov** [comment]
This is now fixed in the latest version of Caret.

Closing this issue. Thanks for reporting.
