### ISSUE TITLE
Wrong character spacing in tables when using in-place code tags

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#429]
When writing tables, if a row contains some text within the `code` tags, character spacing is wrong and the cursor is offseted.

This code:
```
| test  | test                      |
| ----- | ------------------------- |
| abc   | `deasasdasdadasdadasdf`   |
| `ghi` | 123                       |
```

Produce this output:
![wrong](https://user-images.githubusercontent.com/819314/27984937-69cc28ae-63e2-11e7-8908-dc2335e48a60.png)

**Comment by astoilkov** [comment]
Thanks for reporting this issue. We already fixed it internally. You could expect an update including the fix early next week.

**Comment by manuelbua** [comment]
Thanks!

**Comment by astoilkov** [comment]
This is now fixed in the latest version of Caret.

Closing this issue. Thanks for reporting.
