### ISSUE TITLE
Improve scroll bar on dark mode

### ISSUE THREAD

**Issue by Aerz** [careteditor/caret#431]
Hi, I'm recently using Caret as my main Markdown editor and looks great, but on large files when the scroll bar appears, It doesn't change to "dark mode".

In my opinion, the best colors should be:
- White background --> Transparent background
- Gray scroll --> Dark gray scroll

And I would add:
- Preference option "scroll behavior" with 3 options:
  - Always show
  - Fade In/Out (when scrolls)

Actual:
![](http://i.imgur.com/grQZSm4.png)

Suggested result:
![](http://i.imgur.com/uMlE5P6.png)

Reggards! :)

**Comment by aerz** [comment]
The bug persist. As mentioned in #588
