### ISSUE TITLE
Feature Request: Configurable dimness for the greyed out test

### ISSUE THREAD

**Issue by dracan** [careteditor/caret#433]
I use dark mode, and find it really hard to see the greyed out markdown. It's great that it's greyed out - but it would be really useful to have the greyness configurable, as personally I wouldn't have it greyed out *quite* as much.

**Comment by astoilkov** [comment]
We agree. We changed the grayed out color in Caret 2.2 to be more visible. Have you seen an improvement or you still want to make it more visible?

**Comment by dracan** [comment]
I can barely see it I'm afraid. I can see this being quite an individual preference, so is it worth being a configurable setting?

**Comment by astoilkov** [comment]
We will implement this. However, I will close this issue in favor of https://github.com/careteditor/caret/issues/117 because we will create all types of settings to change editor theme.
