### ISSUE TITLE
3.2.0 update bug on Windows

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#434]
After updating to 3.2.0 from 3.1, I see this:

![image](https://user-images.githubusercontent.com/101152/28066420-20b34be0-663d-11e7-9af5-7a1c3b427611.png)

It's the entire window, "including" minimize, maximize and close buttons.

**Comment by astoilkov** [comment]
Many apologies for that. Our deployment process messed up. Download 3.1 from https://caret.io and the the app will be fixed. The next update to 3.2 will be ok.

**Comment by borekb** [comment]
I kind of liked the minimalism :)

**Comment by astoilkov** [comment]
This is now fixed the 3.2 update show install normally.
