### ISSUE TITLE
Caret is unuseable under mac

### ISSUE THREAD

**Issue by slamprecht** [careteditor/caret#435]
I just got an update of caret on my mac. Sierra 10.12.5. Its TOTALLY broken. Just the editor windows starts. But the app doesn't react on ANY key of keyboard nor is ANY menu item chooseable with mouse. Dunno what u do there. But I had a very good editor. Now its gone.

**Comment by astoilkov** [comment]
Many apologies for that. Our deployment process messed up. Download 3.1 from https://caret.io and the the app will be fixed. The next update to 3.2 will be ok.

**Comment by astoilkov** [comment]
The update to 3.2 should work fine now. Thanks for reporting and again sorry for the inconvenience.
