### ISSUE TITLE
Add to Dictionary doesn't seem to always work

### ISSUE THREAD

**Issue by dracan** [careteditor/caret#437]
Some words I add still have the underline below the work and suggest spellings if I ctrl-space. Basically, as if the 'Add to Dictionary' didn't do anything.

This doesn't seem to always happen, and I can't see a pattern. A word I couldn't get it to add earlier, it's now just worked when I tried it again.

**Comment by astoilkov** [comment]
Hi @dracan,

Thanks for reporting this problem. On what operating system are you running Caret?

**Comment by dracan** [comment]
It's Windows 10 (x64).

**Comment by astoilkov** [comment]
@borekb - Have you experienced this problem?

**Comment by borekb** [comment]
This happens for example if the word is before a comma or a dot, e.g., "this is an example asd." If I add "asd" to my custom dictionary, I think Caret actually adds "asd." and keeps underlining the text.

**Comment by dracan** [comment]
Where's the custom dictionary stored? I'll check mine.

**Comment by astoilkov** [comment]
On Windows we use the native Spell Check API which automatically stores the custom words. We are actually not sure where exactly that data is stored.

**Comment by dracan** [comment]
Looks like it's here ...

    C:\Users\Dan\AppData\Roaming\Microsoft\Spelling\en-GB\default.dic

And looking in that file, it's done as @borekb suggested, and included the punctuation.

    LINQPad
    Docker,
    Kibana
    Docker

**Comment by dracan** [comment]
That latter *Docker* would have been when it fixed itself in my earlier comment in this issue ...
> A word I couldn't get it to add earlier, it's now just worked when I tried it again.

**Comment by dracan** [comment]
I think I did that later on in the document - so that perhaps didn't have a comma next to it.

**Comment by borekb** [comment]
I usually just add a space before the comma or a dot before I add to my custom dictionary but this is definitely a Caret bug.

Also, sometimes, after deleting text, the spell checking spans a couple of lines and reports incorrect results. I think I've reported it somewhere but am too lazy to look it up :)

**Comment by astoilkov** [comment]
We have a bug then. Expect a fix soon.

> Also, sometimes, after deleting text, the spell checking spans a couple of lines and reports incorrect results. I think I've reported it somewhere but am too lazy to look it up :)

Yes. You have. We will fix this too.

**Comment by astoilkov** [comment]
This issue is now fixed internally. The fix will land in the next Caret release. I will close this issue when that happens.

**Comment by astoilkov** [comment]
This is now fixed in the latest 3.2.2 Caret release.

Closing this issue. Thanks for reporting!
