### ISSUE TITLE
Strange rendering artifact

### ISSUE THREAD

**Issue by dracan** [careteditor/caret#439]
On my work machine a particular file is rendering a strange vertical line to the left of the editor window ...

![image](https://user-images.githubusercontent.com/567988/28115075-5d5e3c3a-66fb-11e7-8d16-3e2d28d047c9.png)

I've seen this happen to two different files. It doesn't seem to be the file itself, as if I copy the file to another folder it fixes it. So something must be remembering the absolute path to this file. I've even tried deleting all the folders in the `C:\Users\dan.clarke\AppData\Roaming\Caret` that have the name *cache*, to see if something was being cached there, but it doesn't fix the issue. I can't find any way of removing these rendering artifacts.

**Comment by astoilkov** [comment]
This is supposed to be a Git indication showing that the file has changed. Is the folder where file is a Git project?

**Comment by dracan** [comment]
Oh, I see! I didn't realise Caret did that. Yes, it is in Git - however, there are no pending changes against that file. It still shows that line for the whole file.

**Comment by dracan** [comment]
"it is pushed to the public repository and there are no local changes to the file"

**Comment by astoilkov** [comment]
Do you experience the same problem for other files in the same repository?

**Comment by astoilkov** [comment]
Is this a public repo that we can clone so we can test this?

**Comment by dracan** [comment]
Yep, just tried another file, and it does the same. Unfortunately, it's a not a public repo. I can try it this evening on a public repo though. I'll just create a temporary github repo to test.

**Comment by dracan** [comment]
My Git config is set to have this `core.autocrlf=true`.

**Comment by astoilkov** [comment]
Yes. This sounds possible. We will test different configurations tomorrow. Thanks a lot for the detailed and helpful information.

**Comment by dracan** [comment]
No problem! Thanks a lot for such an awesome app! Also, for the Git integration! That's very cool - I didn't know Caret did that :)

**Comment by astoilkov** [comment]
We replicated the problem and fixed it. We will release a new version of Caret tomorrow.

**Comment by dracan** [comment]
Great work! :) Thank you for such a very fast response and resolution!  :)

**Comment by astoilkov** [comment]
This is now fixed in the latest 3.2.2 Caret release.

Closing this issue.
