### ISSUE TITLE
Display fails to redraw when going from retina to non-retina displays

### ISSUE THREAD

**Issue by nogorilla** [careteditor/caret#44]
When moving Caret.io between a retina and non-retina screen, redraw fails to complete resulting in application having incorrect resolution

going from retina to non-retina display:
![caret_io - retina to non-retina](https://cloud.githubusercontent.com/assets/1786677/13030980/105f6af0-d28a-11e5-8e24-c7e5b9119130.png)

going from non-retina to retina display:
<img width="1163" alt="caret_io - non-retina to retina" src="https://cloud.githubusercontent.com/assets/1786677/13030984/3cc8eeea-d28a-11e5-811a-151a2a276552.png">

temporary resolution is to force redraw by calling Recent File or Search Headings shortcuts

**Comment by astoilkov** [comment]
We will investigate the problem and get back to you.

Thanks for reporting this issue.

**Comment by astoilkov** [comment]
Hi @nogorilla,

We have published an application update that should fix this issue. You can update to 1.3.0/1.3.1 and see if the problem still persists.

Thanks in advance.
