### ISSUE TITLE
After Window Swittching Text disappears

### ISSUE THREAD

**Issue by slamprecht** [careteditor/caret#440]
On my Mac:

I arrange two windows side by side. One ist Caret. I copy some text from the 1st window, e.g. browser. I change to caret and use cmd+v to insert. But when I change to caret the text of the actual paragraph disappereas. It comes back until i click the cursor in the document.

**Comment by erusev** [comment]
Hm, I don't reproduce the issue on my Mac.

A few questions:
1. Are the 2 windows in full-screen mode?
2. Do the other paragraphs in the text stay visible?
3. Does the issue happen in other documents?
4. What's the version of your MacOS?

Thanks so much!

**Comment by astoilkov** [comment]
We weren't able to replicate the problem. I am closing this issue for now. I will reopen it if we receive additional information on the problem.
