### ISSUE TITLE
Caret is opening an older cached(?) version of my document

### ISSUE THREAD

**Issue by dracan** [careteditor/caret#441]
I've just opened a Markdown file I was working in this morning, and some changes I had made are missing. However, the changes *are* in the file that's physically on disk. If I view the file in another editor, it does have the changes.

Caret has a `*` next to the filename, indicating there are changes, even when first opening the file. However, the changes seem to be referring to an *earlier* version of my document, not the latest. So Caret seems to have it's own cached copy of the document somewhere. How do I get it to ignore this cached copy and open the physical file that's on disk?

Note that I haven't edited this markdown file in any *other* editor than Caret, so this sounds like a bug.

This is a bit worrying, as I now don't feel I can trust that I'm working on the latest version of my document :-(

**Comment by dracan** [comment]
I've just had to get around this issue by opening the file in another editor, and copying and pasting the entire content back into Caret. Note that when I did this, the `*` went away (I didn't have to save the file again). So I assume the `*` is based on a real-time "diff"?

**Comment by dracan** [comment]
I notice that Caret does remember changes I've made since saving when closing and opening. So the only thing I can think of is if somehow I had accidentally deleted the missing content after saving and moving onto something else - and then when restarting Caret, it went to my unsaved accidental changes with no way to revert?

The above is just a guess with me trying to work out what *might* have happened. Seems odd that I'd accidentally delete content though. Perhaps I pressed ctrl-z to undo something in a different window not realising that it was Caret that had focus in another monitor ¯\\_(ツ)_/¯

Either way - there is the issue that there's no way to revert to the physical file on disk after restarting Caret. Undos aren't persisted, so I can't even undo those changes made. I had to paste the text back into Caret from another editor.

**Comment by astoilkov** [comment]
We have tried a lot of different scenarios in order to replicate a possible bug but without success. 

The only thing I can think of is what you said - you have made an undo change by accident with `Ctrl+Z`. How big was the difference between the two files?

You are right that there is an issue for not having a way to revert to the file on disc. We will find a solution to this problem and introduce it in the next minor release.

Additionally, we will improve the caching mechanism so we are absolutely sure a bug can't creep in.

**Comment by dracan** [comment]
It wasn't a big difference. A missing header I had added ready for me to start on the next section, and also a comma missing from the paragraph above the header. So there's certainly the possibility that the `ctrl+z` thing did happen.

I'd have thought the revert thing could just be a `File -> Revert` option?

**Comment by dracan** [comment]
It's just happened again with a couple of my most recent paragraphs missing in the cached version. I *know* I didn't accidentally undo this time. Same symptoms - physical file on disk *does* have my changes, but when I load up Caret, it doesn't have my changes and does have an `*` symbol.

I did logout and back in again though whilst Caret was still running, so it (and other apps) would have been closed by Windows rather than me explicitly doing so. Is it possible that this explicit close is breaking it?

**Comment by dracan** [comment]
I'll try and experiment with this hypothesis either later today or tomorrow. Unfortunately I can't at the moment though.

**Comment by dracan** [comment]
In fact, I've actually just tried it now, but it *didn't* show the issue. I tried making a change, saving the changes, then logging out of windows without closing Caret, then opening Caret after logging back in again. It did have the changes though. I'll keep an eye out so that next time it happens hopefully I'll have a bit more information.

**Comment by astoilkov** [comment]
Keep us posted. If you find the steps for replicating the problem we are ready to fix it immediately.

**Comment by dracan** [comment]
Happened again. Although I didn't do anything I didn't try when I tried to reproduce this morning. Are there any logs, or anything I can do to help diagnose the issue? I'm a programmer, so happy to dig a bit deeper with guidance.

**Comment by dracan** [comment]
Don't see why this would make a difference, but it's worth pointing out that my Markdown files are in a Dropbox folder.

**Comment by astoilkov** [comment]
I think I found the reason for the problem. I will investigate more, make a fix and release a version so we can check if the problem will go away.

**Comment by dracan** [comment]
Great news! Out of curiosity - what was the scenario that would have caused it?

**Comment by astoilkov** [comment]
I was able to replicate the problem by doing the following things:
  1. Open a saved file (with no modifications in it)
  2. Write something new without saving and wait for 1 minute without blurring the editor
  3. Add some more text to the file after the minute have passed and then save
  4. Log out
  5. Return back and launch the application - text should be the one that you wrote before waiting that minute

**Comment by astoilkov** [comment]
The fix is now included in the latest Caret release. We also made improvements and refactoring to the caching mechanism to ensure no such issues arise again.

Closing this issue. If for some reason the issue appears again write here immediately so we could reopen it and investigate more.
