### ISSUE TITLE
Freeze when using sidebar 

### ISSUE THREAD

**Issue by UltimateRandom** [careteditor/caret#442]
I'm using the files sidebar and sometimes when i switch to another file the program freezes and i have to kill it in task manager.
CPU i5-6200u, caret 3.2.1, windows 10 64.
Also can i make a request? 😄 sidebar files be accessible by single click.

**Comment by erusev** [comment]
Do you think there's something specific about the files that you switch to when it freezes - perhaps, big file size, or some specific content? Thanks

**Comment by UltimateRandom** [comment]
I think they are normal, the biggest has 1500 words.

**Comment by astoilkov** [comment]
We fixed the issue. The next release of Caret will include the fix.

Thank you so much for investigating and providing the additional information. 

I will close this issue when we release the next version of Caret.

**Comment by astoilkov** [comment]
Caret 3.2.3 with the fix included is now available.

Thank you so much for all the information provided.

Closing this issue.
