### ISSUE TITLE
Error with multi-line markdown table columns

### ISSUE THREAD

**Issue by m1guelpf** [careteditor/caret#444]
## Description

I was writing in a markdown table while having Caret in a small window (multitasking). When the table column text reached the border of the window and continued in another line, the error ocurred.

## Stack trace
```
{
    "message": "Cannot read property 'top' of undefined",
    "version": "3.2.2",
    "os": "Linux 4.8",
    "path": "web/Editor/Editor.Autocomplete.js",
    "code": "t.top+=Math.ceil(this._editor.dimensions.lineHeight/2),this.element.style.display=\"\",this.element.style.top=t.top+\"px\",this.element.style.left=t.left+\"px\",this._editor.command.get(\"autocomplete-close\").enabled=!0,this._editor.command.get(\"autocomplete-prev-item\").enabled=!0,this._editor.command.get(\"autocomplete-next-item\").enabled=!0,this._editor.command.get(\"autocomplete-select-item\").enabled=!0}.bind(this)))}},",
    "line": 5,
    "column": 2423,
    "stack": [
        "at t.<anonymous> (web/Editor/Editor.Autocomplete.js:5:2423)",
        "at Object.e [as callback] (web/Events.js:5:773)",
        "at t.value (web/Events.js:5:1330)",
        "at t.value (web/Editor/Editor.js:5:17933)"
    ]
}
```

**Comment by astoilkov** [comment]
Do you have an observation when this happened?

**Comment by m1guelpf** [comment]
@astoilkov I was writing in a markdown table while having Caret in a small window (multitasking). When the table column text reached the border of the window and continued in another line, the error ocurred.

**Comment by m1guelpf** [comment]
@astoilkov Is this fixed in the new release?

**Comment by astoilkov** [comment]
We fixed the bug internally. We will release a new version that will include the fix tomorrow.

**Comment by m1guelpf** [comment]
@astoilkov Didn't see it in the release notes... is it fixed?

**Comment by astoilkov** [comment]
Yes. It is fixed.

This is the description of the item:

> Fix | Cannot read property 'top' of undefined #444 #443 

I am closing this issue.
