### ISSUE TITLE
Something has turned spell checking off

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#448]
I'm not sure about the root cause but after pasting a long piece of text, I noticed that Edit > Check Spelling is disabled. I don't remember doing that manually (I use spell checking all the time).

It happened in 3.2 right before I updated to 3.3 if that's any clue.

**Comment by astoilkov** [comment]
Have this happened before?

I sometimes open command palette and while searching for another item accidentally hit enter on the spellchecking item. Is it possible something like this happened?

We haven't changed any code related to the spellchecking. The code is actually really straightforward. There are no if conditions so it isn't possible something to be turned off automatically by accident.

**Comment by borekb** [comment]
No it was the first time it happened. It is possible that I've turned it off somehow even though I'm not aware of it. I'm going to reopen this if it happens again, thanks for your quick response.

**Comment by borekb** [comment]
I have a theory of how this happened: I pressed Ctrl+Shift+P and searched for "check" as I was trying to check for updates. And I accidentally pressed Enter in the other row. That was probably it :)

![image](https://user-images.githubusercontent.com/101152/28409771-e6cf4e8c-6d3b-11e7-8076-4447cc3a51b7.png)
