### ISSUE TITLE
Feature request : vim mode

### ISSUE THREAD

**Issue by evmin** [careteditor/caret#454]
I would appreciate having the ability to use vim mode for edition notes.

**Comment by astoilkov** [comment]
Hi @evmin,

What is the difference between your [vi input mode](https://github.com/careteditor/caret/issues/415) feature request and this one?

Thanks in advance.

**Comment by evmin** [comment]
@astoilkov : My apologies. No difference - just ignorance on my part. Please close one of them. Sorry for the trouble.

**Comment by astoilkov** [comment]
No problem. Closing this one as in the other one there are votes and discussion.
