### ISSUE TITLE
Mouse selection is one character off

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#455]
Given this example text: `OO OOOO`, say that I want to select the right-most `OOOO` by dragging a mouse from the left boundary of the word. I have trouble doing that because clicking the left half of the first "O" letter jumps before the space:

![image](https://user-images.githubusercontent.com/101152/28499456-d8f3ce96-6fb6-11e7-87aa-dd5a7674bb3a.png)

It's a bit hard to see so here is a zoomed in version:

![image](https://user-images.githubusercontent.com/101152/28499468-240a146c-6fb7-11e7-8512-a4a2f8156068.png)

Correct would be this:

![image](https://user-images.githubusercontent.com/101152/28499478-7193e69a-6fb7-11e7-819e-036af5652bc5.png)

It isn't really related to the space between words, I get similar behavior insider words as well.

**Comment by astoilkov** [comment]
@borekb I can't seem to replicate the issue on any operating system. Is this consistent or it happens only from time to time?

**Comment by borekb** [comment]
Hmm, all seems to be OK now here too. Maybe it was a temporary glitch.

**Comment by astoilkov** [comment]
Probably [this](https://github.com/careteditor/caret/issues/354) is happening.

**Comment by dnlfrst** [comment]
This issue is still a thing, I experienced the exact same thing on Windows 10 yesterday. Right now there's no issue with the offset, so this is definitely not persistent, but happens only from time to time.

**Comment by astoilkov** [comment]
@Iw1s This is fixed in our internal build. Expect a release soon that will include the fix.
