### ISSUE TITLE
Numbering of ordered list with nested item is broken

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#456]
Example:

```md
1. First
    - nested
1. Second
2. Third
```

**Comment by astoilkov** [comment]
@borekb This is the same issue as https://github.com/careteditor/caret/issues/233 right?

**Comment by borekb** [comment]
Crap, and I tried to find it :) You're right.

**Comment by astoilkov** [comment]
No problem. I will close this issue and leave the previous one open. We will work on the issue soon.
