### ISSUE TITLE
PDF export with Latex Mathblock 

### ISSUE THREAD

**Issue by JanMoser** [careteditor/caret#458]
i tried to export a document with Latex Mathblocks which were apparently longer than the document width....in HTML export you show scrollbars...which is ok...but you do the same in PDF export ;-) which makes looking at them rather difficult :-)

![image](https://user-images.githubusercontent.com/8159942/28557962-d6a39126-710f-11e7-9fbc-64b1d9c3e80c.png)

**Comment by astoilkov** [comment]
Hi @JanMoser,

Do you have ideas what we could do when the math is longer than the document width?

Thanks in advance.

**Comment by JanMoser** [comment]
Hi @astoilkov,
maybe you could proportionally reduce the font size to fit the page width, or, as a quick win, maybe just reduce the default fontsize of the LaTeX block to the normal font one....at the moment it is huge

**Comment by erusev** [comment]
@JanMoser 

We reduced the size of math blocks (from 2rem to 1.2rem).

We'll release the update sometime next week.
