### ISSUE TITLE
I have to keep entering license on restart

### ISSUE THREAD

**Issue by vjdhama** [careteditor/caret#46]
I bought license for caret, but when i restart the app it still asks for license. Even when i have already entered it before.

**Comment by erusev** [comment]
Hm, is `Help` » `Enter License` active? 

If you have a minute, I'd love to discuss the issue over Skype or sth - email me at erusev@caret.io with info on how I can get in touch and I'll get in touch.

**Comment by vjdhama** [comment]
Yes it was. I had to enter license thrice. I'll gather more info and email you probably.

**Comment by erusev** [comment]
> it was

Does that mean that it's no longer there?

Thanks.

**Comment by vjdhama** [comment]
No. Now it seems to be fine. That's why I said I'll gather more info. I'll open a new issue if persists.

**Comment by erusev** [comment]
Thanks a lot, one more question, is it possible that the first time you entered the license you quitted the app in an unconventional way - for example, your mac restarted unexpectedly or sth like that?

**Comment by vjdhama** [comment]
Nope i quit the app normally.

**Comment by erusev** [comment]
Thanks, we'll investigate.
