### ISSUE TITLE
Heading navigation: show heading levels

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#461]
If I'm not mistaken, heading navigation used indentation or something similar to hint at the structure of the document while currently, it is flat:

![image](https://user-images.githubusercontent.com/101152/28573440-f46ea6a6-714a-11e7-8c79-dd2634f15c85.png)

Would be good to good to have the structure back.

**Comment by erusev** [comment]
@borekb we'll fix that in the next release (3.4), thanks for the feedback!

**Comment by astoilkov** [comment]
Closing this as it is now resolved in the latest version.
