### ISSUE TITLE
IME candidate window position jumps while typing.

### ISSUE THREAD

**Issue by lixiaoyan** [careteditor/caret#462]
![caret](https://user-images.githubusercontent.com/1610614/28583524-1a7fdb38-712f-11e7-8608-392bf088a3e2.gif)

I captured this video on Arch Linux with the latest version of Caret.

**Comment by ytxiuxiu** [comment]
Yes, the same issue on Mac.

**Comment by astoilkov** [comment]
We have fixed this issue. The next version of Caret will include the fix. I will close this issue when this happens.

Thanks for reporting.

**Comment by astoilkov** [comment]
The fix is now included in the latest version of Caret.

Closing this issue.
