### ISSUE TITLE
Image won't show in some cases

### ISSUE THREAD

**Issue by ytxiuxiu** [careteditor/caret#463]
As I scrolling up, some images disappear..., as the gif below (may cost a little while to load) shows

![jul-26-2017 22-06-58](https://user-images.githubusercontent.com/11512990/28620108-dfd2a260-724e-11e7-92cd-937623de44f2.gif)

Can someone fix this? Thanks!

**Comment by astoilkov** [comment]
This is now fixed in the latest version of Caret.

Closing this issue. Thanks for the bug reports!
