### ISSUE TITLE
Live preview isn't very 'live'

### ISSUE THREAD

**Issue by ytxiuxiu** [careteditor/caret#464]
The gif below (may cost a while to load) shows, the live preview is not scrolled to the same position as the left side. This is probably because there are images in the documents.

![jul-26-2017 22-13-31](https://user-images.githubusercontent.com/11512990/28620383-06436276-7250-11e7-90eb-f430229dd644.gif)

Thanks!

**Comment by astoilkov** [comment]
@ytxiuxiu Can you send us the document from the gif so we could test with it? (No problem if it is private and you don't want to share it)

**Comment by ytxiuxiu** [comment]
@astoilkov Sure, it is not at all private. Just my note. I've sent it to your gmail. Thanks!

**Comment by astoilkov** [comment]
This is now resolved in the latest version of Caret.

Closing this issue. Thanks for reporting.
