### ISSUE TITLE
Maintain manually entered numbered list values

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#467]
This kind of document is very hard to write in Caret:

```md
1. First item

~~~
code example
~~~

2. Second item

![image](image.png)

3. Third item
4. Fourth item
```

It's true that this is "faking" a single list and is three separate lists instead:

```html
<ol>
  <li>
    First item
  </li>
</ol>
<pre>
  <code>code example</code>
</pre>
<ol start="2">
  <li>
    Second item
  </li>
</ol>
<p>
  <img src="image.png" alt="image">
</p>
<ol start="3">
  <li>
    Third item
  </li>
  <li>
    Fourth item
  </li>
</ol>
```

But it's what we occasionally use if maintaining a nested list would be a pain.

Here, Caret's smartness gets in a way a bit:

![image](https://user-images.githubusercontent.com/101152/28692640-be053c50-7321-11e7-9e49-1f983dc2f9b4.png)

**Comment by bellebethcooper** [comment]
This is really common among Markdown editors, but I agree it's frustrating to not be able to override it when you want to.

**Comment by astoilkov** [comment]
We improved list autocompletion in [Caret 4.0 Beta](https://caret.io/4beta/). Now it is possible to make individual list items.

Closing this issue. If any more suggestions come to mind don't hesitate to write back.
