### ISSUE TITLE
[[toc]] bug with dots in headings and export to HTML

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#468]
For this document:

```md
## Butterflies etc.

Note the dot

## Normal heading
```

when I do `[[toc]]` and turn it into a full list, I get this:

```md
- [Butterflies etc.](#butterflies-etc.)
- [Normal heading](#normal-heading)
```

However, when I export to HTML, the H2 ID will be `id="butterflies-etc"` without the dot so the link in a ToC is not working.

**Comment by astoilkov** [comment]
We have fixed this issue in the latest version of Caret.

Closing this issue.
