### ISSUE TITLE
Spell-checking does not use system settings

### ISSUE THREAD

**Issue by hkdobrev** [careteditor/caret#47]
I use spell-checking on Mac OS with British English rules (Mac OS Preferences -> Keyboard -> Text -> Spelling: British English).

Other apps resort to that - e.g. Slack is underlining the word `revolutinize`, but accepts the word `revolutionise`. If I change my settings to American English, it would do the opposite.

However Caret is not conforming to this and it seems it's always using American English.

**Comment by erusev** [comment]
Good point, we'll see what we can do.

**Comment by erusev** [comment]
Btw, do u know that ctrl+space opens spelling suggestions? The site doesn't do a good job advertising that.

**Comment by hkdobrev** [comment]
@erusev ctrl+space on my machine is a global shortcut for toggling my terminal on top so I certainly didn't know/use that. I actually can't seem to use it unless I change my terminal shortcut, because there is no menu item for that so I can bind another application-level keyboard shortcut to the menu item.

**Comment by erusev** [comment]
Thanks, we'll introduce ways to configure the shortcuts at some point.

**Comment by hkdobrev** [comment]
@erusev There is no need as Mac OS already provides this if there is a menu item available.

**Comment by erusev** [comment]
Thanks, makes sense.

**Comment by brunolimawd** [comment]
Changing the language would be great, as I write in pt-BR and he always shows me as incorrect. But Slack it uses the configuration of my OS (OS X) to check in Brazilian Portuguese.

**Comment by astoilkov** [comment]
This is now implemented in the latest Caret release. Closing this.
