### ISSUE TITLE
When images are remote, editor is glitchy and jumpy

### ISSUE THREAD

**Issue by Swader** [careteditor/caret#473]
Since the editor does no caching of its own, it keeps trying to reload the remote URL for images included in the post. Now that images are included in the edit mode as well, this results in a huge degradation of UX - it keeps spazzing out and scrolling all over the place, moving the cursor out of view. Keeping images locally is not an acceptable workaround.

Steps to reproduce: write a post that has 1000+ words with remotely hosted images scattered throughout it.

**Comment by astoilkov** [comment]
Hi Bruno,

Does the issue appear when writing and editing or only when you first open the document?

**Comment by borekb** [comment]
It is noticeable on slower internet connection but I wouldn't say it's unbearable. It seems that images scrolled out of view are "garbage collected" by the rendering engine and drawn again when scrolling into view. Maybe some internal caching could be better there.

**Comment by Swader** [comment]
@astoilkov all the time, when writing and editing. It'd be bearable if it jumped back to the position it scrolled away from, but it doesn't.

@borekb As someone who works on a 30M connection and processes over 60k words of written content per week, I can tell you it's quite unbearable for me. I'm not talking about images being garbage collected, but being re-rendered even if still on screen as I type and change the content of the post in front of me. No need to scroll out of view.

The simplest solutions is to

- add a flag that disables image preview in the left pane of the editor

or 

- cache images locally in a .caret folder in the current folder.

Additionally, cache could be destroyed on file close, to preserve disk space (some of my posts are 20-50MB heavy with images, especially when dealing with gifs).

**Comment by astoilkov** [comment]
We have fixed the problem. You could update to Caret 3.4.0.

Closing this issue. Thanks a lot for reporting this problem and the additional information provided.
