### ISSUE TITLE
New window opens in wrong folder

### ISSUE THREAD

**Issue by bellebethcooper** [careteditor/caret#474]
1. I have a file open (Mac app 3.3.1)
2. Open new window with cmd+shift+N
3. Expect the new window to be in the same folder as the file in step 1, but it's actually in another folder I recently had open
4. Repeat step 2. This time the new window *is* in the same folder as the file in step 1
5. Repeat step 2. Again, the new window is in the folder I expected.

When closing all windows but the original from step 1, I was able to replicate this process again. The first new window opens in a recent folder but not the same folder as my open file. Every new window after that opens in the same folder as my open file from step 1, which is what I'm expecting.

**Comment by astoilkov** [comment]
This is now fixed in the latest [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue. Thanks for reporting!
