### ISSUE TITLE
It is better that images can be dragged to the document from the folder sidebar

### ISSUE THREAD

**Issue by ytxiuxiu** [careteditor/caret#475]
Like the screenshot shows below, it is better that images can be drag-and-dropped to the document from the folder sidebar

![snip20170801_1](https://user-images.githubusercontent.com/11512990/28822050-255b56f0-76fb-11e7-8213-c3942bbe2746.png)

It can be an enhancement

**Comment by astoilkov** [comment]
This is now implemented in the new Caret 4.0 Beta update available [here](https://caret.io/4beta/).

Closing this issue. Thanks for the suggestion.
