### ISSUE TITLE
An image inserting issue

### ISSUE THREAD

**Issue by ytxiuxiu** [careteditor/caret#477]
The most of time, when I drag an image from a sub-directory, it will link to the image using a relative path (see gif 1), which is good. However, only for some images, I don't know what kind of images, I drag to the document from a sub-directory, it will copy that image to the same directory of the document and insert it into the document with an absolute path to the image (see gif 2). So, in this case, I need to deleted the copied image and manually insert the image using relative path so that I can share my document (the absolute path doesn't work on other's computer)

![aug-01-2017 22-47-01](https://user-images.githubusercontent.com/11512990/28825894-5d4b8ec6-770b-11e7-8503-91e639260953.gif)
Gif 1

![aug-01-2017 22-36-08](https://user-images.githubusercontent.com/11512990/28825550-09d97cc2-770a-11e7-87d5-f1f5dd750cbf.gif)
Gif 2

**Comment by astoilkov** [comment]
We caught the problem and fixed it. The fix is now available in the Caret 3.4.0 release.

Closing this issue. Thanks for reporting.
