### ISSUE TITLE
script html tags not included in copy to html

### ISSUE THREAD

**Issue by bellebethcooper** [careteditor/caret#478]
I've been using some Zapier script embed tags in files recently and I've noticed that while other html is rendered in preview and included in export, these ones are not rendered in preview (which I'm fine with) but also completely missing when copying as html.

Here's an example of a script tag I'm using that's missing when copying as html:

```
<script type="text/javascript" src="https://zapier.com/zapbook/embed/widget.js?guided_zaps=3079"></script>
```

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 3.4.0 release.

Closing this issue. Thanks for reporting.
