### ISSUE TITLE
Cursor has some strange offset while writing on Linux (Debian 9)

### ISSUE THREAD

**Issue by Zhyano** [careteditor/caret#479]
When I type on my Linux device, on the newest Version (3.3.1) and Debian Stretch (newest Version) installed, the input cursor is offset by a weird amount, after changing the pointer location with arrow keys, and sometimes also with the mouse.
Before:
![screenshot from 2017-08-05 12-40-30](https://user-images.githubusercontent.com/29983972/28994936-5ae7df86-79db-11e7-9662-a2a417bcfcd1.png)
After:
![screenshot from 2017-08-05 12-41-54](https://user-images.githubusercontent.com/29983972/28994942-8389d548-79db-11e7-81fd-7051502a21ed.png)
(The cursor wasn't moved during these screenshots, just the 'm' key was pressed)

To reproduce, just type some stuff (like in these examples, click around and move the cursor with the arrow keys. Then there should occur this bug.

This problem makes using Caret on Linux hard, so a fix is really appreciated, but thanks for your great work though!

**Comment by astoilkov** [comment]
Hi @Zhyano,

What happens if you go to `File -> Preferences` and change the font from Roboto to some other font you have on your system?

Thanks for reporting this.

**Comment by Zhyano** [comment]
Is this intended to be so, or is this also a bug? There's no menu, or something similar?

This is what a new window looks like:
![screenshot from 2017-08-06 11-59-04](https://user-images.githubusercontent.com/29983972/29002290-41be9f9e-7a9f-11e7-9883-dc3185960d68.png)

Am I missing something?

But thanks for your help!

**Comment by astoilkov** [comment]
Have you tried pressing `Alt`?

**Comment by astoilkov** [comment]
Or maybe the `Caret` text after the `Applications`?

**Comment by Zhyano** [comment]
Ah, great, `alt` did the trick.

>What happens if you go to File -> Preferences and change the font from Roboto to some other font you have on your system?

Gonna try this out now

**Comment by Zhyano** [comment]
Thanks for your workaround!
Doesn't look as nice as before, but definitely working properly now!
Thanks a lot, again :smile:

PS: Is this bug already known or should I create a new issue just regarding Roboto?

**Comment by astoilkov** [comment]
You could create a new issue. We weren't aware of this problem.

Thanks for reporting this.
