### ISSUE TITLE
Cursor offset problems in headings and some :icons

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#484]
The cursor offset problem is back on the headings, as soon as a "problematic" icon is used, such as `:exclamation`, not sure why the problem is not there with other icons, such as `:email`:

![output](https://user-images.githubusercontent.com/819314/29076966-4701ec68-7c57-11e7-8acd-ad1e83ed6939.gif)

Sorry for the low quality but couldn't upload anything bigger :roll_eyes:

**Comment by astoilkov** [comment]
This is now fixed in Caret 4.0 Beta release available [here](https://caret.io/4beta/).

Closing this issue. Thanks for reporting this @manuelbua!
