### ISSUE TITLE
Typo in configuration settings make it difficult to switch proportional font in prose

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#485]
Upon opening the settings file you can notice the typo in there for `useProportionalFontInProse`, spelled instead `uuseProportionalFontInProse`.

~~User settings can still be saved, but one should manually correct the typo first, then save: upon saving, the typo is obviously back there, but with user settings applied.~~

**Comment by manuelbua** [comment]
Edited since, in fact, the settings are not saved either way.

**Comment by astoilkov** [comment]
This is now fixed in the latest version of Caret.

Closing this issue. Thanks for reporting @manuelbua
