### ISSUE TITLE
Nested to-do block incorrect syntax highlighting

### ISSUE THREAD

**Issue by nogorilla** [careteditor/caret#487]
When nesting to-do blocks the syntax highlighting incorrectly colors the closing `]`

note: the closing `]` is not the same subdued color as the open `[`

![screen shot 2017-08-09 at 9 20 59 am](https://user-images.githubusercontent.com/1786677/29123605-5083d502-7ce4-11e7-94c9-4c81ba795f56.png)

**Comment by astoilkov** [comment]
We have few issues regarding nested lists which we will fix soon.

Thanks for reporting.

**Comment by astoilkov** [comment]
This is now fixed in our new Caret 4.0 Beta release available [here](https://caret.io/4beta/).

Closing this issue. Thanks for reporting this.
