### ISSUE TITLE
Support YAML front matter

### ISSUE THREAD

**Issue by hkdobrev** [careteditor/caret#49]
Reference to the Jekyll docs: http://jekyllrb.com/docs/frontmatter/

I know you want to support this in the future, but I didn't find any issue about it.

But what does support for front matter mean?

Here are some pointers:
- [ ] Render it as a table in the preview similar to GitHub
- [ ] Recognise some of the properties as special. E.g. `title` could be identified as a heading so the `Jump->To Heading...` action would recognise and find it.
- [ ] Validate it against YAML specification
- [ ] Syntax-highlight it - YAML keys and values and perhaps colour the recognised keys differently

**Comment by erusev** [comment]
Thanks! We can use this issue to add other ideas as we discover them.

**Comment by astoilkov** [comment]
We are happy to say that we implemented YAML front matter support in Caret 1.10.0.
  - The YAML syntax is now highlighted in the editor
  - The YAML text is excluded from the preview. We exclude it because we want to make the preview appearance match the real published or printed version of the document

**Comment by estudiooka** [comment]
It's highlighted as a block, would be better if the syntax would be highlighted as happen when use a Yaml code box

**Comment by erusev** [comment]
Hi @estudiooka, what do you mean by Yaml code box? Thanks!

**Comment by estudiooka** [comment]
Please check the image bellow. 
It would be nice the left image to be as the right one.
Thanks.

[https://pasteboard.co/Ih66Xbt.png](https://pasteboard.co/Ih66Xbt.png)

**Comment by erusev** [comment]
I understand now and I think we can do that, thanks!

**Comment by estudiooka** [comment]
thank you, great app !!!
