### ISSUE TITLE
Cursor moves to beginning of file after saving

### ISSUE THREAD

**Issue by bellebethcooper** [careteditor/caret#494]
Caret 3.4.2 on Mac

1. Create a new file
2. Type a heading
3. Save file
-> Cursor moves to beginning of first line (heading) in file

Also tried adding some text after the heading and leaving cursor in text rather than first line/heading, but it still moves to beginning of file after saving.

**Comment by astoilkov** [comment]
This is now fixed in the latest [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue. Thanks Belle!
