### ISSUE TITLE
Question: different color schemes possible?

### ISSUE THREAD

**Issue by f8ttyc8t** [careteditor/caret#500]
Hi there,
using your great tool, already bought it to support development.

After using it for a while I was wondering whether it's possible to add/modify bright/dark editor color scheme? Even standard themes are pretty nice, it might be of value to have custom colors...
(this question is propably a duplicate of issue #117 )

Thanks in advance!

**Comment by astoilkov** [comment]
Thanks for the support @f8ttyc8t 

Currently there is no way to make a custom theme for the editor. You correctly found https://github.com/careteditor/caret/issues/117 where this is discussed. Editor themes is part of our roadmap so you could expect this to be implemented in the future. Note that before we implement this we have some other things planned so it may take a while. You could follow https://github.com/careteditor/caret/issues/117 to track for changes.

**Comment by f8ttyc8t** [comment]
Hi,
Thanks for quick response!

Will keep an eye on #117 , it's not an critical thing.

Anyway, thanks for crafting this great piece of software!
