### ISSUE TITLE
Question: disable image preview in editor

### ISSUE THREAD

**Issue by f8ttyc8t** [careteditor/caret#510]
Hi,
is there a way/config entry to disable image preview in **editor** (not preview)?
Even I really like automatic preview, using lots of images in document often break my writing flow.
Therefore it would be great to be able to configure this behavior (keyboard shortcut for toggling would be fantastic).

Thanks!

**Comment by astoilkov** [comment]
Hi @f8ttyc8t,

There are some users that want to disable image previews. We added this enhancement on our roadmap so expect this implemented. If you want to follow the progress of this item you could subscribe to [this thread](https://github.com/careteditor/caret/issues/378).

I will close this issue thread so we don't have duplicates. Thanks for reporting this.

**Comment by f8ttyc8t** [comment]
@astoilkov thanks!
Sorry - did not see there is already a related thread.
