### ISSUE TITLE
Disable strikethrough style for checked items

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#512]
I've noticed check items are now rendered like this:

![image](https://user-images.githubusercontent.com/101152/29562214-a7154686-8738-11e7-83bc-64ddfa5d2de8.png)

I'd appreciate a preference to disable this.

**Comment by erusev** [comment]
This is fixed now, we'll release an update later next week.

**Comment by astoilkov** [comment]
We disabled the strikethrough for checked items in [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue.

**Comment by appel** [comment]
Sorry to reopen this issue, but I'd actually prefer the strikethrough style for checked items, or at least have some type of visual indicator (e.g. 0.7 opacity). Can we have an option to enable/disable/style this, perhaps?

**Comment by erusev** [comment]
@appel 

I've been thinking about the same thing. I'll see what we can do.

**Comment by appel** [comment]
Thanks @erusev, appreciate it!
