### ISSUE TITLE
Locks up randomly

### ISSUE THREAD

**Issue by dracan** [careteditor/caret#515]
It's now started just locking up randomly whilst typing, and I have to kill the process. I'm afraid I don't really have any more information than this, as there's nothing really special or different I'm doing when it happens. It's happened a few times in the past two days, and I've barely been using it, so I'm guessing this would be happening a lot of I was currently using it in anger.

**Comment by astoilkov** [comment]
This should be now fixed in the latest Caret release.

Closing this issue.

**Comment by dracan** [comment]
Just been using it and it hasn't locked up yet 🤞
