### ISSUE TITLE
White Screen when first opening

### ISSUE THREAD

**Issue by aaronsaray** [careteditor/caret#52]
I am using the night theme - but whenever I open up Caret for the first time, it shows what I assume is the default/background for the white theme - for a good 1 second before it turns to black/dark.  I assume this is due to a loading delay where it's trying to apply the proper theme.  But, since I'm using a dark theme, one might assume (correctly) that my eyes are now very sensitive to bright flashes at this time of night. :)  It would be great to get this to either a) start in dark mode -or light mode - depending on what you're using - immediately or b) if there is a loading process going on, pick a middle of the road grey for the first screen before it is transitioned to either light or dark.

Thanks! Keep up the good work.

**Comment by erusev** [comment]
Thanks, this makes a lot of sense, we'll see what we can do.

**Comment by astoilkov** [comment]
Happy to say this is implemented in Caret. Closing this.
