### ISSUE TITLE
Saving without extension in Mac

### ISSUE THREAD

**Issue by ramthir** [careteditor/caret#522]
When saving a new file in Windows, it automatically gets the `md` extension. But when it comes to Mac the file is saved without the extension. We have to manually type the `md` extension after the file name.

Please fix the behaviour in Mac, so that it also get the `md` extension automatically when we type in just the file name when saving.

**Comment by astoilkov** [comment]
This is now fixed in the new Caret 4.0 Beta update available [here](https://caret.io/4beta/).

Closing this issue. Thanks for reporting this.
