### ISSUE TITLE
Cancel "Save changes?" quits caret

### ISSUE THREAD

**Issue by f8ttyc8t** [careteditor/caret#524]
Cancelling "save" dialog quits caret instance rather than cancelling closing app.

Reproduce:
0. Environment: Windows
1. open existing document in Caret
2. open another Caret window window (new document will be created)
3. type something into newly created window
4. close window -> Caret asks whether to save document or not.
5. press "cancel"
6. Document/instance will be exited. (On Mac, app behaves as expected by returning to document instead). Changes are (probably?) lost.

**Comment by astoilkov** [comment]
This is now fixed in the [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue. Thanks for reporting it @f8ttyc8t!
