### ISSUE TITLE
Ctrl+K in preview mode inserts link

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#525]
I was surprised by this, maybe it's a small bug.

1. Go to preview mode
2. Press Ctrl+K
3. See the current word turned to link
4. Confirm back in Markdown that `[link syntax]()` has indeed been inserted

![caret-link-in-preview](https://user-images.githubusercontent.com/101152/30024521-658445c8-9174-11e7-97be-68a57606b738.gif)

**Comment by borekb** [comment]
Drag & drop in preview mode also seems to affect the Markdown source. It's not really a static preview, is it? ;)

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue. Thanks Borek.
