### ISSUE TITLE
'Move Lines Up' includes one additional line below selection

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#526]
Before:

![image](https://user-images.githubusercontent.com/101152/30070412-9af1c9ca-9263-11e7-8515-37df332cf911.png)

After:

![image](https://user-images.githubusercontent.com/101152/30070423-a3c67550-9263-11e7-9e8e-611a4be900d4.png)

Expected (most editors behave this way):

![image](https://user-images.githubusercontent.com/101152/30070450-bdc19296-9263-11e7-8923-84c6a9d6840a.png)

**Comment by astoilkov** [comment]
This is now fixed in [Caret 4.0 Beta](https://caret.io/4beta/).

Closing this issue and the roll continues 😃.
