### ISSUE TITLE
License activation not working

### ISSUE THREAD

**Issue by thebuero** [careteditor/caret#540]
Hi, I bought Caret and really like it so far!
However, I cannot activate it on my second machine.
You state that „licenses are per user not per device“, which was a reason for me to buy.
Could you get in touch with me? what information do you need to assist?

Thanks,
Florian

**Comment by erusev** [comment]
Sure, can you forward us the email with your license at contact@caret.io?

Thanks!

**Comment by astoilkov** [comment]
I am closing this issue as the conversation is continuing at contact@caret.io.
