### ISSUE TITLE
Application drop-down menu missing on elementaryOS

### ISSUE THREAD

**Issue by Iw1s** [careteditor/caret#541]
I'm using elementaryOS (eOS) on my laptop and also have Caret installed there. Sadly, there's no drop-down menu showing up:

![fehler](https://user-images.githubusercontent.com/13868083/30816586-a0d154f6-a216-11e7-932d-c814fae5d364.png)

This issue might be related to the fact that eOS *does not support* normal menu bar like Windows does.
On Windows 10 Caret looks like this at the moment (expectation):

![erwartung](https://user-images.githubusercontent.com/13868083/30808306-df334da8-a1fd-11e7-84a6-ca2e9c213d5c.PNG)

This is a little disruptive, because every option normally available in the drop-down menu now has to be chosen from the `Ctrl+Shitf+P` command palette.

**Are you aware of this fact or is this intended?**

**Comment by astoilkov** [comment]
Hi @Iw1s,

Have you tried pressing the Alt key? This should open the application menu. Let me know if this helps.

**Comment by erusev** [comment]
@Iw1s 
Do you have experience with the Elementary store?
Do you know if it would it be difficult to add Caret to the store?
I like Elementary very much and I'd love to see Caret in the store.

**Comment by dnlfrst** [comment]
@astoilkov   
I haven't, but that's actually the solution to my problem, thank you very much!  

@erusev   
It would indeed be nice to see Caret in the AppCenter. Sadly I have yet to make any in-deepth experience with it.  
Nevertheless, from what I've read so far, I don't think Caret can be published as-is. This is based on technical [requirements](https://github.com/elementary/houston/wiki/Before-You-Publish) that need to be fulfilled prior to publishing an app in the AppCenter:

- Your app needs to be a native Gtk3 app. _Electron apps are explicitly prohibited._
- Your app must come with Debian packaging.
- Your app needs to be hosted in a GitHub repository, thus open-source.

**Comment by erusev** [comment]
@Iw1s 
Thanks for the great response!
