### ISSUE TITLE
Making text bold while containing an asterisk confuses the editor, preview is fine

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#543]
I had to make some text bold and it was containing an asterisk, when i noticed the editor window gets confused by it, while the preview rendering seems fine:

![bold-bug](https://user-images.githubusercontent.com/819314/30918223-2cad7044-a39e-11e7-8af3-1542a88a1b2d.png)

Notice how the editor gets confused after the first ending asterisk, but the preview window is showing the correct result.

You can use the following text to replicate the problem:
`test test **5*12** test test`

**Comment by erusev** [comment]
This is fixed now, we'll ship the fix with the next beta release.

**Comment by astoilkov** [comment]
We have released a new Caret Beta update which includes the fix.

Closing this issue. Thanks for reporting.
