### ISSUE TITLE
Visual bug with license ad while checking for updates and viewing preferences

### ISSUE THREAD

**Issue by dnlfrst** [careteditor/caret#545]
This issue occured on **Windows 10 Home (10.0.15063 Build 15063)** using **Caret 3.6.4**.
When the preferences are opened (`File > Preferences`), simultaneously checking for updates (`Help > Check for updates...`) (whereas no updates are present) and having the ad for purchasing a license leads to a visual bug (see below).  
Neither using `Esc` nor clicking the `[x]` does remove this. There's no way other than restarting the application to get rid of the bug.

How it looks like:

![fehler einstellungen benachrichtigung update](https://user-images.githubusercontent.com/13868083/30985111-965362e6-a48f-11e7-86ef-4b2b43ef957f.PNG)

**Comment by astoilkov** [comment]
Hi @Iw1s,

This is now fixed in our new Caret 4.0 Beta update available [here](https://caret.io/4beta/).

Closing this issue.
