### ISSUE TITLE
License advertisement is hidden when Caret loses focus resulting in visual bug

### ISSUE THREAD

**Issue by dnlfrst** [careteditor/caret#548]
This issue occured on **Windows 10 Home (10.0.15063 Build 15063)** using **Caret 3.6.4**.  
When the license advertisment is shown and Caret loses focus, said ad is hidden instantly. Caret losing focus implies clicking outside of its window boundaries or focusing another application.  
What still remains is the `div`-container at the bottom saying `hit esc to close | [TIMER]`. This is even true after the timer runs out, thus, taking the ability to actually hit `Esc` and remove the `div`-container. Removing it can only be done by restarting the application.  
Although the ad is hidden by losing focus, Caret is still disabled while the timer is running and enabled again after the countdown has finished.

How it looks like:

![fehler](https://user-images.githubusercontent.com/13868083/31012295-92897902-a511-11e7-910c-1787bf153d4c.PNG)

**Comment by astoilkov** [comment]
This is now fixed in the new Caret 4.0 Beta update available [here](https://caret.io/4beta/).

Closing the issue. Thanks for reporting.
