### ISSUE TITLE
Recent file path cutoff 

### ISSUE THREAD

**Issue by enovid** [careteditor/caret#549]
I love the recent file feature, but long file paths get cut off. 

This is especially frustrating because some repo names make the path too long. (e.g. the repo for my stats course)

<img width="579" alt="caret-recent-file-path-cutoff" src="https://user-images.githubusercontent.com/8015376/31051598-302c06d8-a621-11e7-9d53-fd0797478e6d.png">

**Comment by jelias** [comment]
Glad I found this before reporting the same thing.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 4.0 Beta release available [here](https://caret.io/4beta/).

Closing this issue. Thanks for reporting.
