### ISSUE TITLE
Nested List have differing syntax highlighting

### ISSUE THREAD

**Issue by nogorilla** [careteditor/caret#55]
Not sure if this is a bug or as intended, but as you can see in the screenshot I have a nested todo list. The first item is highlighted correctly while following items have highlighting similar to code

<img width="1171" alt="screen shot 2016-03-09 at 7 24 00 pm" src="https://cloud.githubusercontent.com/assets/1786677/13655371/d9e37956-e62c-11e5-99c2-00431c5d5439.png">

**Comment by astoilkov** [comment]
This took us a while but it is now fixed in the latest version of Caret.

Closing this issue. Thanks for reporting.
