### ISSUE TITLE
HighSierra Bug

### ISSUE THREAD

**Issue by PierreFontaine** [careteditor/caret#550]
Since I moved on HighSierra, Caret launch but doesn't respond.

![image](https://user-images.githubusercontent.com/15703438/31077587-556ccf40-a77f-11e7-961f-ebc9edf91585.png)

**Comment by astoilkov** [comment]
Hi @PierreFontaine,

We have moved one of our testing machines on HighSierra in order to replicate the issue but this was without success. Can you try to reinstall Caret in order to see if the issue will be fixed? You could use an app like AppCleaner or just go and remove ~/Library/Application Support/Caret folder.

Thanks in advance.

**Comment by ramthir** [comment]
@astoilkov I've recently updated to HighSierra and I can use Caret without any issues.

**Comment by chris-c-thomas** [comment]
@PierreFontaine  I'm also using High Sierra and Caret launches without issue. I'd try completely removing Caret and reinstalling? Like @astoilkov mentioned, clear ~/Library/Application Support/Caret along with deleting the app as a whole. Hopefully this fixes everything for you.

**Comment by PierreFontaine** [comment]
Thanks for all those answers ! Unfortunately clearing `~/Library/Application Support/Caret` didn't solved my issue, so I moved on Typora.

**Comment by astoilkov** [comment]
Hi @PierreFontaine,

It is possible that the soon to be released Caret 4.0 will fix the problem. If you are interested I could write you back when this happens?

**Comment by PierreFontaine** [comment]
Sure you can !

**Comment by astoilkov** [comment]
Hi @PierreFontaine,

We have released a [Caret 4.0 Beta](https://caret.io/4beta/) which should fix the problem. You could try it and let me know.

Thanks for trying out in advance.

**Comment by PierreFontaine** [comment]
hello @astoilkov,

I've tried your beta release, and it works well !

Thanks for keeping me informed 👍
