### ISSUE TITLE
Caret performance on large .md files

### ISSUE THREAD

**Issue by aslushnikov** [careteditor/caret#554]
Hi guys,

I've purchased caret to edit documentation for puppeteer: https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

It worked really good at first, but now the documentation file is pretty huge and the editing experience is sluggish. I no longer enjoy caret for editing and have to fall back to vim.

Are there any plans for improving editor performance on large files?

Thanks,
Andrey

**Comment by erusev** [comment]
Yes, we'll introduce a significant improvement in performance with the next update later this month - I can let you know here when the update is out.

**Comment by aslushnikov** [comment]
@erusev thanks guys, looking forward to it.

**Comment by astoilkov** [comment]
We have release Caret 4.0 Beta which includes huge performance and memory boosts. You can download it from [here](https://caret.io/4beta/).

Closing this issue. Hope you now return to Caret.

**Comment by aslushnikov** [comment]
> Hope you now return to Caret.

@astoilkov It's very snappy. Thank you guys for your work, I'm back. 

P.S. the "search" UI is way nicer too.
