### ISSUE TITLE
Files open in TextEdit

### ISSUE THREAD

**Issue by jamipietila** [careteditor/caret#557]
Hi!

For some reason files what I open directly from Caret left menu or from the Caret file manager (CMD + T), they open in TextEdit instead Caret.

When I open them from File > Open (CMD + O) or Recently opened menu (CMD + E) they open in Caret.

Any ideas how to fix it?

**Comment by astoilkov** [comment]
Hi @Jamipietila,

What are the file extensions of the files you are trying to open?

Sorry for the delay.

**Comment by jamipietila** [comment]
No worries, thanks for the reply :)

Caret seems to do Plain Text Document (txt) as default. Default app in my system for those is TextEdit.

**Comment by astoilkov** [comment]
Hi @Jamipietila,

Can you test if you will experience the sample problem in the new [Caret 4.0 Beta](https://caret.io/4beta/)?

Thanks in advance.

**Comment by jamipietila** [comment]
Sure thing! But the link to the Beta is not working at the moment?

**Comment by astoilkov** [comment]
The link is now fixed. Sorry for the inconvenience.

**Comment by jamipietila** [comment]
Files open now, great! I found a bug from Beta what is not related to this one. I create another ticket.
