### ISSUE TITLE
Add keyboard shortcut for strikethrough

### ISSUE THREAD

**Issue by nogorilla** [careteditor/caret#56]
Currently, strikethrough does not a keyboard shortcut. I use that formatting a lot and would love to have this feature.

**Comment by erusev** [comment]
Makes sense, do u have a specific shortcut in mind?

**Comment by nogorilla** [comment]
⌘S is already used for 'Save' so maybe: ⌘⌥S or maybe ⌘⌃S would be good

**Comment by erusev** [comment]
You can set that through OSX preferences, it's super simple, u can follow the steps at:
https://support.apple.com/kb/PH18418?locale=en_US

**Comment by nogorilla** [comment]
Thanks, pretty new to OSX so I didn't know about that.

**Comment by erusev** [comment]
That's ok, I just recently found out about it, I'll close this though, as it'd take us too much effort to find a shortcut that makes sense as is consistent enough.
