### ISSUE TITLE
Spell check not working

### ISSUE THREAD

**Issue by ROpsal** [careteditor/caret#560]
Caret 3.4.6 on Windows 7-64bit.

The spell check option isn't working.  I've disabled and then re-enabled.  I've also done a reinstall.

Am I missing a file or something?

**Comment by astoilkov** [comment]
Hi @ROpsal,

Sorry for the inconvenience. We will need a little more information in order to pinpoint the problem.

What language are you trying to spell check? Do you have other applications that experience the same problem?

Thanks in advance.

**Comment by ROpsal** [comment]
Hello,

Language I am using is US English.  The Typora program has no issues with spell checking.

I also tried wiping out the Roaming\Caret and Local\Caret directories and reinstalling.  No change.

Thanks.

**Comment by astoilkov** [comment]
We found the problem and already fixed it. The next Caret release will include the fix. I will write in this thread when this happens.

Thanks for the information @ROpsal.

**Comment by f8ttyc8t** [comment]
Any idea when to expect new & fixed version?
Caret.io features site mentiones version 4 to be planned for around September 2017...

Thanks.

**Comment by astoilkov** [comment]
Hi @f8ttyc8t,

It will take us between one and two weeks to release the next version. Regarding the features page, this is an old information which we will remove soon. Thanks for mentioning.

**Comment by f8ttyc8t** [comment]
Hi @astoilkov ,
Thanks for letting us know!

Looking forward to get new version.

**Comment by astoilkov** [comment]
Caret 4.0 Beta release is now available [here](https://caret.io/4beta/). The release fixes the described issue.

Sorry for the delay in releasing the new version.
