### ISSUE TITLE
High Memory Consumption When Editing Long Documents

### ISSUE THREAD

**Issue by diethardsteiner** [careteditor/caret#561]
When I tried Caret about a year ago it really struggled with longer documents - this seems to have been improved in the meantime. There is, however, still a slight delay noticeable when typing. Also, when you start typing, memory consumption suddenly increases by quite a bit every few words you type:

This is the memory consumption when opening the long document with Caret:
 
![screenshot from 2017-10-29 08-32-56](https://user-images.githubusercontent.com/1726057/32143744-1864abea-bca6-11e7-85b1-579b63b0207f.png)

When I start typing something, memory consumption increases:
![screenshot from 2017-10-29 08-33-42](https://user-images.githubusercontent.com/1726057/32143748-306d44cc-bca6-11e7-8272-e38dbf547c7f.png)

and then after just a few words more the increase in memory usage is quite considerable (not extreme, but considerable - over 200MB):
![screenshot from 2017-10-29 08-34-53](https://user-images.githubusercontent.com/1726057/32143807-38fcf320-bca7-11e7-8a5b-78c079d5efd0.png)

Now if I compare this with Abricotine, first of all the document opens instantly (I notice a delay with Caret) and editing the document doesn't change the memory consumption:

Opening the long doc:
![screenshot from 2017-10-29 08-31-44](https://user-images.githubusercontent.com/1726057/32143768-83b3bd00-bca6-11e7-93e9-ccca5c3a515f.png)

Editing the long doc:
![screenshot from 2017-10-29 12-42-51](https://user-images.githubusercontent.com/1726057/32143780-b85215ca-bca6-11e7-8dc1-cb7468e79166.png)

It would be really great if you could make some further improvements on Caret in regards to memory consumption. 
Background info: Caret is running on Fedora (latest stable version), 16GB RAM, i7 processor

**Comment by astoilkov** [comment]
Hi @diethardsteiner,

I am happy to say we devoted a lot of effort on performance the past months. We improved file loading time, typing performance, memory consumption and app startup time by a lot. You could expect these things released soon in Caret 4.0 Beta release.

**Comment by diethardsteiner** [comment]
Hi @astoilkov,
Excellent - good to hear! Will the beta be available via https://github.com/careteditor/beta?

**Comment by astoilkov** [comment]
Yes. I will write in this thread when this happens.

**Comment by diethardsteiner** [comment]
Ok, thanks

**Comment by astoilkov** [comment]
I am writing here to let you know that Caret 4.0 Beta is available [here](https://caret.io/4beta/) which includes huge performance and memory boots.

Hope you like it.
