### ISSUE TITLE
No menu visible in PopOS. 

### ISSUE THREAD

**Issue by sudhirj** [careteditor/caret#563]
There's a really good linux distro called Pop OS that's based on Ubuntu and Gnome, and Caret runs on it, except that I can't find the menu anywhere. The menu on the top left only has the option to quit, and because Caret doesn't display the menu bar I'm stuck.

**Comment by sudhirj** [comment]
Keyboard shortcuts work fine, though, so in the meanwhile if you publish a keyboard shortcut cheat sheet for Linux that would be great.

**Comment by astoilkov** [comment]
Hi @sudhirj,

In order to show the menu, you could press the `Alt` key. Additionally, you could open `File -> Keyboard Shortcuts` where you could find a list of shortcuts.

**Comment by sudhirj** [comment]
Alt key works great, thanks. Closing, see if you can document this more clearly somewhere? The clean start looks great on macOS, but it has better affordance by appearing when the mouse moves.

**Comment by astoilkov** [comment]
We are working on a documentation articles that will be available on our site when ready.
