### ISSUE TITLE
caret is too almost a wiki

### ISSUE THREAD

**Issue by jorgemelis** [careteditor/caret#57]
Should you find a way to open links to files in my file system, I would have the best wiki.
I enter a link of the form [text](path-to-file)
If Caret could then open and let me edit path-to-file when I clicked the link, I would have a wiki too

It would be the simplest, lightweight and perfect wiki for me

**Comment by erusev** [comment]
> open and let me edit path-to-file when I clicked the link, I would have a wiki too

I'm not sure I understand, do you mean clicking on a link to another file from the file system should open that file in Caret?

**Comment by jorgemelis** [comment]
yes!, that would be wonderful! it could be the most portable wiki!

**Comment by erusev** [comment]
Try <kbd>Cmd</kbd>+click

**Comment by jorgemelis** [comment]
You are the best! 
If you feel like it sometime, you could improve it further accepting a link relative to the document being edited.

Thank you very much!

**Comment by erusev** [comment]
> If you feel like it sometime, you could improve it further accepting a link relative to the document being edited.

This should work as well.

**Comment by jorgemelis** [comment]
I am on a mac. I am editing /Users/jorge/Dropbox/_/posts/Hardware.md where I reference another file
with the text [MBP13JoE2015](/Users/jorge/Dropbox/_/posts/Hardware/MBP13JoE2015.md)
and it works perfectly.

But if I use [MBP13JoE2015](Hardware/MBP13JoE2015.md)
or [MBP13JoE2015](./Hardware/MBP13JoE2015.md)

it doesn't work

**Comment by erusev** [comment]
Ah, I see, we'll see what we can do to fix that, thanks.

**Comment by astoilkov** [comment]
Hi @jorgemelis,

I don't seem to replicate the issue. References like `file.md` `./file.md` `/file.md` all work on my side. Can you update to the latest Caret version (1.2.2) and report if the issue still persists? It could be something that we already fixed.

**Comment by jorgemelis** [comment]
Sorry I haven't been able to test it before. It still happens to me on a
mac, El Capitan with Caret version 1.2.2

The file I am editing is  /Users/jorge/Dropbox/_/posts/Hardware.md
The files I am referencing are in /Users/jorge/Dropbox/_/posts/Hardware/, a
subdirectory of the directory Hardware.md is in.

If I use the link in the
form /Users/jorge/Dropbox/_/posts/Hardware/MCB15JorgeEarly2011.md it opens
with Ctrl-Cmd, but if I use ./Hardware/MCB15JorgeEarly2011.md it doesn't
open.

Thank you very much for your interest, I can work with the full paths
anyway.

**Comment by astoilkov** [comment]
Ok. I have created the exact same folder structure and put the links that you provided but still can't replicate the problem.

Could you paste the paragraph of text in which you have the links that are not working so we could try with them.

Additionally, what happens when you hit `Cmd+Click ` or `Ctrl+Space` and open the file? Is there anything that happens or the applications doesn't seem to do anything?

**Comment by jorgemelis** [comment]
This text is not working

## [MBP13JoE2015](./Hardware/MBP13JoE2015.md)
- MacBook Pro (Retina, 13-inch, Early 2015)
- 2,7 GHz Intel Core i5
- 8 GB 1867 MHz DDR3
- Intel Iris Graphics 6100 1536 MB
- C02PVRG6FVH5

I cannot hit Ctrl+Space because the file scrolls down to the end, and when
I hit Cmd+Click at the link it does nothing, as if I had not pressed it.

With absolute links it opens the file.

I cannot find my work directory when I am using Caret, perhaps that is the
problem.  Could it be your working directory matches the edited file path
in your case but not in mine?

Thank you very much again, but please, don't bother with it, it's a minimum
issue for which I have a straightforward wraparound.

**Comment by astoilkov** [comment]
Hi @jorgemelis,

Sorry for the big delay. What do you mean by my working directory matching the edited file path. Can you give concrete examples?

**Comment by astoilkov** [comment]
Hey @jorgemelis,

We have done some improvements regarding this topic.

I am closing this issue for now. If you problem persists do not hesitate to reopen it and explain what's wrong.

Thanks for all detailed explanations.
