### ISSUE TITLE
No menu options on Ubuntu 17.10

### ISSUE THREAD

**Issue by liston** [careteditor/caret#570]
I've just installed the latest deb version of Caret on Ubuntu 17.10, but when I start it up  I do not see any menu options.

Liston

**Comment by LoopLupe** [comment]
same here

**Comment by astoilkov** [comment]
Have you tried to press the `Alt` key? This should show the app menu.

**Comment by liston** [comment]
Yep, Alt key works, thanks.

**Comment by astoilkov** [comment]
Great to hear that. I will close this issue. If you have more questions please feel free to open new issues.
