### ISSUE TITLE
Search for content in all files?

### ISSUE THREAD

**Issue by gandalfsaxe** [careteditor/caret#576]
Caret has excellent features for:
1. Searching for files
2. Searching for content within a file

Have you considered to make a fuzzy global search for content across all files? That would be very helpful.

**Comment by erusev** [comment]
We have "find in files" accessible from Edit › Find in Files.

**Comment by gandalfsaxe** [comment]
Ah yes, it didn't work for me the first time I tried it, so I thought it did something different. But it looks like exactly that. Excellent! 😃
