### ISSUE TITLE
installation on ubuntu 17.10

### ISSUE THREAD

**Issue by nio101** [careteditor/caret#578]
I installed the latest caret.deb on Ubuntu 17.10, but launching the app through the app menu did nothing.

Is there any command line available to run Caret?

**Comment by astoilkov** [comment]
Hi @nio101,

There isn't any command line available for running Caret yet. Have you tried uninstalling Caret and installing it again? Additionally, we will test Caret on Ubuntu 17.10 and we will get back to you.

Thanks for reporting this issue.

**Comment by nio101** [comment]
Yes, I tried, but uninstall/reinstall didn't help.

**Comment by astoilkov** [comment]
We will investigate further and let you know when we have more information on this. Thanks.

**Comment by nio101** [comment]
tried to manually run Caret from /opt/caret, got a message stating that libgconf2.4 was missing, installed it using `apt-get install libgconf-2-4`...
But now I only get this message:
`pcilib: Cannot open /sys/bus/pci/devices/0000:05:01.0/resource`

(same problem as with the beta version)

**Comment by astoilkov** [comment]
@nio101 As I understand correctly you are experiencing the same problem with both the Beta release and the Official stable release?

**Comment by nio101** [comment]
tried to manually run Caret from /opt/caret, got a message stating that libgconf2.4 was missing, installed it using `apt-get install libgconf-2-4`...
But now I only get this message:
`pcilib: Cannot open /sys/bus/pci/devices/0000:05:01.0/resource`

(same problem as with the beta version)

**Comment by nio101** [comment]
Yes...
Same problem with Atom also...
`sudo update-grub && reboot` seemed to fix this ubuntu 18.04 problem... :)

**Comment by astoilkov** [comment]
This seems to be a problem only for some users. We have complaints from other users as well. We will create a documentation article for such problems so users can easily fix them.

Closing this issue.
