### ISSUE TITLE
Image attributes breaks live preview (pandoc / pandoc-crossref spec)

### ISSUE THREAD

**Issue by gandalfsaxe** [careteditor/caret#579]
I found a pretty good solution to the problem referencing figures, tabels, equations etc (see #567). through the pandoc filter [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref/blob/master/docs/man.md). Of course, this is only a fix for the PDF that gets produced by running `pandoc` command, and support in Caret with live preview of cross reference links etc. would be ideal.

Unfortunately the syntax of pandoc-crossref make Caret not render live previews. For example an image with a label in pandoc-crossref syntax is `![Caption](url){fig:labelhere}`. But adding the curly brackets at the end, breaks the live preview of the figure in Caret. So `pandoc-crossref` is quite unusable with Caret now.

I'm using Typora as well, and it doesn't have this problem; adding `{fag:label}` at the end, still renders the image preview (Typora gives me other headaches such as not showing the alt-text / captions with the image preview, but that's another topic).

I hope you will consider some kind of solution for this. Perhaps allowing {} tags with figures, tables, equation etc. without breaking the live preview?

**Comment by astoilkov** [comment]
Hi @GandalfSaxe,

Do you mean that adding an image with the following syntax `![Caption](url){fig:labelhere}` breaks the image preview inside of the editor or inside of the `View -> Preview`?

Thanks.

**Comment by gandalfsaxe** [comment]
It only breaks it in the preview inside the editor, the View->Preview still renders the image fine.

**Comment by astoilkov** [comment]
This is fixed in our internal build. The next release will include the change.

**Comment by gandalfsaxe** [comment]
Good to hear! :)

Now that we're talking about this, have you thought about supporting image size attributes of pandoc so live previews are scaled accordingly?

Pandoc supports image size attributes. For for example `![](file.jpg){ width=50% }` will work. Combined with pandoc-crossref it looks like `![](file.jpg){#fig:figlabel width=50%}`.

**Comment by astoilkov** [comment]
Yes. We have been thinking about this but before we implement it we have higher priority tasks and this could take awhile.

**Comment by astoilkov** [comment]
This is now implemented in the latest Caret 4.0 Beta update available [here](https://caret.io/4beta/).

Closing this issue. Thanks for reporting.

**Comment by gandalfsaxe** [comment]
I don't know if it was ever fixed, but adding any label on a figure, e.g. going:

`![Hi hello there](lol.jpg){#fig:label}`

instead of just

`![Hi hello there](lol.jpg)`

does break the live figure preview. This is in Caret 4.00 rc8 bete

**Comment by erusev** [comment]
What's the best document that describes how this syntax works? Thanks!

**Comment by gandalfsaxe** [comment]
That would be the docs of pandoc-crossref: https://github.com/lierdakil/pandoc-crossref/blob/master/docs/index.md

And if you just wanna see examples, there is a demo document: https://github.com/lierdakil/pandoc-crossref/tree/master/docs/demo - i.e. `demo.md` is the input, and all the `output*` are the various output as specified in the makefile.

As mentioned, [Typora](https://typora.io) simply ignores the {...} in in live preview of the markdown image ![]() whereas it actually breaks the live preview in Caret. However Typora doesn't support figure captions in Live preview. So it would be really awesome if you would consider making the text in the square brackets visible as image captions in the live preview!

**Comment by gandalfsaxe** [comment]
Actually, it's not just `pandoc-crossref` filter, it's actually also a syntax supported by `pandoc` itself, see https://pandoc.org/MANUAL.html#extension-link_attributes

Thus the {} content can be considered a very standard way to providing image/link attributes.

As a start, just ignore the `{...}` content and render the image anyway.
Then later you can always work on properly resizing the image according to any width/height attributes.
