### ISSUE TITLE
Artefact in generated PDF & lists

### ISSUE THREAD

**Issue by instanceofme** [careteditor/caret#58]
I have a `o` at the start of any PDF where a list is present. E.g. generate from the following text

```Markdown
Test

- list item

```

Version: 1.2.1

**Comment by instanceofme** [comment]
This too causes a problem, also visible directly in preview:

```Markdown
  1. Frist
  2. Second
      - sublist
  3. Third
```

**Comment by astoilkov** [comment]
We fixed this. We are waiting for a response on https://github.com/careteditor/caret/issues/45 before creating a new release.

**Comment by astoilkov** [comment]
Fixed. We pushed a new app update - 1.2.2.
