### ISSUE TITLE
4.0 Beta: Orphaned Processes

### ISSUE THREAD

**Issue by clockler** [careteditor/caret#591]
Running the new 4.0 Beta version on Windows 10, upon exiting (whether by closing the window normally, using File > Exit, or the Close Window command) the subprocesses are not properly closed and instead are left running. On startup the editor seems to be pulling some garbage data from these still-running processes, as they are recognized as child processes when the editor is again running and the editor frequently re-runs with the introduction files open.

For instance, if I remove the contents of the electron-cache and cache directories and run the editor, it runs with the default window bounds and opens the introduction as expected. I can then open another folder and select a file from that folder, maximize the window, then close the window; upon re-running, I get a window with the correct *size*, but not maximized, and containing the introduction instead of the files I had opened. If I end the task and its child processes along with it instead of exiting normally, I get the expected result on reopening it - a Caret window exactly as I left it.

Funnily enough if I open multiple windows while leaving the child processes, then later end all the orphans, the next run will open all the windows I closed normally at once.

**Comment by astoilkov** [comment]
This is now fixed in the new [Caret 4.0 Beta update](https://caret.io/4beta/).

Closing this issue. Thanks so much for testing the new Caret 4.0 Beta!
