### ISSUE TITLE
Beta 4 error

### ISSUE THREAD

**Issue by Amparose** [careteditor/caret#594]
Was about to post an issue about the live preview not updating between opening files in the welcome folder but then noticed the neat "an error occurred" bar down the bottom. Restarted Caret Beta and preview updates so not sure how to trigger the error.

The following error has occurred:
```
{
    "message": "Path must be a string. Received undefined",
    "version": "4.0.0-beta0",
    "os": "macOS High Sierra",
    "path": "path.js",
    "line": 7,
    "column": 5,
    "stack": [
        "at assertPath ((path.js:7:11)",
        "at Object.basename ((path.js:1355:5)",
        "at PathWrap._update (extensions/Path/PathWrap.js:5:584)",
        "at EditorDesktop.trigger (node_modules/desktop/Events.js:76:27)",
        "at EditorDesktop._update (extensions/Editor/Editor/Editor.js:5:4845)"
    ]
}
```

**Comment by astoilkov** [comment]
This is now fixed in a new 4.0 Beta update. You can download it from [here](https://caret.io/4beta/).

Closing this issue. Thanks for reporting.
