### ISSUE TITLE
v4 beta weird Windows taskbar behavior when v3 is installed as well

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#597]
I've pinned Caret v4 beta to a taskbar on my Windows 10 machine and all the fields of the shortcut seem right:

![image](https://user-images.githubusercontent.com/101152/34628969-9d1a1078-f266-11e7-83d6-6abd35a17856.png)

However, when I click it, Caret v3 icon is started, although the app is Caret 4 beta. Actually, now, I'm a weird state where v4 doesn't even start (note the taskbar):

![caret-v4-doesnt-start](https://user-images.githubusercontent.com/101152/34629141-5e4295ea-f267-11e7-96d8-8ef7e007e588.gif)

I'll try to clean up some caches.

**Comment by borekb** [comment]
Oh, this will have something to do with it:

![image](https://user-images.githubusercontent.com/101152/34629231-bc01491a-f267-11e7-958d-8c1eaf9b2071.png)

**Comment by borekb** [comment]
That helped, so here's my original issue:

![image](https://user-images.githubusercontent.com/101152/34629393-369eb2ca-f268-11e7-8b5c-ae144a1f35e0.png)

**Comment by borekb** [comment]
Now I've got a single window open, with a single document (not multiple "tabs"). Not sure is this is expected:

![image](https://user-images.githubusercontent.com/101152/34629493-9cc446b4-f268-11e7-86e1-c6d778912208.png)

**Comment by astoilkov** [comment]
Are you running `caret-4.0.0-beta1` or `caret-4.0.0-beta0`?

**Comment by borekb** [comment]
It's beta1.

**Comment by astoilkov** [comment]
We have made a new `beta2` update where the issue should be fixed. Can you try it out and see if the problem persists. Note that you will probably have issues the first time you run `beta2` but after restarting it everything should go back to normal.

**Comment by borekb** [comment]
The process tree gets killed (#598 is resolved) but I can still see the taskbar icons issue:

![image](https://user-images.githubusercontent.com/101152/34647999-8e73e6e4-f391-11e7-91fe-23a215a6468e.png)

Also, the jump list is confused:

![image](https://user-images.githubusercontent.com/101152/34648011-d3f00306-f391-11e7-98c1-0dca801b3804.png)

**Comment by astoilkov** [comment]
We also fixed the taskbar issue so the next update will include the fix.

Thanks for all the detailed information Borek!

**Comment by astoilkov** [comment]
We fixed the issue in the latest Caret 4.0 Beta release.

Closing this issue. Thanks for reporting.
