### ISSUE TITLE
Caret 4 Beta Processes persisting after close

### ISSUE THREAD

**Issue by netmasteroc3** [careteditor/caret#598]
I'm seeing a number of caret processes that persist running after caret is closed. Is there a reason caret-4-beta is doing this? Caret 3 doesn't leave processes hanging around when it quits.

When closed:
![caret closed](https://user-images.githubusercontent.com/28659714/34632325-c80eceb4-f242-11e7-9c06-7f1168667511.png)

When running:
![caret running](https://user-images.githubusercontent.com/28659714/34632328-cbec9700-f242-11e7-8c40-dddbd2dff1a5.png)

Win 10, 1709, build 16299.125.

**Comment by astoilkov** [comment]
Are you running `caret-4.0.0-beta0`? This was an issue which we fixed. You can look [here](https://github.com/careteditor/caret/issues/591).

Edit: It seems this issue still persists. We will let you know when we fix it.

**Comment by netmasteroc3** [comment]
I was running beta 1 (according to help > about).
I just updated to beta 2, and it seems to be resolved now.

**Comment by manuelbua** [comment]
Updating to beta2 also resolved it for me too, thanks!

**Comment by astoilkov** [comment]
Closing this then.

Thanks for the help in resolving this.
