### ISSUE TITLE
4.0 Beta: Nested list causes app to hang

### ISSUE THREAD

**Issue by klanchman** [careteditor/caret#599]
Working with a document that contains a "heavily" nested list (roughly 4+ levels) causes the app to hang. This includes loading a document, pasting a document into the editor, and editing a document. 

When editing, the app hangs after each keypress when editing the region with the list. Editing regions without the list is normal.

Having more items in the list causes the app to hang longer. Having more complicated formatting in the list (e.g. italics, bold, links, etc) causes the app to hang longer.

## Environment

Caret version: 4.0.0-beta2
OS version: macOS High Sierra 10.3.2 (17C88)
Tested on 2 different machines and the behavior was the same.

----

The sample document below causes the issue to occur

```
# A Slow Document

This document loads slowly

## Editing here is fine

You can edit this area without any issues

----

## Editing here is slow
- Sample text
  - Sample text
  - Sample text
    - Sample text
      - **Bold**, _italics_, ~~strikethrough~~, sample text
      - [Sample text](http://example.com)
      - `Sample text`
      - [ ] Sample text
      - Sample text :wink:
    - Sample text
      - Sample text
      - Sample text
      - Sample text
      - Sample text
    - Sample text
    - Sample text
      - Sample text
      - Sample text
```

**Comment by borekb** [comment]
I can confirm this. An example document that is already very slow to me is:

```
- Item
    - Something
    - [x] Test
    - [ ] Test
    - [x] Test
    - Something else
    - Possible improvements:
        - Here
    - Example item:
        - One
        - Two
            - Nested 1
            - Nested 2
```

Add a couple of nested list items and it will soon become unusable.

Maybe as a hint, the highlighting is not correct either:

![image](https://user-images.githubusercontent.com/101152/34650897-b3ee5698-f3c8-11e7-997c-5cf89c74e072.png)

**Comment by astoilkov** [comment]
We fixed the problem in the new Beta update.

Closing this issue. Thanks for reporting it!
