### ISSUE TITLE
file browser only finds text files

### ISSUE THREAD

**Issue by debrouwere** [careteditor/caret#6]
The file browser does not display images or other files present in the current directory. If you type a filename manually, the app says the file does not exist even when it does. One common use-case for the file browser is to insert links to images, so it'd be nice to have images be visible in the browser, or at least to not report them as missing if they do exist.

**Comment by erusev** [comment]
ah, that's a great point, we'll fix that, thanks

**Comment by astoilkov** [comment]
This is implemented in the latest release.

You should get an in-app update notification some time this week.

Thanks a lot for the suggestion. :)
