### ISSUE TITLE
Alerting when a file is "Dirty"

### ISSUE THREAD

**Issue by anandrajaram** [careteditor/caret#60]
The multiple window support is great! But I'd like an enhancement. Here is the scenario: 

* File A is currently open, and I am in the process of editing it (and it is dirty, meaning it has unsaved contents). 
* I open File B from Finder, Before opening File B, caret prompts me to save File A before opening File B. 

I am not sure why this matters in a multiple window setup. I'd like to be able to open File B right away regardless of the status of File A.

**Comment by erusev** [comment]
Do you mean that file B should get opened in a new window? Tnx.

**Comment by anandrajaram** [comment]
File B is opened in a new window, but before it is opened I get a prompt to save File A. Hope that clarifies. 






On Sat, Apr 2, 2016 at 10:59 AM -0700, "Emanuil Rusev" <notifications@github.com> wrote:












Do you mean that file B should get opened in a new window? Tnx.

**Comment by erusev** [comment]
Thanks, we'll fix that.

**Comment by astoilkov** [comment]
Hi @anandrajaram,

I am happy to say this is resolved in the latest version of Caret. Now files opened from Finder open in a new window.

Closing this issue. You could check out the improvement and if you have any comments do not hesitate to write us back.
