### ISSUE TITLE
Trim pasted license when verifying

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#601]
When I tried copy pasting my licence from gmail there was a trailing space that got copy pasted over to the app causing it to fail to activate. It would be nice if you ignored leading or trailing spaces when verifying licences.

**Comment by astoilkov** [comment]
Great suggestion. Will implement this. Thanks a lot for the suggestion.

**Comment by astoilkov** [comment]
This is now implemented in the latest Caret 4.0 Beta.

Closing this issue. Thanks for the awesome suggestion.
