### ISSUE TITLE
Reveal in explorer doesn't work

### ISSUE THREAD

**Issue by xanderberkein** [careteditor/caret#602]
Reveal in explorer (the option of the context menu in the Files sidebar) doesn't work for me. Nothing happens when I click on it.

I'm on Windows 10, using Caret 3.4.6

**Comment by astoilkov** [comment]
Hi @xanderberkein,

We have tested Caret 3.4.6 under Windows 10 and the context menu option works as expected. However, it looks like it doesn't focus the File Explorer but just opens a new window without focusing it. Is it possible you have a hidden taskbar which prevents you from seeing the newly opened window?

**Comment by xanderberkein** [comment]
Huh, it does seem to work indeed. I could've sworn it didn't yesterday, but maybe I didn't notice it since I had some other File Explorer windows open. Thanks for the response!
