### ISSUE TITLE
Error after attempting to "Restart" to update

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#607]
Update notification came, probably for [4.0.0-beta5](https://github.com/careteditor/beta/releases/tag/4.0.0-beta5), but clicking "Restart" only leads to this error:

```
{
    "message": "Cannot read property 'hide' of undefined",
    "version": "4.0.0-beta4",
    "os": "Windows 10",
    "path": "C:\\Users\\borek\\AppData\\Local\\caret-beta\\app-4.0.0-beta4\\resources\\app.asar\\extensions\\Updates\\Updates.js",
    "code": "caret.quitting=!0,this._not",
    "line": 5,
    "column": 1839,
    "stack": [
        "at HTMLSpanElement._quitAndInstall ((C:\\Users\\borek\\AppData\\Local\\caret-beta\\app-4.0.0-beta4\\resources\\app.asar\\extensions\\Updates\\Updates.js:5:1839)"
    ]
}
```

**Comment by astoilkov** [comment]
This was a bug in `4.0.0-beta4` which is now fixed in `4.0.0-beta5`. Note that the app is successfully updated only the Restart button doesn't work.

**Comment by borekb** [comment]
On Windows 10, beta5 freezes right after the start, I tried both updating and installing from scratch, something is very wrong with it. I'm trying to find out more..

**Comment by borekb** [comment]
It freezes to the point that not even maximize / minimize / close buttons respond. But right-clicking Caret icon in taskbar and closing the window does so immediately, without the typical "Caret is not responding", so I'm wondering what it could be. Did you update Electron in beta5?

**Comment by astoilkov** [comment]
I found the problem. I will make a new release now.

**Comment by astoilkov** [comment]
This is now fixed.

**Comment by borekb** [comment]
👍 , fast response as always!
