### ISSUE TITLE
Export as HTML

### ISSUE THREAD

**Issue by instanceofme** [careteditor/caret#61]
I guess it may be simple enough to implement if it's already half done in copy as HTML and as an intermediate step for PDF export? Maybe it's not that simple but if it can be a quick win, I'd take it!

Two main use cases for me:
- Exporting publishable HTML pages (yes, obvious is my middle name) with the same style than Caret preview / PDF
- Fine-tuning the adjustments I make in an inline `<style>` before exporting to PDF.  
  Currently I do that by trial-and-error (add a wildly guessed CSS rule, export PDF, check what's amiss, repeat).

**Comment by erusev** [comment]
Thanks, Adrien Obvious ;)

We'll discuss it an well let you know, but before that, we need to finish the Windows release as well as the new version of the website (which we are very excited about).

**Comment by astoilkov** [comment]
Export to HTML is now available in the Caret 2.0 release.

Closing this issue. Thanks for the feature idea.

**Comment by instanceofme** [comment]
Thanks, Adrien Obvious is very happy!
