### ISSUE TITLE
Auto-save?

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#613]
I just noticed that Caret 4.0.0-beta6 is auto-saving my documents. I think that on my other computer, this was not happening, I was seeing the dirty marker (`*`) and had to press cltr+s manually. So I'm confused.

If auto-save is the new behavior of v4, I'd appreciate an option to disable it.

**Comment by astoilkov** [comment]
Starting from Caret 4.0 (Caret 4.0.0-beta0) we now auto-save all documents. Why do you need to disable the auto-save? What are your scenarios for not wanting auto-save?

**Comment by borekb** [comment]
Google Drive uploads a file as soon as it is saved, and stores that as a revision, so saving every second or two messes up my revisions. Continuous upload could also be a bit of a problem with larger files and on slower / limited data connections.

**Comment by astoilkov** [comment]
If the auto-save saves the file only when you switch to another app will that be ok with you?

**Comment by aheidelberg** [comment]
Also, you might just want to try something out or see how something looks in a larger file that already has lots of content. When you then want to go back you would have to cmd+z the whole way instead of just closing without saving.

If you are even willing to only trigger auto-save on app switching, why not just give us an option?
Auto-save enabled would still be the default obviously.

**Comment by borekb** [comment]
App-switching doesn't seem to me like an intuitive point of when to save. If it's called auto-save, it should probably auto-save instantly.

I've used some tools that have auto-save and an option to disable that feature. I've had periods when I had auto-save on, i.e., in Jetbrains IDEs, but sometimes I decided to turn it off, usually to prevent auto-triggering of certain processes that watch file changes.

I think an option would be useful – almost a must for me (I've switched to v3 for now).

**Comment by astoilkov** [comment]
@aheidelberg Do you know that the app has a `File -> Revisions` functionality that you can use to revert to a revision after you have made a lot of changes instead of using `Cmd+Z`?

@borekb I think auto-save functionality purpose is to ensure that the file is always saved without worrying about it. Why do you think app-switch isn't a good moment to save when it can ensure that the job gets done?

We try to make Caret as minimalistic as possible. This is why we try to understand exactly why our users need an option for something before adding it. This ensures us that we don't end up with a bunch of options we need to support but aren't really useful.

**Comment by borekb** [comment]
> We try to make Caret as minimalistic as possible. This is why we try to understand exactly why our users need an option for something before adding it. This ensures us that we don't end up with a bunch of options we need to support but aren't really useful.

I applaud this approach, however, disabling auto-save is really important for me because of the unfortunate side-effect mentioned above.

Saving on app switch is an interesting idea but as I thought whether it would solve things for me, the answer is no. For example, if I switched to another app to copy something, it would create a new revision for me. If I clicked a Windows notification, it would create a new version for me. Etc.

Also, I don't think I would call that feature "auto-save" if I can write 1000 words without that work ever being saved (if I don't switch).

Hope this provides some more context.

**Comment by astoilkov** [comment]
Thank you both for joining the discussion and for the detailed explanations. After thinking about it we decided to implement an option for auto-save.

Thanks!

**Comment by aheidelberg** [comment]
> Do you know that the app has a File -> Revisions functionality that you can use to revert to a revision after you have made a lot of changes instead of using Cmd+Z?

I did not know about Revisions, thanks for pointing that out. When is a Revision created?

**Comment by astoilkov** [comment]
@aheidelberg revision is created in these cases:
- when a file is opened for the first time in Caret
- after 400 characters difference between the last revision and the new (the editor waits for the user to input a new line so the diff is more clean)

**Comment by borekb** [comment]
If you included the option in beta9, I would be able to continue beta-testing for you :)

**Comment by astoilkov** [comment]
We have implemented an option to disable auto-save. Hope you like it.

Closing this issue. Thanks for the feedback.

**Comment by slawek-survicate** [comment]
@astoilkov is auto save disabled by default now? I doesnt work for me in `4.0.0-rc22`. What's the option name?

**Comment by astoilkov** [comment]
Hi Slawek,

No. It is enabled by default. The option could be toggled in the application menu under `File -> Autosave`.

Hope that helps.

**Comment by slawek-survicate** [comment]
@astoilkov weird, it has not been enabled. Now it works thanks. BTW its confusing that part of options is in preferences.md and part is clickable from menubar. It should be available to switch in both.

**Comment by astoilkov** [comment]
Yes. I totally agree. We are reworking preferences for the next major release so everything will be more easy to understand.
