### ISSUE TITLE
Download button on Caret website reloads webpage

### ISSUE THREAD

**Issue by JamoDevNich** [careteditor/caret#614]
The download button on the Caret website reloads the webpage after showing the version selector underneath. Inspecting it shows a blank location... maybe hashtag was intended to go there instead?

![Inspect Screenshot](https://i.imgur.com/WjtMh9Q.png)

**Comment by erusev** [comment]
Fixed. Thanks so much for reporting this!

**Comment by borekb** [comment]
Related to this, it seems that the Beta download link points to beta4, not the current beta6.
