### ISSUE TITLE
Format links as list breaks markup

### ISSUE THREAD

**Issue by Amparose** [careteditor/caret#616]
Steps to reproduce in [non]beta:

- Paste/create a number of markdown links separated by a single end-of-line break.
- Highlight and select menu > Format > List.

Result is the unordered list is created but the first square bracket of each markdown link is removed and thus markup is broken.

**Comment by astoilkov** [comment]
This is now fixed in the latest version of Caret 4.0 Beta.

Closing this issue. Thanks for reporting.
