### ISSUE TITLE
Synxtax assistance acts weirdly on unicode(non-english) characters

### ISSUE THREAD

**Issue by ghost** [careteditor/caret#617]
While I am writing unicode(non-english, Korean) characters, Caret writes the string weirdly....

The following example shows what happens when I am writing the same string of the first row.

(When I am writing the first character)
![any_0121193616](https://user-images.githubusercontent.com/35654355/35193195-8fcadfdc-fee2-11e7-80c3-a27572d3ea76.gif)

The following diagram shows the final result.
![image](https://user-images.githubusercontent.com/35654355/35193186-8356a722-fee2-11e7-89b2-db23160a0cf0.png)

Could you check why that happens? Thank you.

**Comment by astoilkov** [comment]
Hi @YiruDanielJeon,

This issue is fixed in the Caret 4.0 Beta available for download [here](https://caret.io/4beta/).

Closing this issue. Thanks for reporting.

**Comment by ghost** [comment]
Thank you. I will try the new version! :)
