### ISSUE TITLE
LaTeX looks different in v4 beta

### ISSUE THREAD

**Issue by aheidelberg** [careteditor/caret#620]
This is how it looks in v3
<img width="638" alt="screen shot 2018-01-24 at 12 21 03" src="https://user-images.githubusercontent.com/22153826/35329728-2ed8c1be-0101-11e8-9242-13eef801cddc.png">
And this is how it looks in v4 beta 6
<img width="566" alt="screen shot 2018-01-24 at 12 21 20" src="https://user-images.githubusercontent.com/22153826/35329727-2eb92f7a-0101-11e8-9ccc-746b5add2a67.png">

Is there any reason behind this change?
Personally I prefer the v3 look and would love an option to choose the style.

**Comment by astoilkov** [comment]
You mean that the Caret 4.0 has smaller font size? You can take a look at the [discussion here](https://github.com/careteditor/caret/issues/406) that explains why we reduced the default size.

If you want to increase the size of LaTeX you can create a custom CSS preview theme via `View -> Preview Theme -> Add Theme` copy one of the existing ones and change the size of `.katex-display` `font-size` property.

I am closing this issue. If you have any additional questions don't hesitate to contact us.

**Comment by aheidelberg** [comment]
That's not what I meant, size has nothing to do with it. You can clearly see the difference in some letters. For example the p and the curly braces in my previous post and the x, n, k and the "element of" symbol (\in) in the screenshots below.
**v3**
![x3](https://user-images.githubusercontent.com/22153826/35338252-b01ef65a-011d-11e8-843f-d8aab46b0597.png)
**v4**
![x4](https://user-images.githubusercontent.com/22153826/35338251-b002271e-011d-11e8-9ae6-add0f3b64563.png)

Also the | symbol (\lvert, \rvert) doesn't render correctly in the beta.
**v3**
![abs3](https://user-images.githubusercontent.com/22153826/35338067-2c2f100a-011d-11e8-9c7f-7eb59df75904.png)
**v4**
![abs4](https://user-images.githubusercontent.com/22153826/35338066-2c11e6ce-011d-11e8-9bcd-e9c1e5978288.png)

**Comment by astoilkov** [comment]
Can you send us the LaTeX expressions plain format so we could test them?

Thanks in advance.

**Comment by aheidelberg** [comment]
https://gist.github.com/aheidelberg/c62597377e257bb3b7c582ba141bc7e3
I put a couple more in there. I also just compiled it with normal LaTeX and it looks more like in v3.

Did you maybe switch from KaTeX to MathJax (or MathJax to KaTeX)?

**Comment by astoilkov** [comment]
This was actually a bug in Caret 4.0. We fixed it internally and the next release will include it. I will write here when this happens.

Thanks for reporting!

**Comment by astoilkov** [comment]
Hi @aheidelberg,

The fix now landed in the latest Caret 4.0 Beta release.

Closing this issue. Thanks for reporting!
