### ISSUE TITLE
Preview doesn't scroll with the editor

### ISSUE THREAD

**Issue by aheidelberg** [careteditor/caret#621]
Sometimes the preview doesn't scroll correctly with the editor.
I'm not sure how to reproduce it / what causes it exactly but after scrolling around a bit it always happens.
This only happens in the beta for v4
![scroll](https://user-images.githubusercontent.com/22153826/35342112-86e91cf2-0127-11e8-8217-d0ab2c43bd9d.gif)

**Comment by astoilkov** [comment]
Is it possible you send us the document so we can test with it?

Thanks in advance.

**Comment by aheidelberg** [comment]
[Raw Gist](https://gist.githubusercontent.com/aheidelberg/041c51bce87789b6438f7082648c6ddf/raw/dd320f2b4952a68810fd427d596df0acd04131ca/scroll.md)

**Comment by chriskrycho** [comment]
FWIW, I see the same problem in any document with lots of code blocks.

**Comment by astoilkov** [comment]
We think we fixed the problem the problem in the latest Caret 4.0 Beta. Can you test it to verify it? 

Thanks in advance.

Closing this issue. If we haven't fixed the problem I will reopen it.
