### ISSUE TITLE
v4 beta: Search missing from macOS menu bar

### ISSUE THREAD

**Issue by chriskrycho** [careteditor/caret#623]
I use <kbd>⌘</kbd><kbd>⇧</kbd><kbd>?</kbd> followed by typing to invoke macOS' menubar **Search** functionality pretty often when I want to quickly jump around to commands in the menu bar that I may not have mapped. As of the Caret 4 beta, this is missing, and I'm hobbled as a result. <kbd>⌘</kbd><kbd>⇧</kbd><kbd>?</kbd> still focuses the menubar **Help** item, but since there's no **Search** field available, no dice.

**Comment by astoilkov** [comment]
Hi @chriskrycho,

This is now fixed in the latest Caret 4.0 Beta release.

Closing this issue. Thanks for reporting!
