### ISSUE TITLE
X-Callback-URL Scheme?

### ISSUE THREAD

**Issue by menduo** [careteditor/caret#628]
Will caret support X-Callback-URL scheme? So I can link from other apps.

**Comment by astoilkov** [comment]
Hi @menduo,

Yes. We are considering implementing it. Can you share for what you would use the it?

Thanks in advance.

**Comment by menduo** [comment]
@astoilkov For example: add a todo in Things or OmniFocus, append a callback link to the notes, so I can jump to Caret to see details when I'm check my todo list.
