### ISSUE TITLE
Customize shortcuts

### ISSUE THREAD

**Issue by imapirate** [careteditor/caret#63]
On my system, `^ + Space` is a global shortcut taken by CulturedCode Things –and actually I know plenty of apps out there pretending to use it– so I can't take advantage of context commands. Can you provide a way to customize shortcuts, please?

**Comment by contentkraft** [comment]
Same problem here. On the German or Romanian layout it's not possible to use `^ + space` .

**Comment by imapirate** [comment]
Well @contentkraft if your issue is related to keyboard layout, you may also use a remapping utility, like [karabiner](https://pqrs.org/osx/karabiner/). Works pretty well :)
But yeah... let us customize please ^_^

**Comment by erusev** [comment]
Makes sense, we'll see what we can do.

**Comment by arda-** [comment]
Bump. If this could be configured in preferences using yaml (similar to Atom's solution for keybindings), I'd be over the moon.

**Comment by astoilkov** [comment]
Keyboard shortcuts can now be customized in the new Caret 2.0 release. We hope you like it and @arda- it's YAML.

Closing this issue. Any feedback is more than welcome.
