### ISSUE TITLE
Auto-save enhacements

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#634]
I frequently find myself wanting to use Caret as a quick brain dump. Writing stuff down quickly and moving on. I find the friction of having to name and save a file after I'm done to be in the way of my flow.

I would like to therefore propose an enhancement to auto-save, which is to automatically save an untitled document using the default "timestamp.md" file name in the root of the current open folder once I close the Caret app. 

Maybe there's a better UX to solve the problem I have, so whatever you think makes sense I would appreciate immensely.

**Comment by astoilkov** [comment]
Hi Sammy,

I don't fully understand you. You can close Caret without the need to save untitled files. Why do you save them every time after you are done?

**Comment by sguergachi** [comment]
Well I want it to actually save the file to the current folder. In my case I sync files using dropbox, and would like to access them on different devices. Currently Caret keeps the untitled document alive when I close and re-open, but doesn't actually save. This is the behaviour I'm requesting be changed to enable my use case.

**Comment by astoilkov** [comment]
Unfortunately, the use case is very specific and many users will complain if we save every untitled in the current folder. However, I could propose two different workflows that could make handling untitled documents easier:
- Open the Files popup using `Ctrl+T` or `Ctrl+P`, type the name of the new file you want to create and hit `Alt+Enter` to create it
- Focus the sidebar using `Ctrl+Shift+B` and then hit `Ctrl+N` to create a new file

This two workflows should make creating and managing new files you want to save on disk easier.

I am closing this issue. If you have additional questions or suggestions don't hesitate to write back.

**Comment by borekb** [comment]
I use a file called `temp.md` for quick thoughts that are saved and synced between my devices. If the contents is something I'd like to keep longer and not overwrite it, I just copy it to a new file (Ctrl+N) and save it quickly using Ctrl+S and using the default timestamp-ish format (it's super-useful that Caret suggests a good name by default!).

**Comment by slawek-survicate** [comment]
@astoilkov you can just add preferences option for this - no need to change default behaviour. I use dropbox for syncing and it would be super useful for me.
