### ISSUE TITLE
Ctrl + N doesn't highlight new tab

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#635]
If I have a doc open and press Ctrl+N to open a new document in a tab, the current tab isn't highlighted: 
![image](https://user-images.githubusercontent.com/615386/35485880-825ef1de-0433-11e8-84e1-f3a52d490b89.png)

**Comment by sguergachi** [comment]
There's also a bug related to this, where when I select the "Untitled" tab (which should be empty) it shows me content from the left tab (which is not empty).

**Comment by astoilkov** [comment]
Hi Sammy,

Does this happen to you every time becacause I can't replicate it?

**Comment by sguergachi** [comment]
Hmm I can't seem to replicate it anymore, don't know how I got the application into a state where this happens repeatedly.

**Comment by astoilkov** [comment]
We had a similar issue in Caret 4.0 Beta 7. For now, I will close this issue and if you replicate it again do not hesitate to write us back so we can reopen it.
