### ISSUE TITLE
V4 Beta 8: Underscores in file names make tab titles italic

### ISSUE THREAD

**Issue by bellebethcooper** [careteditor/caret#636]
Maybe this is by design, but I can't think of why it would be expected behaviour. When I open a file with underscores in the filename, the tab's title becomes italic.

See example here, where filenames with hyphens aren't italic, but those containing underscores *are*:
<img width="654" alt="screen shot 2018-01-29 at 4 28 32 pm" src="https://user-images.githubusercontent.com/4826241/35494837-7afcdb5c-0511-11e8-9ca3-25809f9bc7f8.png">

**Comment by erusev** [comment]
We use _italic_ to indicate that the file does not belong to the current folder (outside files).
It's probably a coincidence that the outsider files in your case are also the only ones that have underscores.

We're working on a documentation section of the website that should explain this.

**Comment by bellebethcooper** [comment]
Ah, thanks. Sorry for the confusion!
