### ISSUE TITLE
Playing with tables

### ISSUE THREAD

**Issue by imapirate** [careteditor/caret#64]
Trying to trigger recognition without success :/
What does the tables workflow look like?

The following error has occurred:
```
{
    "message": "Invalid count value",
    "version": "1.2.2",
    "platform": "darwin",
    "os": "15.4.0",
    "path": "web/Editor.Markdown.Table.js",
    "code": "_0xa12exd=_0x9a85[37][_0x9a85[36]](_0xa12exc+_0xa12ex4[_0x9a85[28]]+_0xa12ex4[_0x9a85[31]]-2)",
    "line": 5,
    "column": 4728,
    "stack": [
        "at String.repeat ((native)",
        "at Object.EditorMarkdownTable.(anonymous function)._autocompleteTable (web/Editor.Markdown.Table.js:5:4728)",
        "at Object.EditorMarkdownTable.(anonymous function)._beforeUpdate (web/Editor.Markdown.Table.js:5:8159)",
        "at loopEvents (web/Events.js:5:229)",
        "at Object.Events.trigger (web/Events.js:5:527)",
        "at Object.Editor.(anonymous function)._update (web/Editor.js:5:14427)",
        "at Object.Editor.(anonymous function)._oninput (web/Editor.js:5:19174)"
    ]
}
```

**Comment by erusev** [comment]
It recognizes regular tables like:

```
| Model               | Year | Price |
| ------------------- | ---- | ----- |
| MacBook             | 2015 | $1299 |
| MacBook Air 11"     | 2014 | $899  |
| MacBook Air 13-inch | 2014 | $999  |
```

There are some limitations. It won't recognize a table where rows don't start with a pipe ("|") or tables that have colon alignment like:

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

We are working on fixing these limitations.

As to the error, we'll investigate, thanks for reporting!

**Comment by imapirate** [comment]
Yep, makes sense. However, I was expecting some form of bootstrapping, as it's tedious to build it from scratch. I mean something like `t3*5 + ↹` to scaffold a 3 column by 5 rows table, and put the _caret_ in row 1 column 1. What do you think?

**Comment by erusev** [comment]
Yes, I agree and we are working on something like that.

Btw, you can navigate cells using <kbd>tab</kbd>? It's not a big deal, but I thought that if you work w/ tables you might like to know it.

**Comment by astoilkov** [comment]
Hi @imapirate,

The issue that you reported is fixed in the latest Caret release.  Regarding the easier creation of tables - we have some ideas that we will implement in the future.

Closing this issue.
