### ISSUE TITLE
Spell check not working in 4.0.0-beta8

### ISSUE THREAD

**Issue by ghost** [careteditor/caret#640]
Hi all at Caret,

I'm running Caret version 4.0.0-beta8 on Fedora 27. Misspelled words are not underlined, and I am unable to bring up the context menu to correct them.

In the screenshot below, Caret version 3.4.6 is running on the left and 4.0.0-beta8 is on the right. Configuration files are entirely fresh. The 'Check spelling' option is enabled.

![dinosuar](https://user-images.githubusercontent.com/35947921/35549190-2dbd3968-0539-11e8-8814-bbda2cfb81ea.png)

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update. 

Closing this issue. Thanks for reporting this and for the detailed information provided.
