### ISSUE TITLE
[Feature Request]TOC navigation support in Preview Mode

### ISSUE THREAD

**Issue by menduo** [careteditor/caret#645]
Hi:

In preview mode,  `cmd` + `r` show the TOC, then click an item, caret doesn't jump into the section, hope you can add this feature.

(But it works fine in edit mode.)

Thanks.

**Comment by astoilkov** [comment]
Hi @menduo,

I wasn't able to replicate the problem. You can look at the GIF below.

![2018-02-08 10 01 57](https://user-images.githubusercontent.com/884810/35961721-4cd9a6d0-0cb7-11e8-9a2a-cdaaea947f97.gif)

**Comment by menduo** [comment]
I'm sorry for the ambiguous, I mean the Preview Only mode, click `View -> Preview` but not `View -> Show Preview`, not the live preview.

**Comment by astoilkov** [comment]
Hi @menduo,

I was still not able to replicate the problem using the full screen preview. You can take a look at the GIF below.

![2018-02-16 12 06 07](https://user-images.githubusercontent.com/884810/36302666-ecb18c80-1311-11e8-8882-5f75bd8caa44.gif)
