### ISSUE TITLE
[Feature Request] add TOC while export to PDF

### ISSUE THREAD

**Issue by menduo** [careteditor/caret#646]
Hi:

Would you please add TOC in the PDF exported? That will be great.

Not add `[[TOC]]` to page content.

Thanks a lot.

**Comment by astoilkov** [comment]
Hi @menduo,

I am not sure I understand you correctly. We do include the TOC in the exported PDF. What do you mean by `Not add [[TOC]] to page content.`?

**Comment by menduo** [comment]
Sorry for my poor English. See the picture below:

the left side, missing the `TOC`. The right side, the `TOC` is generated by the `[[TOC]]` syntax(this is controlled by me ).

And I hope caret can add `TOC` to the left side. 

![image](https://user-images.githubusercontent.com/13566062/35966740-af0f53da-0cf9-11e8-8e20-edf83344ea62.png)

**Comment by astoilkov** [comment]
Hi @menduo,

The API we use to export to PDF doesn't support modifying the `Table of Contents` section in the exported document. For now what you request is not possible.

Thanks for the understanding.

**Comment by menduo** [comment]
@astoilkov Got it.
