### ISSUE TITLE
Multiple tabs within window?

### ISSUE THREAD

**Issue by gandalfsaxe** [careteditor/caret#650]
Hi,

It'd like to see multiple tabs within a window, similar to web browsers. If it's there, I definitely missed it :)

**Comment by astoilkov** [comment]
Hi,

You could open new tabs in the same window by doing one of the following:
 - Open `Go->To File...` find the file you want to be opened in a new window and press `Cmd/Ctrl+Enter`
 - Hit `Cmd/Ctrl+Enter` in the sidebar
 - Right-click on a file in sidebar and select `Open in New Tab` option
 
Hope that helps.

**Comment by gandalfsaxe** [comment]
I can' get any of that to work.

If I right click a file in the sidebar, there is no such option:

![image](https://user-images.githubusercontent.com/12127864/36173926-e5766b24-110a-11e8-8ae1-df3139c48708.png)

**Comment by astoilkov** [comment]
Sorry. I assumed you are using Caret Beta 4.0 where tabs are available. You will need to wait for the beta channel to hit stable so you could use tabs.

**Comment by gandalfsaxe** [comment]
Ok :) I hope it will work the standard way that tabs work in standard Mac apps, i.e. Cmd+T for new tab, Cmd+W to close tab.

**Comment by astoilkov** [comment]
It will work the way I described in the previous post. Each tab will be opened explicitly by hitting `Cmd+Enter` on files in `Cmd+T` or sidebar or with the context menu. `Cmd+W` will close the currently opened file.

Closing this issue. If you have more questions don't hesitate to ask.

**Comment by gandalfsaxe** [comment]
Where do I get the beta?

**Comment by astoilkov** [comment]
You can download it from our [home page](https://caret.io). Just click the "Download for Mac" button.

**Comment by gandalfsaxe** [comment]
Thanks. Is there a change log somewhere so I know what's different from the latest stable release?

**Comment by astoilkov** [comment]
https://caret.io/releases

**Comment by gandalfsaxe** [comment]
How do you prefer beta feedback?

**Comment by astoilkov** [comment]
You can create GitHub issues which include the word beta in the title.

Thanks in advance for testing out the beta!
