### ISSUE TITLE
Offline Activation? (without Internet connection)

### ISSUE THREAD

**Issue by ghost** [careteditor/caret#651]
Hi, I am using Caret very well and I want to use Caret in a computer where Internet connection is not available. (I installed Caret by using USB memory stick) However, I could not activate Caret. 

Is there any way that I can activate Caret in a computer without Internet? Thank you.

**Comment by astoilkov** [comment]
Hi @YiruDanielJeon,

Unfortunately, there is no way to activate Caret on a machine without internet access. Caret uses a licensing server to verify each license.

Sorry for the inconvenience.
