### ISSUE TITLE
Clicking on a character selects the character in the line below

### ISSUE THREAD

**Issue by BruceEckel** [careteditor/caret#654]
Not sure how to reproduce this. Windows 10
![image](https://user-images.githubusercontent.com/1001900/36322961-8edb1392-130c-11e8-9ef7-65a681e9e57c.png)

**Comment by astoilkov** [comment]
How often does this happen? Please let us know if you find a consistent way for replicating the issue.

Thanks for reporting this.

**Comment by BruceEckel** [comment]
Well, I installed a screen recorder to try to capture it, and then when I restarted Caret the problem had gone away. It *was* happening all the time, but restarting it seemed to fix it. I'll keep watching for it and repost the issue if it recurs.
