### ISSUE TITLE
Changing font size from "medium" to "+" causes the cursor to not align with text

### ISSUE THREAD

**Issue by bellebethcooper** [careteditor/caret#66]
![caretcursornotaligned](https://cloud.githubusercontent.com/assets/4826241/14631177/8aee7172-0655-11e6-8d21-3f2429799803.png)

If I open Caret 1.2.2 with a file open that I was previously working on, the font size is set to "medium". If I change it to the "+" font size, regardless of which theme I'm using, the cursor at the bottom of the file I have open doesn't align with the text anymore. Added a screenshot for reference.

**Comment by erusev** [comment]
Belle, does this happen to all files or just that one file? I tried to reproduce the issue w/ a bunch of files but no luck so far :(

**Comment by bellebethcooper** [comment]
Ah, I think you're right. I don't know what the problem is, but I can only reproduce it with that particular file.

**Comment by erusev** [comment]
Hm, do you think you can send me the text to erusev@caret.io or the part of it that causes the issue? This would save us a lot of investigation.

**Comment by bellebethcooper** [comment]
Done!

**Comment by erusev** [comment]
Thanks, Belle, we'll see what we can do.

**Comment by astoilkov** [comment]
Hi @bellebethcooper,

We have introduced a new Caret release that should fix the issue. Could you update the application and take a look if you could still replicate the problem.

Thanks in advance.

**Comment by bellebethcooper** [comment]
@astoilkov I'm not able to reproduce this in the latest version. Seems to be fixed! Thanks a lot.

P.S. When checking for updates in 1.2.2 Caret says no updates available. I had to re-download the trial version from your website to get the update.

**Comment by astoilkov** [comment]
Great to hear that. We know about the update issue - it just says there isn't an update but the application is currently downloading the app in the background.

Closing this issue.

P.S. If you want to track the update mechanism problem you could open a public issue and we will close it when we fix it.
