### ISSUE TITLE
Prompt to reload / autosave bug in 4.0-beta9

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#667]
Steps to reproduce on Windows 10:

1. disable autosave
2. open a file, edit it, _don't save_ (a dot is visible next to the file name)
3. go to another app
4. return back to Caret

I get this:

![image](https://user-images.githubusercontent.com/101152/36658585-83c02b56-1ad1-11e8-840f-da1879e7d35d.png)

Reload goes back to the last saved state of the file, losing the newer changes. Fortunately, I was able to press Undo (or was is Redo?) to get my changes back.

It's not happening always but quite regularly.

**Comment by borekb** [comment]
This just happened to me with with rc1 as well.

**Comment by astoilkov** [comment]
Yes. We haven't fixed that yet.

**Comment by astoilkov** [comment]
We had to do a refactoring to fix this but we haven't tested enough to include it in this release.

**Comment by borekb** [comment]
No problem. It also happens when I save a file, type one additional character and then switch to another app and back.

**Comment by borekb** [comment]
I've been using Caret 4.0.0-rc1 for several hours today, this is a clear no. 1 annoyance for me so 😉 😉 hopefully this is fixed soon :)

It is unfortunately also triggered by a clipboard manager which I use heavily. (I use ClipX but I guess it would happen with any of them as Caret technically loses focus.)

**Comment by astoilkov** [comment]
We have merged the branch containing the fix and refactorings. The issue will be fixed in the next beta release.

**Comment by astoilkov** [comment]
This is now finally fixed in the latest Caret Beta RC3 update.

Closing this issue. Thanks for reporting.

**Comment by borekb** [comment]
Just saw it in rc4. I opened a file, made some edits to make it dirty, then Alt+Tab to another app and Alt+Tab back.

![image](https://user-images.githubusercontent.com/101152/38057315-4e4e3712-32df-11e8-8bd8-039a8c971fd0.png)

**Comment by astoilkov** [comment]
Ok. This should finally be fixed in the latest beta update.

Closing this issue. Thanks for the patience.

**Comment by borekb** [comment]
Awesome, looks good in rc5!
