### ISSUE TITLE
Inserting blank lines trashes preview with multiple %20

### ISSUE THREAD

**Issue by olvlvl** [careteditor/caret#682]
Hi,

I'm trying out v4.0.0-beta9 and when I'm inserting blank lines multiple `%20` are inserted in the preview, trashing it. Here an example:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/155998/37522692-fd9277ac-2924-11e8-8517-7b7ad2e281af.png">

**Comment by astoilkov** [comment]
Hi @olvlvl,

I can't seem to replicate the problem. Can you describe a specific scenario step by step which replicates the problem? This would be of great help.

Thanks in advance.

**Comment by olvlvl** [comment]
Hi,

Here is a sample document:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ante dolor, rutrum non ornare eu, volutpat et nisi. Nam varius nulla ut elit molestie, nec volutpat nulla tincidunt. Nunc nisi nulla, porta at nisl non, pellentesque dapibus purus. Donec dictum erat in dui bibendum, laoreet ultrices urna blandit. Morbi elit est, tempor et condimentum eu, aliquet a nisl. Vivamus justo mi, finibus ut sollicitudin ut, posuere nec libero. Maecenas eu est sit amet turpis ullamcorper luctus. 

- bibendum, laoreet ultrices urna blandit. Morbi elit est, tempor et condimentum eu, aliquet a nisl. Vivamus justo mi, finibus ut sollicitudin ut, posuere nec libero. Maecenas eu est sit amet turpis 
- bibendum, laoreet ultrices urna blandit [laoreet ultrices](https://example.com/?q=service%20locator&p=0) laoreet ultrices urna [bibendum, laoreet ultrices](https://example.com) bibendum, laoreet ultrices urna blandit. Morbi elit est, tempor et .
```

Insert a number of spaces after the first paragraph, it trashes the preview:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/155998/37548930-cf7bed60-297b-11e8-8e5e-daf92e9eb19e.png">

**Comment by astoilkov** [comment]
We fixed this issue in the latest Caret Beta update.

Closing this issue. Thanks for the detailed description.
