### ISSUE TITLE
Autosave marker not shown in File menu on Windows

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#686]
I see this for both checked and unchecked states of Autosave:

![image](https://user-images.githubusercontent.com/101152/37598058-70ae71c4-2b81-11e8-9000-d9cd087c3f6e.png)

The correct state is shown in the palette:

![image](https://user-images.githubusercontent.com/101152/37598087-88345958-2b81-11e8-9b6f-5304ae552675.png)

4.0.0-rc1

**Comment by borekb** [comment]
Also possibly related, there's an inconsistency in what the View menu shows and what is actually opened in Caret:

![image](https://user-images.githubusercontent.com/101152/37606585-17663060-2b96-11e8-8ce3-8ebf1c503d41.png)

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue.
