### ISSUE TITLE
Placing cursor at the end of misspelled word automatically displays suggestions

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#689]
When I move the cursor to this location and wait about a second, the suggestions automatically appear:

![image](https://user-images.githubusercontent.com/101152/37619411-b85c5cb0-2bb9-11e8-93f8-3c132dbb69ec.png)

Doesn't happen in the middle of the word.

**Comment by astoilkov** [comment]
This is a feature borrowed from macOS where every text editor does this. Is this something you don't like?

**Comment by borekb** [comment]
Oh if it's intentional I'm fine with that. It's not a UX convention on Windows but not a problem at all. Thanks for explaining.
