### ISSUE TITLE
Multiple screen issue

### ISSUE THREAD

**Issue by nap** [careteditor/caret#69]
I've noticed that if I take the application window from my retina display to an external monitor, the redraw of the application break.

![screen shot 2016-05-11 at 12 05 22 pm](https://cloud.githubusercontent.com/assets/2131451/15187867/ddaa883e-1770-11e6-84d2-94a93e11291e.png)

It also does something weird if I move the application back and forth between both display.
![screen shot 2016-05-11 at 12 05 51 pm](https://cloud.githubusercontent.com/assets/2131451/15187881/e3687cd6-1770-11e6-85b6-324f6784e709.png)

**Comment by erusev** [comment]
Thanks @nap, we'll see what we can do.

**Comment by astoilkov** [comment]
Hi @nap,

We have published an application update that should fix this issue. You can update to 1.3.0/1.3.1 and see if the problem still persists.

Thanks in advance.

**Comment by nap** [comment]
Works great now, thanks!

**Comment by astoilkov** [comment]
Happy to hear that. Closing this issue now.
