### ISSUE TITLE
Incorrect caret position in 4.0

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#690]
It reminds me of https://github.com/careteditor/caret/issues/271. It didn't happen up until now for me in 4.0.0-rc1 but now I get an incorrect caret (cursor) placement:

Let's start with this:

![image](https://user-images.githubusercontent.com/101152/37627286-0f1c2732-2bd4-11e8-9d41-282dbb57881f.png)

When I press "x", this happens:

![image](https://user-images.githubusercontent.com/101152/37627312-1ed91f2c-2bd4-11e8-8afc-a450117f9d21.png)

I can reproduce with a file that contains just this:

```
Recommended by Tom, not recommended by Dan.
```

**Comment by astoilkov** [comment]
This is now fixed in the Caret Beta RC2 release.

Thanks for reporting this and sorry for the inconvenience.

**Comment by borekb** [comment]
Wow, thanks for such a quick fix.
