### ISSUE TITLE
Caret 4 Beta RC1 Menu Mouseover/Activation Issue

### ISSUE THREAD

**Issue by netmasteroc3** [careteditor/caret#691]
The menu (hamburger menu) ignores ignores the mouse when the pointer is over the icon, but not when over the edges of the button. 

If I move my mouse over the edge of the menu area, it darkens (light theme), and if I click it will open the menu. If I then move my mouse over the 3 bars icon, the menu returns to the deactivated state (returns to non-shaded) and clicking will not open the menu.

Windows 10 64-bit build 1709.

Also tried uninstalling caret4-beta, and deleting the caret beta folders in App Data, then reinstalling with a fresh download just to be sure that there wasn't any weird things from the earlier betas persisting there.

**Comment by astoilkov** [comment]
This is now fixed in the Caret Beta RC2 update.

Closing this issue. Thanks for reporting.
