### ISSUE TITLE
Autocomplete widget UI color is inverted for Dark/Light mode

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#694]
I'm not sure why i didn't notice before, but now (`-rc2`) the UI color for the autocomplete widget (the one available via <kbd>CTRL+SPACE</kbd>) has inverted colors instead of following the `View->Mode` selection, that is, i get the Light version when in `Mode->Dark` and the Dark version when `Mode->Dark` is unchecked.

I'm not sure, but this may have started to happen after i switched to _Light mode_ and then back to _Dark mode_ (just to look at the other theme).

Unfortunately i can't seem to get a screenshot of it, will update the report if i'll be able to!

**Comment by astoilkov** [comment]
We fixed this in the latest Caret Beta.

Closing this issue. Thanks for reporting this.
