### ISSUE TITLE
Preview shows HTML entities instead of characters

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#696]
I how now at least twice encountered a strange situation where preview showed HTML entities (something like `%58%30...`) instead of rendered characters. Unfortunately, I didn't make a screenshot but the way to "fix" it was just to return to write mode, enter a single character somewhere, save the file and do preview again. I cannot even reproduce the issue right now but when I see it again, I'll try to provide more info.

**Comment by borekb** [comment]
Got one! It's from a private document which I need to blank out but at least something:

Source:

![image](https://user-images.githubusercontent.com/101152/37699280-2a7dd2be-2ce7-11e8-8f0b-d1b155be33ff.png)

Preview:

![image](https://user-images.githubusercontent.com/101152/37699238-e75b880a-2ce6-11e8-9ea7-b2c946d30057.png)

This time, changing and saving the document didn't help, I needed to switch to another file and back; then the preview fixed itself.

**Comment by manuelbua** [comment]
I'm not always able to replicate this, but when i do it's always happening on text appearing after a link such as `[this](https://google.com)`; for some reason it doesn't always happen, but i can also have it behave correctly after removing and re-entering the last round bracket.

**Comment by borekb** [comment]
This is probably a duplicate of #682, sorry for missing that. Feel free to close.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta release.

Closing this issue. Thanks for reporting.
