### ISSUE TITLE
Left arrow doesn't work about `1/ :emoji:`

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#697]
When I have a MD file with this contents:

```
1/ ☀️
```

, place my cursor after the sun emoji (at the end of line) and press the left arrow key, it gets stuck there:

![image](https://user-images.githubusercontent.com/101152/37759885-46250a68-2db5-11e8-9109-2f0c5c9c01f3.png)

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue. Nice catch by the way.
