### ISSUE TITLE
Clicking 'Export to HTML...' does nothing in 4.0.0-rc2

### ISSUE THREAD

**Issue by ghost** [careteditor/caret#698]
Hi all at Caret,

I'm running Caret version 4.0.0-rc2 on Fedora 27. The 'Export to HTML...' option in the File menu does nothing when clicked. The 'Export to PDF...' option, on the other hand, does work. There's also a strange double-line separator under the 'Export to HTML...' option that doesn't look like it's intentional.

![export-to-html](https://user-images.githubusercontent.com/35947921/37793558-4dfa86fc-2dcc-11e8-8f7a-058a1170ec97.png)

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue. Thanks for reporting.
