### ISSUE TITLE
Pressing CMD+[minus] or CMD+[plus] causes error

### ISSUE THREAD

**Issue by grrowl** [careteditor/caret#7]
It's so easy to report a bug, I'm sure you'll get a lot of these ;)

Pressing CMD+[minus] or CMD+[plus]  (common shortcuts for zoom) causes the following error to occur:
```
{
    "type": "javascript-error",
    "message": "Uncaught TypeError: Cannot read property 'call' of undefined",
    "path": "/Applications/Caret.app/Contents/Resources/app.asar/web/Events.js",
    "line": 5,
    "platform": "darwin",
    "os": "MacIntel"
}
```

**Comment by erusev** [comment]
This is fixed in the latest release.

You should get an in-app update notification.

Thanks a lot for reporting this :)
