### ISSUE TITLE
Links to md-files and pdf-files not working in Mac-version

### ISSUE THREAD

**Issue by reisixx** [careteditor/caret#703]
These links work fine in the win-version, but they are not triggering any action on the Mac, although they are displayed as "active".

**Comment by astoilkov** [comment]
Hi @reisixx,

This seems like a duplicate of https://github.com/careteditor/caret/issues/704. Is it possible to answer the questions there?

Thanks in advance.

I will close this issue so we can continue the discussion in the other issue.
