### ISSUE TITLE
Hidding Sidebar doesn't re-center content

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#706]
Using Caret 4-rc4

Hiding the sidebar using the Ctrl+\ shortcut doesn't re-center content.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/615386/38054933-5ce5152c-32a6-11e8-9f2c-a57a5fa2ae39.gif)

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret Beta update.

Closing this issue. Thanks for reporting.
