### ISSUE TITLE
Renaming file outside of Caret freezes it

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#710]
Steps to make Caret 4.0.0-rc4 completely stuck:

1. Open `file.md` in Caret
2. Close Caret
3. Rename `file.md` to `renamed.md` on the disk
4. Open Caret again

It is completely stuck, showing the now non-existing `file.md` but not reacting to any keyboard or mouse inputs.

**Comment by netmasteroc3** [comment]
This also occurs when the file is deleted not just renamed.

**Comment by astoilkov** [comment]
We have fixed this in the latest Caret Beta update.

Closing this issue. Thanks for reporting.
