### ISSUE TITLE
Opening Caret when one of the files that were previously open is deleted causes it to crash on Windows

### ISSUE THREAD

**Issue by wbogocki** [careteditor/caret#717]
I don't think it this happens on Mac though but I can confirm if you want me to. I also had only one file open when it happened if that's relevant.

**Comment by astoilkov** [comment]
Hi Wojtek,

We indeed had such an issue but we fixed it in Caret Beta RC5. Can you check if you have updated your version to RC5 and if the problem persists there?

**Comment by wbogocki** [comment]
It should have happend on RC5 because I haven't updated since then. However I can't reproduce it anymore so maybe I just didn't notice the update or mybe it crashed for some other reason. I'll get back to you if it crashes again in a clearer context.
