### ISSUE TITLE
Template for new files

### ISSUE THREAD

**Issue by sambody** [careteditor/caret#727]
Each time I create a new document, to win time, I'd like it to have be prefilled with data. 

It could be as simple as already having the "#" (and a space) for the main title already in place, so that I can start typing the title immediately. Or it could be a template with YAML Front Matter or MultiMarkdown Metadata. Or anything else.

For that, the possibility to set a predefined template for new files would be useful.
(I'm using Caret 3.4.6)

**Comment by erusev** [comment]
Do you use a clipboard history app? It'd allow you to reuse templates or snippets (like YAML) super fast and without having to depend on the implementation of the specific apps.

**Comment by sambody** [comment]
I didn't think of that possibility. 
Thanks for the idea.
