### ISSUE TITLE
F3 as "find next" on Windows

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#733]
Small suggestion: maybe the "find next" command could be configurable via Keyboard Shortcuts – currently, it seems to be hardcoded for `Enter` but on Windows, another very common convention is `F3` which I'd like to set up.

**Comment by astoilkov** [comment]
We added F3 as a "find next" alternative shortcut. The next release will include it.

Is there a similar shortcut for "find prev" on Windows?

**Comment by borekb** [comment]
Shift+F3. Thanks!

**Comment by borekb** [comment]
Cool, it's working nicely in 4.0.0-rc8!

**Comment by astoilkov** [comment]
Great. Closing this issue.
