### ISSUE TITLE
Hitting enter on new paragraph goes to previous line

### ISSUE THREAD

**Issue by richardxu100** [careteditor/caret#739]
On the Mac version, I've experienced a bug where after hitting enter on a finished paragraph, the cursor will return to the previous paragraph.
![z3tb8gkj4u](https://user-images.githubusercontent.com/13954830/39681968-31af598c-517b-11e8-9295-fb6a6aa6ea55.gif)

**Comment by netmasteroc3** [comment]
I've seen this same problem in some cases on Windows (10, x64, build 1709) in the RC-5. Not sure what triggers it as it doesn't consistently happen. Seems like it might be some kind of hidden character or something as moving the cursor or deleting a character will make it behave normally.

**Comment by astoilkov** [comment]
Does this happen in the new Beta release of the app? We think we fixed this issue.

**Comment by richardxu100** [comment]
Hey @astoilkov I haven't experienced the issue since the latest update. I think it has been fixed.

**Comment by astoilkov** [comment]
Ok. Great. I will close this issue then.

If it happens again do not hesitate so we can investigate further.
