### ISSUE TITLE
Windows 10 Creator's Update slows down app (Beta v4.0.0-rc5)

### ISSUE THREAD

**Issue by mkjn** [careteditor/caret#742]
The [Windows 10 Creator's Update](http://www.businessinsider.com/microsoft-windows-10-fall-creators-update-whats-new-2017-10) was released last fall but only recently got installed on my laptop at work, where I am running the latest beta version of Caret.

Since that update installed, the beta version of Caret now runs very slowly. The app takes a little longer to launch, but the biggest problem is that there is so much lag when I try to type in any file in Caret that the app is pretty much unusable. The weird thing is, version 3 of Caret seems to work just fine – no lag.

The Creator's Update really hosed my laptop in a lot of ways – I'm not just having trouble with Caret. So maybe there's nothing really you can do about it.

But I wanted to mention it, since v3 now runs so much better than v4 on my machine...

Thanks,
jason
   jason@nichols.in

**Comment by astoilkov** [comment]
Hi @mkjn,

Can you take a look at the conversation [here](https://github.com/careteditor/caret/issues/675#issuecomment-386488640) and see if maybe you are experiencing the same problem.

Thanks in advance.

**Comment by mkjn** [comment]
Thanks for the feedback . . . It turns out, I already had Autosave turned off, so that doesn't seem to be the issue. I'm also not seeing the freezing or weird numbering issues described in the other conversation.

For me, the problem is just that there is significant lag when I try to type in any file, even if the file is a new blank document with no numbered lists and that's not part of a big GitHub repository or anything. Scrolling is fine – it's just with entering text that I see the issue.

FWIW, the Windows 10 Creator's update has annoyingly affected other apps as well, so Caret is not the only app where I'm seeing performance issues. Like I said, it's just weird that the update seems to have affected v4 but not v3...

Thanks again for your help...

**Comment by netmasteroc3** [comment]
@mkjn Have you tried uninstalling Caret and reinstalling it? 

I ran in to the same problem with RC5 a couple of weeks ago, where it was extremely laggy when I typed but otherwise behaved normally. I was about to open a bug report, but before I did I tried uninstalling and reinstalling (in part because I was going to revert to the early build to see if it was build related). After the reinstall caret was perfectly fine, then it updated automatically, and it was still perfectly fine.

**Comment by astoilkov** [comment]
@mkjn One more question from me. Are you have auto-correct functionality turned on?

**Comment by mkjn** [comment]
"Check Spelling" is turned on, but "Autocorrect spelling" is turned off. Thanks...

**Comment by mkjn** [comment]
Update: I tried uninstalling and reinstalling Caret, but that did not fix the issue. However, with the latest version of the beta (4.0.0-rc8), the problem seems to be resolved. Everything works fine, and there is no lag when typing.

I also just had a Windows 10 update install, so I don't know if you fixed something in your update, or if there was a bug fix in the Windows update that helped, but this issue is resolved for me now.

Thank you!
