### ISSUE TITLE
Malware Analyzation Suggestion (Includes Report doc)

### ISSUE THREAD

**Issue by legendarynacar** [careteditor/caret#743]
Hi there,

I wanna make a suggestion for your project about security. Many developer do not care or forget to care security for their projects. And it leads to pain in future because when the project become alive , users are scanning it. There are too many automation analyzers and they look for patterns generally to identify malwares.

While your project is in early ages, I suggest you to fix misunderstandings for automated systems. I think it will evolve your programming (algorithm) skills further.

I can not help on this because of lack of free time. And I think it would be better if the project owner (or team members) analyzes it.

Here is the file report for you to analyze. This service is lead on this field so in my humble opinion you can trust them.

https://www.hybrid-analysis.com/sample/29b9045ba70cd5576daa3b871cf08fcfa8811537e11cb9c62e54555cce327c3d

Best wishes,

**_Legendary Nacar_**

**Comment by astoilkov** [comment]
Hi @legendarynacar,

Thanks for the suggestion and for the detailed information. I did take a look at the report. However, the issues all seem related with [Electron](https://electronjs.org/) and [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows).

I would suggest creating issues in the repositories listed above giving the same report to them.

I will close the issue for now. However, if you have additional questions do not hesitate to contact us.
