### ISSUE TITLE
Document recovery is garbage

### ISSUE THREAD

**Issue by selfagency** [careteditor/caret#75]
I just spent two hours writing and forgot to hit save. Of course, my computer crashed. After I rebooted, Caret had saved the first five of 780 words. Garbage.

**Comment by erusev** [comment]
@selfagency I apologize for this accident, we'll investigate.

**Comment by astoilkov** [comment]
Hi @selfagency,

We have now improved the document recovery. We are caching the contents every minute. We apologize again for the problems caused.

**Comment by selfagency** [comment]
Thanks and sorry for the snippy post.
