### ISSUE TITLE
How to select all text in a document

### ISSUE THREAD

**Issue by healinginfluence** [careteditor/caret#756]
I am testing out Caret Beta. I am using it to write blog posts for my WordPress blog. I write the post and like the preview. I then want to select the entire text of the document, copy it and paste it into MarsEdit. 

I cannot find a way to select all the text in the document at once. Am I missing something obvious. That's how it feels.

**Comment by astoilkov** [comment]
Does `Ctrl+A` on Windows/Linux, `Cmd+A` on Mac work?

**Comment by healinginfluence** [comment]
Yes, it works. I was trying in the Selection menu. Thank you!

I do have one other question. Are footnotes supported? I don't see them showing up in preview.

**Comment by astoilkov** [comment]
Yes. Footnotes are supported. Here is the syntax:

```md
[^footnote]

[^footnote]: http://google.com
```

**Comment by healinginfluence** [comment]
Thank you. That's what I did but the footnote does not preview as a
footnote. This is a cut and paste from preview.

On top of the wonderful details that make Paris come to life, Downie's
prose shows a love and mastery[^1] of the English language that I
appreciate. This gem of a book will teach you so much about Paris and make
you want to return again and again or just to go to Paris and remain as
Downie has.

[^1:] This is a footnote.


David
enzel.io

**Comment by astoilkov** [comment]
I corrected your example so it can work. You just mistyped the position of the `:` sign. It should be in front of the bracket.

On top of the wonderful details that make Paris come to life, Downie's
prose shows a love and mastery[^1] of the English language that I
appreciate. This gem of a book will teach you so much about Paris and make
you want to return again and again or just to go to Paris and remain as
Downie has.

[^1]: This is a footnote.

**Comment by healinginfluence** [comment]
My mistake! Thank you for your help and patience. This app is exactly what
I was looking for! Thank you again.

David
enzel.io

**Comment by astoilkov** [comment]
No problem. I am happy you like the app. We are constantly improving it so stayed tuned for more awesome updates.

I am closing this issue. However, if you have more questions don't hesitate to contact us.
