### ISSUE TITLE
Feature request: warning for boundaty tuning parameters

### ISSUE THREAD

**Issue by kaurao** [careteditor/caret#758]
It will be extremely useful if caret threw a warning if the best tuning parameters selected for building the final model happen to be at the boundary of the search grid.

**Comment by astoilkov** [comment]
Hi @kaustubhrpatil,

I am not sure I understand you. Can you explain in a little more detail what is your scenario and what are you suggesting specifically? Screenshots would also help a lot.

Thanks in advance,
Antonio.

**Comment by kaurao** [comment]
oops posted on wrong repo, sorry about that!
