### ISSUE TITLE
Korean Input Issue

### ISSUE THREAD

**Issue by lyuha** [careteditor/caret#78]
Caret ignore first input of next character. Then, typing twice first key of next character.

If type `분류`, then show `분ㅠ`.

**Comment by erusev** [comment]
@lyuha Could you, please, explain in a little more detail? Thanks

**Comment by astoilkov** [comment]
Hi @lyuha,

We caught the problem. We have resolved it and the issue will be fixed when the new Caret release is available. Thanks for reporting this.

P.S. I will close this issue when we release the new Caret version.

**Comment by astoilkov** [comment]
Closing this issue as this fix is now part of the latest release.
