### ISSUE TITLE
Spacebar randomly does not work in the newest version

### ISSUE THREAD

**Issue by stegsaurus** [careteditor/caret#787]
I just updated to the latest version of Caret on Windows 10 (**4.0.0-rc14**) and noticed a strange bug. Randomly, the spacebar will stop responding and not enter any spaces no matter how many times you press it. 

Pressing **Enter** does fix the issue temporarily but it will pop up again before long. I tested this in several other apps, including Visual Studio Code, to ensure that it's not just my keyboard.

I'm using **Windows 10 Pro, version 1803, build 17134.191**.

I've also taken a short video of this behavior to illustrate it: https://streamable.com/8xxxj

**Comment by astoilkov** [comment]
We fixed the issue and release a new beta release. Sorry for the inconvenience.

Closing this issue.
