### ISSUE TITLE
Caret cursor is missing

### ISSUE THREAD

**Issue by richardxu100** [careteditor/caret#788]
It seems that the caret cursor has been removed in version 4.0.0-rc14. Are there plans to add the cursor back? If not, in a future release, would it be possible to add an option to make the standard cursor flicker (to help people find it on the screen easier)?

**Comment by astoilkov** [comment]
We made the standard cursor flicker for now. We also have future plans to improve the cursor. We released a version where the cursor flickers.

Closing this issue.
