### ISSUE TITLE
Built in external hyperlinks do nothing, throw error

### ISSUE THREAD

**Issue by huwd** [careteditor/caret#79]
I'm having trouble with the built in caret hyper links.

**OS**: Ubuntu 16.04
**Caret v**: 1.3.1

**Steps to Reproduce**

Open an outdated version of caret.io (currently 3.1) when a newer version has been released.
Small turquoise box appears at bottom:

> update available
> Visit caret.io to download it [x]

clicking the button does nothing for around .5 sec then opens new dialog:

> an error has occurred:
> submit on github | send error data [x]

Both of which also appear to do nothing. Will upgrade manually and then re-test.

**Comment by astoilkov** [comment]
Indeed there was such an issue. Try upgrading manually and get back to us. Thanks.

**Comment by huwd** [comment]
Ah ha, sorry was there already an open issue for this?

**Comment by astoilkov** [comment]
No public issue. Just in our private tracking system.

**Comment by huwd** [comment]
Ok I've upgraded, is there any way to coerce it into spitting out the dialog boxes or do i just wait for the next version release?

**Comment by astoilkov** [comment]
No. There isn't any way of doing this. We should wait for the next version release.

**Comment by huwd** [comment]
:+1:  Hokay, will do.
