### ISSUE TITLE
Issue with Show Preview and Show Files

### ISSUE THREAD

**Issue by sebastianf** [careteditor/caret#796]
If you have **Show Preview** and **Show Files** activated, theres is an issue with writing Section. In addtion the Windows size must have a larger widht. You can't see the beginning of the lines.

<img width="1376" alt="caret" src="https://user-images.githubusercontent.com/914661/44296744-9ca2ba00-a2c4-11e8-9512-258d12504b8e.png">

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret release.

Thanks for reporting. Closing this issue.
