### ISSUE TITLE
Easy way to identify version needed

### ISSUE THREAD

**Issue by huwd** [careteditor/caret#80]
Trying to post good issues for any ubuntu bugs I come across, however I find it easy to lose track of what version I'm currently running.

Would it be possible to a add a version dialog/about caret under help - so I can can quickly confirm i'm not leading you down the garden path with incorrect version numbers?

**Comment by astoilkov** [comment]
Hmm. 1.3.2 should have Version item in the Help menu. Can you verify that?

**Comment by huwd** [comment]
Doh, sorry shoulda upgraded first and then asked. Sorry!
