### ISSUE TITLE
Unsaved / dirty files not marked

### ISSUE THREAD

**Issue by weipah** [careteditor/caret#807]
I'm using Caret 4.0.0-rc20 and there seems to be no marker for unsaved files. 
It would be nice to have one.

**Comment by astoilkov** [comment]
This is probably because Autosave feature is turned on. If you disable Autosave it will start showing the unsaved marker.

You can try it and let me know.

**Comment by weipah** [comment]
@astoilkov ah, yes that explains it! I checked and I can see the small indicator now. Thanks a lot!
