### ISSUE TITLE
Right click -> open with caret not working as expected in Ubuntu Linux

### ISSUE THREAD

**Issue by Azeirah** [careteditor/caret#81]
### Expected behavior

Right clicking on a .md file in the file explorer, and selecting `open with caret` should open the file in caret ready for editing.

### Actual behavior

Caret opens, but shows the last edited file ready for editing, the selected file is nowhere to be seen.

### Reproduction

Ubuntu Linux 16.04, Unity

Right click a .md file -> `open with` -> `caret`

**Comment by erusev** [comment]
Thanks, we'll investigate.

**Comment by astoilkov** [comment]
I happy to say this is now fixed in the latest 1.3.3 release. You could head out to http://caret.io and download it.
