### ISSUE TITLE
Live preview mode, highlighting text puts the word count in the bottom right corner

### ISSUE THREAD

**Issue by Zhyll** [careteditor/caret#82]
In line preview mode, if you highlight text then the counter will appear over the top of the live preview, not in the middle of the screen as one would expect.

**Comment by astoilkov** [comment]
Can you post a screenshot of the problematic scenario so we could understand it better?

**Comment by Zhyll** [comment]
![carat preview error](https://cloud.githubusercontent.com/assets/2462168/15984161/3f5c1948-2fb9-11e6-8aec-acbe22af42ed.png)

**Comment by astoilkov** [comment]
This issue should be fixed in the latest release of Caret. Closing this. Do not hesitate to contact us if you find another problem. Have a great day.
