### ISSUE TITLE
Spelling mistake suggestions are awkward to use

### ISSUE THREAD

**Issue by Morganamilo** [careteditor/caret#821]
Caret-3.4.6

To list spelling mistake suggestions you must have your cursor already in the middle of the word. Usually I will go back and correct a sentence or paragraph after typing it. This means my cursor is usually at the end of the paragraph.

Right clicking a word then moves the cursor to the end of the word. Spelling suggestions are not shows here. Instead I need to close the right click menu, left click in the middle of the word and right click again.

Instead Right clicking a word should show suggestions regardless of where my cursor is.

**Comment by astoilkov** [comment]
Hi Anna,

This is fixed in the Caret Beta release which you can download from [our site](https://caret.io/).

I am closing this issue. Feel free to write to us if you encounter any other problem.
