### ISSUE TITLE
Files do not persist across Chromebook restart

### ISSUE THREAD

**Issue by jkff** [careteditor/caret#822]
I keep all kinds of random notes in an always-open window of a text editor (in several tabs). I normally used Sublime Text, but on CrOS I use Caret. The tabs serve as scratchpads and I don't save the files.

Unfortunately, if I power the Chromebook off and on, the files are lost. I've just lost some fairly valuable notes this way (I don't often power-cycle my Chromebook - this time it was just because it wanted to update the OS).

Please make the storage of unsaved files resilient to OS restarts.

**Comment by astoilkov** [comment]
Hi Eugene,

Can you share what version of Caret are you using? You can check that from the About Caret menu item.

Thanks in advance.

**Comment by jkff** [comment]
Hi! Thanks for the fast response. My Caret version is 1.8.13. In the OS update case, it seems like Caret also updated itself - however, I later double-checked that a regular no-update power cycle also discards the unsaved files.

**Comment by astoilkov** [comment]
Actually, we are currently working on Caret 4.0 Beta where this issue is fixed. I would recommend you to install Caret 4.0 from our [website](https://caret.io) and try it out. Note that there is a difference in the UI, how the app operates and the shortcuts it uses.

**Comment by jkff** [comment]
Thanks Antonio - however, seems that Caret 4.0 is only available for Windows/Linux/Mac? I'm on ChromeOS (a Pixelbook). Is there a respective fix coming to ChromeOS too?

**Comment by astoilkov** [comment]
Hi Eugene,

I think I know what is going on here. You are probably talking about [this project](http://thomaswilburn.net/caret/) that is available on ChromeOS. However, we are not the creators of this project. The only connection between the projects is the name.

**Comment by jkff** [comment]
Oh I see, thank you!

**Comment by astoilkov** [comment]
Happy we figured it out. Closing this issue.
