### ISSUE TITLE
Ordered list style in unordered list and performance issues

### ISSUE THREAD

**Issue by jsmolka** [careteditor/caret#825]
I used annotations of an ordered list inside an unordered one and I got both styles at the same time. To illustrate the issue I took a screenshot. I'd expect the numbers inside the unordered list to have no style at all and just be plain text. I am not sure if that's a bug or an intended feature.

![screen](https://user-images.githubusercontent.com/29958696/47518524-82202a80-d88b-11e8-94bb-70500b1aa931.png)

Apart from that I am experiencing some performance issues on my notebook when editing big documents. It feels a little unresponsive because not every letter is getting displayed immediately when writing fast. They get displayed in small groups of two or three at a time.

**Comment by astoilkov** [comment]
Hi Julian,

What you are experiencing with ordered lists inside of an unordered is correct by the [CommonMark](https://commonmark.org/) standard. You can verify that from [this example](https://spec.commonmark.org/dingus/?text=-%201.%20first%0A-%202.%20second).

Regarding the performance: Is it possible to share the file you are working with so we can test it on our side? If you are willing to share it you can send it via email on astoilkov@caret.io.

**Comment by jsmolka** [comment]
Starting Caret with Administrator Privileges fixed the performance issue.
