### ISSUE TITLE
Spell check: How to fix/activate auto suggest? How to ignore?

### ISSUE THREAD

**Issue by gandalfsaxe** [careteditor/caret#826]
Hi,

I get a bunch of dark underlines under words that I suspect are not in the system dictionary. That indicates that spell checking is enabled; so far as good.

But how do I then interact with the spell checker? How do I activate a dropdown menu with auto suggest options or ignore the word / add it to the dictionary?

**Comment by astoilkov** [comment]
Hi Gandalf,

You can interact with misspelled words by right-clicking on the word or by opening the context menu via `Ctrl+Space` or `Alt+Enter`.

Hope this helps.

**Comment by gandalfsaxe** [comment]
Hi,

Weird, right clicking didn't work for me. But now it does, perhaps after restarting the program.

Good tip with the keyboard shortcut, even two of then. I think you should put it in the application menu so one can easily find it, including the keyboard shortcut :)
