### ISSUE TITLE
Caret won't save

### ISSUE THREAD

**Issue by Zhyll** [careteditor/caret#83]
Caret doesn't save or export to PDF.

Windows 10,
Caret licence enabled.

**Comment by astoilkov** [comment]
By saying "doesn't save" what do you mean? It doesn't save documents when you hit `File->Save(Ctrl+S)` or it doesn't save the PDF exported document?

**Comment by Zhyll** [comment]
Neither, both result with this:
![carar save error](https://cloud.githubusercontent.com/assets/2462168/15984149/ada0be28-2fb8-11e6-87b4-3c376c83ca92.png)

This is true for `ctrl + s`, `File -> Save (Ctrl+S)`, `File -> Save as... (Ctrl+shift+S)` and `File -> Export to PDF...`

**Comment by astoilkov** [comment]
This issue is fixed in the latest 1.3.3 Caret release. Sorry for the inconvenience caused.
