### ISSUE TITLE
Linux: Caret can't Ctrl+backspace to delete a word

### ISSUE THREAD

**Issue by jc00ke** [careteditor/caret#84]
Running Ubuntu 16.04, Caret 1.3.2, I'm unable to delete a word by using `Ctrl+backspace`.

**Comment by Azeirah** [comment]
I've noticed this too, the role of the `ctrl` button has been moved to the `alt` button, alt-backspace to delete a word, alt-left to move a word to the left, etc..

**Comment by astoilkov** [comment]
Yes. Indeed that is the case. We will fix this behavior in our next release.

**Comment by astoilkov** [comment]
This issue is not fixed in the latest 1.3.3 release. Closing this issue. If we have missed something don't hesitate to reopen the issue.
