### ISSUE TITLE
Critical security vulnerability in Caret 4.0.0-rc21

### ISSUE THREAD

**Issue by manuelbua** [careteditor/caret#841]
Hi guys, i found a critical security issue in `Caret 4.0.0-rc21` and i would like to reach out to you privately so that i can give you the details without disclosing them publicly yet. Is there an email address i can write to?

**Comment by astoilkov** [comment]
@manuelbua Yes. You can reach out to me personally at astoilkov@caret.io. Thanks for your understanding!

**Comment by manuelbua** [comment]
Hi @astoilkov, this was fixed with `4.0-rc22` as of 21 November 2018 as per our mail exchange last year. I'm writing this so that it's publicly know this issue was also promptly resolved and can now request a CVE as well.

**Comment by astoilkov** [comment]
Great, thanks!
