### ISSUE TITLE
Allowing for scrolling while "dragging to select"

### ISSUE THREAD

**Issue by ftrotter** [careteditor/caret#844]
I am trying to copy long markdown documents from Caret to another system. But when I try to use my mouse to select large portions of the document, the interface does not "scroll up" or "scroll down" to allow me to select more text than shows on the screen at one time. 

This is standard behavior for word processors and most other UX's. But it does not seem to work in Caret.

**Comment by astoilkov** [comment]
This is definitely on the roadmap. We are aware of the issue. I will close this issue because there are two other issues that report the same thing. https://github.com/careteditor/issues/issues/718 https://github.com/careteditor/issues/issues/518
