### ISSUE TITLE
Clicking "open" does not open a file chooser

### ISSUE THREAD

**Issue by ftrotter** [careteditor/caret#845]
When selecting the "open" from the main menu (OSX) the expectation is that a file chooser would appear, asking which file to open. Instead, it merely opens a new editor window. Then it requires a user to click "open" again and then the file chooser is shown.

**Comment by astoilkov** [comment]
We replicated the problem. We will fix it.

Thanks for reporting.

**Comment by ftrotter** [comment]
Thanks for taking this request... I am assuming it is likely already fixed... closing to reduce cruft..
