### ISSUE TITLE
Tasklists checked-item theming improvement

### ISSUE THREAD

**Issue by eatcodeplay** [careteditor/caret#859]
Hi,

i've been using Caret for a while now ( not using the Beta yet ). I've come to use the Task-Lists quite
a lot, but always hated the way the checkbox looked on Win 10. So i finally decided to customize the dark-theme for myself.

![Image of Yaktocat](https://i.imgur.com/hJJNhAu.jpg)

I've been able to easily change the checkbox behaviour, but what i am missing, is the capability to strikethrough the text when an item is checked / completed.

While looking at your generated HTML i noticed the DOM Structure doesn't allow for manipulating the `label` or `li` to set the text as striked via CSS.

I suggest / would love to see a `.checked` css-class added to the li or label.

This way, current behaviour won't be affected, but if someone (me 😜 ) wants to actually do something with it, they can 😉

**Comment by astoilkov** [comment]
Thanks for the idea. We will see what we can do.
