### ISSUE TITLE
No Readline Library in v1.3.2?

### ISSUE THREAD

**Issue by zackmore** [careteditor/caret#86]
Hi guys,

after updated to v1.3.2 I could not move the cursor around use C-a / C-e and etc any more. That's a little lame when you use mouse or the arrow keys.

Is there any chance will add this feature back?

**Comment by erusev** [comment]
Hi Qin, what do you mean by "C-a" and "C-e"? Thanks.

**Comment by zackmore** [comment]
Ah sorry my fault. "C-a" means "Ctrl + a": jump to the start of current line; "C-e" means "Ctrl + e": jump to the end of current line. And others like "C-f", "C-b", "C-n", "C-p", all of these keyboard combinations just like editing in Emacs or the normal input field on webpage, or in terminal.

For more information about Readline Library: https://cnswww.cns.cwru.edu/php/chet/readline/readline.html

**Comment by erusev** [comment]
Thanks, Qin, we'll see what we can do :)

**Comment by astoilkov** [comment]
Hi @zackmore,

These shortcuts should be working fine now. You could update to the latest version of Caret and see if everything is working correctly. Closing this issue. Do not hesitate to reopen it if we have missed something.
