### ISSUE TITLE
Uninstall/reinstall Caret completely Mac

### ISSUE THREAD

**Issue by dbollaer** [careteditor/caret#863]
I wanted to try out a beta version from caret. So I tried installing from the github repo.

I could not open any file any more.
I received an X on my screen instead of the file.

I removed the beta version and reinstalled the stable version.
But the problem persists.

How do I completely reinstall caret?

I am using mac.

Thank you in advance.

**Comment by astoilkov** [comment]
Hi Danny,

Can you share a screenshot of the problem? I am not sure I understand the problem. Is it true that both `File -> Open` and clicking on a file in the sidebar doesn't work?

If you want to reinstall Caret you just need to go delete the `.app` file and the folder where we keep the cache which is located under `/Users/your-user/Libary/Application Support/Caret`.

**Comment by dbollaer** [comment]
Removing and reinstalling fixed my issue, thank you @astoilkov
