### ISSUE TITLE
Completely unusable w/ Korean IME in Windows

### ISSUE THREAD

**Issue by beingryu** [careteditor/caret#87]
I haven't tested in other OSs, but in Windows, Caret doesn't support Korean inputs very well (like most of the new text editors). As East-Asian IMEs usually go together, this would imply that all CJK IMEs won't work properly. The text renders great though.

I have bought the license at the early stage, and am willing to provide any information and help to make it work on my system.

It's not easy to explain what's the expected behavior, but I'll try my best:

1. Refer to [this article](https://koreanvitamin.wordpress.com/2012/09/06/how-to-type-korean-hangul-on-windows-7/) to enable korean IME and soft keyboard. (FYI: By default, it'll use the input mode called 2-beol-sik)
2. Click '한/영' key to toggle between Korean alphabets and English alphabets input mode.
3. In Korean input mode, try the following input sequence: "ㄱ, ㅏ, ㄴ, ㅏ, ㄷ, ㅏ, ㄹ, ㅏ, ㅁ, ㅏ". In qwerty, the keys correspond to "r, k, s, k, e, k, f, k, a, k". This should be rendered as "가나다라마", but in Caret it reads "가다마", so seems like a completed character is sometimes ignored.
4. More complicated example would be "ㄷㅏㄹㅏㅁㅈㅜㅣ (space) ㅎㅓㄴ (space) ㅊㅔㅅㅂㅏㅋㅜㅣㅇㅔ (space) ㅌㅏㄱㅗㅍㅏ", which corresponds to "e k f k a w n l (space) g j s (space) c p t q k z n l d p (space) x k r h v k". It should be rendered as "다람쥐 헌 쳇바퀴에 타고파", but in Caret it produces "다ㅁㅟ헌쳇ㅏㅟㅔ타파". It's completely messed up.

Please let me know if you need any assistance from me. Thanks!

Best,
Wonha

**Comment by beingryu** [comment]
Oops, a duplicate of #78. Please close it if the test sequence renders well :)

**Comment by astoilkov** [comment]
We have tested your scenarios and everything should be working fine in the latest Caret release. You could wait for an update notification in your application.
