### ISSUE TITLE
[Feature Request] Having an Option to Hide the Menu

### ISSUE THREAD

**Issue by ardian** [careteditor/caret#88]
Hi there,

It would be awesome if you can add an option to hide the main menu in the editor, to be more clear take a look the screenshot that is attached.

--------------------------------
![caret-menu](https://cloud.githubusercontent.com/assets/172661/16135260/95a40aa0-3422-11e6-97cd-f72cc99d93be.png)

OS: GNU/Linux Fedora
DE: GNOME 3.20

**Comment by erusev** [comment]
Hi Adrian, we'll see what we can do, thanks.

**Comment by ardian** [comment]
Awesome!, thanks a lot for the option.
