### ISSUE TITLE
Feature Request - Hide a section of text

### ISSUE THREAD

**Issue by AntoineCheron** [careteditor/caret#880]
Hi Caret developers,

To work more easily on long documents, it would be very nice to be able to hide/show a section of code, with a toggle, like Visual Studio Code does. 

I hope this short video could help you visualize the idea: https://streamable.com/bszew.

Continue the great job! Thank you all

**Comment by astoilkov** [comment]
Hi Antoine,

I can't see the video it seems it is still being processed. However, is this similar to [this thread](https://github.com/careteditor/issues/issues/376)?

**Comment by AntoineCheron** [comment]
Yes you’re right, sorry for the duplicate.
