### ISSUE TITLE
Better higlighting for search results in dark mode

### ISSUE THREAD

**Issue by eevleevs** [careteditor/caret#881]
Hi, I find that the colours used for highlighting search results in dark mode have poor contrast, and it is difficult to visualise the matches. I use Tomorrow Night (bright), but seems to be a common problem for most of the dark themes. Please consider brighter highlight colours in dark mode.

**Comment by astoilkov** [comment]
Hi Giulio,

We only have one dark theme. What do you mean by Tomorrow Night?

![image](https://user-images.githubusercontent.com/884810/64110132-e9e7b180-cd89-11e9-9534-fb827aef9b83.png)

**Comment by eevleevs** [comment]
Sorry, wrong repo. Evidently there is more than one Caret editor.
