### ISSUE TITLE
Asciidoctor support?

### ISSUE THREAD

**Issue by jmfayard** [careteditor/caret#885]
Hello,
Caret seems really nice. 

Would you consider adding support for asciidoc?
https://asciidoctor.org/docs/user-manual/#what-is-asciidoctor

I am well aware that Markdown is currently the de facto standard. Nevertheless it shows its limits really soon, even if most people are not immediatly aware of it. 

I agree with Alan Key that:

> “Simple things should be simple, complex things should be possible.”

Markdown did successfully the first half, but is a total failure for the second. That's why nobody is using a "standard Markdown" (there is not such things) but always start with Markdown and add to it its mutually incompatible extensions. For example we are here on GitHub so we have "GitHub flavored markdown". If you use a static website generator, you have "markdown plus front-matter". On "pets.com", we would have "Pets flavored markdown". Etc...

Asciidoc on the other hand is as easy as Markdown for the simple things, but scales much better when you need more features. It was originally designed to be a user-friendly alternative to the DocBook XML schema, so you won't probably never feel the need to add your "XXX flavored asciidoc".

More information here:
https://asciidoctor.org/docs/user-manual/#compared-to-markdown

**Comment by astoilkov** [comment]
Hi,

Indeed Markdown isn't a perfect solution. It has its problems.

I like asciidoc. I started imagining we could bring it to the app but then I realized we are a small team and supporting a second syntax would be a development challenge we don't have the resources to do. We are developing Caret for 4 years and we still have bugs, features, and improvements related to Markdown support.

The other opinion is to pivot and support only asciidoc. The problem I see in this solution is that Markdown is widely adopted well-known syntax used by a few of the largest organization in the world.

**Comment by jmfayard** [comment]
Yes that make sense. Change is hard

**Comment by astoilkov** [comment]
I am closing this issue.

**Comment by astoilkov** [comment]
If you have thoughts on that or arguments that could support asciidoc I am open to discussion.

I am closing this issue for now. I will reopen if a new discussion arises.
