### ISSUE TITLE
[Issue] Cursor in the middle of a character 

### ISSUE THREAD

**Issue by ardian** [careteditor/caret#89]
Hey there,

I am having a really big issue with this, I am not sure if it is a feature and I am not really getting how to use it but it doesn't always happen, How I manage to fix this, when this problem appears, I enable or disable the Mid-Screen Scrolling.

I have also captured a screenshot of this, hope this helps resolving this issue, it can get really annoying because everything you write goes one character further. 

OS: GNU/Linux (Fedora 24)
DE: Gnome 3.20 

![caret-bug](https://cloud.githubusercontent.com/assets/172661/16362320/7fa8c0b0-3bac-11e6-8be9-408be4a190b0.png)

**Comment by erusev** [comment]
Thanks @ardian, did you write in English when this happened? Thanks again.

**Comment by ardian** [comment]
Hey @erusev yes I was writing an English article.

**Comment by erusev** [comment]
Do you think there's a character or a particular element type that triggers it? Thanks.

**Comment by ardian** [comment]
I am not sure about that, I will do some testing and see what triggers it.

**Comment by erusev** [comment]
Thanks, that'd be great.

**Comment by astoilkov** [comment]
We believe we found the cause of the problem. It happened in Roboto Mono font after an `_italic_` definition. We included a fix in the latest release of Caret.

Closing this issue for now. If you experience the problem in the new version do not hesitate to reopen the issue.
