### ISSUE TITLE
What is 'continued use'

### ISSUE THREAD

**Issue by keunes** [careteditor/caret#891]
I saw Caret [here](https://github.com/mundimark/awesome-markdown-editors) and it looks nice. But before I install it - what does 'for continued use' mean, when you're talking about pricing?

**Comment by dioncodes** [comment]
And the last update was 2 years ago (beta 4.0), looks like it isn't in development anymore...

**Comment by astoilkov** [comment]
Let me first answer the first question which slipped without being answered. When Caret works without a license the app shows a popup that prompts you to buy it. By 'continued use' we want to say that if you are working with the app a lot you will probably want to buy it and avoid the distraction.

Regarding the development status: We are actually working full time to bringing a new product which will be very similar to Caret. You can read our statement here – https://twitter.com/careteditor/status/1136198029357264896.

**Comment by keunes** [comment]
Thanks @astoilkov for your reply. The pop-up is mentioned nowhere and I must say the 'continued use' is rather confusing. In the context of its sentence ("For continued use Purchase License at $29") it sounds like Caret is free to use for a limited period (implying registration is necessary). I'd recommend updating this when you're updating the website when launching the new version of Caret.

**Comment by astoilkov** [comment]
@keunes I agree. We have actually already changed that in the new website which isn't still published. We now have a dedicated Purchase page with FAQ section. Thanks for the suggestions!
