### ISSUE TITLE
jump to previous/next header

### ISSUE THREAD

**Issue by debrouwere** [careteditor/caret#9]
I don't really understand the purpose of `cmd-]` and `cmd-[`. Perhaps on Windows it's different, but on Mac you can just use `option-down` and `option-up` to achieve more or less the same behavior. It would perhaps be more interesting to have `cmd-]` and `cmd-[` jump to the previous or next header, so you can easily navigate back to a previous section.

(Though perhaps there are better ways to quickly get an overview of your document and to navigate to different sections. This is just something to think about, not really a feature request.)

**Comment by erusev** [comment]
That's another great suggestion. We do plan to have something like a quick overview of the document - it'd be a view that shows the headers in the document and lets people navigate and fuzzy search through them (similar to the file navigation), but it make sense to have shortcuts for next / previous header as well.

**Comment by astoilkov** [comment]
Hi @debrouwere,

In the latest version of Caret there is a Headings navigation that shows all headings in the document. When opened it selects the current heading so navigation between previous and next header could be achieved using `Cmd+G`, pressing `Tab` or `Shift+Tab` and hitting Enter.

Do you think this is useful for your scenario?

**Comment by debrouwere** [comment]
Yep, I really like the headings view!

**Comment by astoilkov** [comment]
Really happy to hear this.

In this case I will close the issue. If you have other suggestions or ideas do not hesitate to open a new issue.
