### ISSUE TITLE
Freeze when I create a table in the software - Version 4.0.0-rc23

### ISSUE THREAD

**Issue by ABWhiskey** [careteditor/caret#906]
Hello

I recently started using this software and I have a rather annoying little problem, let me explain:

On an empty document, I create a table in Markdown for example:

```markdown
| ID | VALUE |
```

It does create the table for me, but when I fill the table, at one point, the application starts to freeze for several seconds, gives me back control, then goes back to freezes and that, in a loop.

I restart the application and the same, as soon as the file is loaded, the freezes start again.

The only way to have more such freezes is to remove the table and restart.

Apparently, this problem only occurs during the creation of a table. I have not seen this problem on other **Markdown** instructions.

Also note that after (and during) freezes, the application process runs at 15% of the CPU without even using it.

I tested to remove the autosave and spell checker, but that does not change anything.

I am on **win 10 Home 64 bit** and Caret version is **4.0.0-rc23**.

Is there a solution to this problem ?, Because at the moment the application is not usable for me.

PS: I tested on an earlier version (3.4.6) and it seems that the freeze problem is not present.

---

Another small detail that has nothing to do with the freeze problem: Why when quitting the application, does it create a screenshot (launch__w1.png) in the roaming folder (appdata) ?

Thank you,

Attached, a file which can reproduce my freezes (.md file).

[FreezeProblem.zip](https://github.com/careteditor/issues/files/5612028/FreezeProblem.zip)

**Comment by astoilkov** [comment]
Thanks for reporting the table problem. We will look into it.

In the meantime, you can request access to our new app which is almost the same - https://nota.md. We will send you an invitation shortly after.

---

The `screenshot (launch__w1.png)` is an interesting concept we are using. We make a screenshot of the app before it quits and when the app starts show that screenshot so people can start visually processing the content before all the initialization code is done and the app becomes responsive.

**Comment by ABWhiskey** [comment]
Thank you for your answer, hoping that this bug is found and especially corrected. I love using this software, but unfortunately with this problem it is quite difficult for me to continue with it. I use a lot of table :p

**Comment by whippingdot** [comment]
> In the meantime, you can request access to our new app which is almost the same - https://nota.md. We will send you an invitation shortly after.

Did you stop working on caret? The last release was in 2018. If you stopped working on this and you starting only working on nota.md please send me an invitation too(even though I will probably use nota no matter what). Also will nota.md be paid in the future? I don't want to use it for some time and then have to stop using it when it becomes paid.

**Comment by astoilkov** [comment]
@whippingdot We received your request so we will send you an invite soon. Nota will use the same model as Caret – it will be paid but you will be able to use all its features for free if you don't mind seeing a purchase prompt from time to time.

**Comment by ABWhiskey** [comment]
And for my freeze problem, a solution ? Currently, I have paid for an application which is unusable (due to freezes) .... Too bad, Caret looked promising, but looks completely abandoned. No follow-up to this problem, no updating of the application.

**Comment by astoilkov** [comment]
@ABWhiskey You are right. We should have worked on this but Nota takes all our available time. If you haven't been satisfied with Caret you can write to us and request a refund.

Sorry for the situation. 😞

**Comment by ABWhiskey** [comment]
I take note, I will see this possibility in the next days. Thank you anyway. I close this topic.

**Comment by whippingdot** [comment]
> @whippingdot We received your request so we will send you an invite soon. Nota will use the same model as Caret – it will be paid but you will be able to use all its features for free if you don't mind seeing a purchase prompt from time to time.

I am sorry, but I want to ask when does soon mean @astoilkov
