### ISSUE TITLE
Menu access on left side vs. right side of window

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#91]
Menu access is typically done on the left side of the window (on Windows OS at least). Recently (not sure what version) the file access was moved to the right with the rest of the windows controls. 

I feel strongly that menu access should stay in the left hand side. I can see why it's attractive to keep all window controls in one neat area instead of splitting them off, but I think it's detrimental to usability.

In terms of grouping, the close, minimize and maximize/restore buttons make sense together, they are actions that act on the actual window. On the other hand, the menu largely contains actions that act on the windows content. So positioning it on the left hand side would make more sense group wise because we naturally read from left to right (in english anyways), so it's naturally a prime real estate for important controls, and the menu is something I access more often than the close or minimize buttons.

**Comment by erusev** [comment]
Makes sense, we'll see what we can do.

**Comment by astoilkov** [comment]
We have moved the app menu on the left side of the app in the latest Caret 1.6.1 version. You could check it out.

Closing this issue.
