### ISSUE TITLE
There is no documentation

### ISSUE THREAD

**Issue by EanNewton** [careteditor/caret#913]
This all started because I clicked File > Backups which came up with a text entry box and no further explanation as to what it does or how to use it and nothing I tried seemed to actually _do anything_.

Inside the app I checked the Help menu and there is no actual help section, just an About, Check for Updates, Visit Website, etc.

On the website there is a "docs" link the footer but it only creates a popup saying "Coming soon..."

This app has been out for almost 7 years now according to your copyright; there should be at least a basic user manual at this point.

**Comment by astoilkov** [comment]
Hi. We've been concentrating on [Nota](https://nota.md) lately. We plan to grow Nota's [documentation](https://nota.md/docs) but don't have plans to introduce docs for Caret.

Are you on macOS? If yes, you can request an invite and we will send you a download link. If not, you can request an invite and we will let you know when it's available for other operating systems.

**Comment by EanNewton** [comment]
macOS is the only system I do not run. Windows / Linux / Unix yes, but have
never touched macOS due to the price of entering their ecosystem

**Comment by EanNewton** [comment]
Closing this as I have received an answer, not the answer I was hoping for but an answer. Thank you
