### ISSUE TITLE
Heading Table of Contents [toc] 

### ISSUE THREAD

**Issue by jasondavis** [careteditor/caret#92]
It would be cool if we could put something like `[toc]` in the Markdown and it would generate a table of contents style list menu with all the headings similar to the heading menu created in the **Jump to Heading** menu.

The list menu created would show up in the HTML in the location that  `[toc]`  is at so it would simply replace  `[toc]`  in the HTML.

The headings would then link to each heading section so the headings wouls also need to generate something like `<a id=heading1">` so that the heading links would take you to that section of the page when clicked.

**Comment by erusev** [comment]
Makes sense.

It'd be great if you could point us to a a web document that has a well-styled table of contents? It might help us get more excited about the feature :)

**Comment by jasondavis** [comment]
I think a simple `<ul>` unordered list with a special class name applied to the HTML would be good so that the user can define how the TOC looks.

Then maybe have some sort of template tag to allow the user to display the TOC HTML anywhere in the HTML output.  I mean they would call the TOC template tag in there markdown text where they want iut to show the TOC in the HTML output.  The TOC tag would be replaced with a real TOC HTML block though.

Some other editors also allow to set custom HTML output in the header of an exported HTML file.  Also custom CSS themes.  This is getting off topic though!

Something simple like Wikipedia pages have would be good I think....  

![chrome_2016-07-21_11-47-05](https://cloud.githubusercontent.com/assets/186818/17029414/1ce7b4b8-4f39-11e6-888a-e6a622d935e8.png)

**Comment by erusev** [comment]
Thanks @jasondavis we'll see what we can do.

**Comment by astoilkov** [comment]
We implemented `[[toc]]` syntax in the latest version of Caret. You could upgrade to try it out.

**Comment by jasondavis** [comment]
Very cool!  Thanks for taking my request and making it happen so quickly.  Hopefully others will enjoy the new feature as well.  I am still looking at the other updates in the new version....

Actively developed new software updates are better than a Christmas morning to me.  I remember SublimeText 2 when it had almost daily updates for a good 6+ months.

Its a great way to keep people interested in your product and grow the userbase so I look forward to what the future brings, good luck and thanks

- Jason Davis

**Comment by erusev** [comment]
Thanks @jasondavis that's great to hear :)
