### ISSUE TITLE
Spell Check doesn't work

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#94]
Not sure how spell check is supposed to work, but I opened a new file and typed random keys and nothing was underlined. 

![image](https://cloud.githubusercontent.com/assets/615386/16738160/87eade4a-4762-11e6-9c09-cbdf5f01fd65.png)

Anything I should be doing for it to work? I checked in the preference menu and it was checked enabled.

**Comment by astoilkov** [comment]
On what version of Windows are you?

Thanks.

**Comment by sguergachi** [comment]
Windows 7


-
Sammy Guergachi

**Comment by sguergachi** [comment]
Seems to work now, maybe 1.4 fixed it.
