### ISSUE TITLE
Menu bars absent [Ubuntu/Gnome]

### ISSUE THREAD

**Issue by huwd** [careteditor/caret#95]
I've just spotted that the menu bars have disappeared after recent updates. I'm afraid I can't pinpoint which version they disappeared on.

**Expected Behavior**
I ran a quick check against other programs to ensure it wasn't a global setting. The Nylas example below shows how menus usually appear:

![nylas](https://cloud.githubusercontent.com/assets/3694062/16766661/3d3a28fc-4833-11e6-93ac-08b357fd476c.jpg)

**Actual Behaviour**
Instead it's missing now, which gives me a nice clean screen but no way to access menu items.

![caret](https://cloud.githubusercontent.com/assets/3694062/16766687/6599322a-4833-11e6-99ea-7ec6403c1e44.jpg)

Have they been removed? Or is there a hotkey to show/hide them now?

**System**
Ubuntu Gnome 16.04LTS

**Comment by astoilkov** [comment]
Does the menu show if you press the Alt key?

**Comment by huwd** [comment]
... yes... well I feel like an idiot.

Thanks!
