### ISSUE TITLE
Pressing left arrow key while using Mid-Screen Scrolling disables Mid-Screen Scrolling

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#96]
Here's a demo of the problem: 

https://cl.ly/gidH

The problem happens when I press the left arrow to go back through the text. I expect the scroll position to stay the same.

**Comment by astoilkov** [comment]
Thanks for reporting this problem. I will start working on it right away.

**Comment by astoilkov** [comment]
I fixed the issue. I will close the issue when we release the next version where the fix will be included.

**Comment by astoilkov** [comment]
The fix for this issue is now included in the latest Caret release.

Thanks for reporting.
