### ISSUE TITLE
Feature Request: Recent Documents

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#97]
Would be nice to see the 3 most recent documents under the File menu item.

**Comment by astoilkov** [comment]
Have you tried using `Cmd+E` for recent files. It supports fuzzy search so it's very convenient to use.

**Comment by sguergachi** [comment]
I will try that, thanks.


-
Sammy Guergachi

**Comment by sguergachi** [comment]
That seems to work fine. Thanks
