### ISSUE TITLE
Restore and Maximize icons should be different

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#98]
In Windows, when you maximize a window the restore icon is displayed (the current icon in the app). But when the window is not maximized the maximize icon should be displayed, see any Windows native app for examples.

**Comment by astoilkov** [comment]
Yes. We are aware of this issue. We will fix it.

Thanks.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 1.6.1 version.

Closing this issue.
