### ISSUE TITLE
Give user control over font size

### ISSUE THREAD

**Issue by yuppity** [careteditor/caret#99]
Caret limits the user to three predefined font sizes. The smallest of these sizes can not really be considered small at all and this forces the user to either to lend Caret considerable amount of screen real estate or look at a very small subset of the text at a time. This seems like an unnecessary, arbitrary limitation (the font size) and it's not readily apparent what the reasoning behind such a limitation is, which leads me to believe it's an oversight.

Would be great if you could address this by stating whether this is something you plan to change in the _near_ future.

**Comment by erusev** [comment]
Makes sense, we'll see what we can do.

**Comment by yuppity** [comment]
That is great news. Thank you!

**Comment by erusev** [comment]
No problem, thanks for the very well written issue.

**Comment by borekb** [comment]
In 1.10, there are four predefined steps. On my quite a small, high density laptop screen (<13'', 1080p) I need to use larger fonts but the largest zoom is too large and the one below that jumps significantly to quite a small font.

It would be good to have more control over this.

**Comment by astoilkov** [comment]
It tooks us a while but we implemented Preferences which are available in the latest Caret 1.13.0 release. You could edit font, font size, line width and line height there.

Closing this issue.
